# Generated by Django 6.0.2 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=50)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['tier_name', 'billing_period'],
                'unique_together': {('tier_name', 'billing_period')},
            },
        ),
    ]
