# Generated by Django 6.0.2 on 2026-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(help_text='Access level (0, 10, 20, 30). Higher = more access.', unique=True)),
                ('price_eur_month', models.IntegerField(blank=True, help_text='Monthly price in EUR. Null for free tier.', null=True)),
                ('price_eur_year', models.IntegerField(blank=True, help_text='Yearly price in EUR. Null for free tier.', null=True)),
                ('stripe_price_id_monthly', models.CharField(blank=True, default='', help_text='Stripe Price ID for monthly billing.', max_length=255)),
                ('stripe_price_id_yearly', models.CharField(blank=True, default='', help_text='Stripe Price ID for yearly billing.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown on the pricing page.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature descriptions for the pricing page.')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
