# Generated by Django 6.0.2 on 2026-02-18 22:11

from django.db import migrations

# Bootstrap-only seed: the four tier rows must exist on a fresh DB so that
# foreign-key references from other tables hold and `user.tier.level >= X`
# access checks resolve. Beyond ``slug`` and ``level``, the migration only
# writes a placeholder ``name`` (the slug, title-cased). Every other
# editable field (``price_eur_*``, ``stripe_price_id_*``, ``description``,
# ``features``) is populated by the tiers.yaml content sync, which is now
# the single source of truth.
#
# The placeholder ``name`` is required because the ``Tier.name`` column is
# a non-nullable ``CharField`` without ``blank=True`` and without a DB
# default; without it, ``get_or_create`` would insert an empty string and
# break the pricing page, account page, and email interpolations that
# reference ``tier.name`` before the first content sync runs. The
# placeholder values happen to match the canonical yaml names, so the
# yaml sync is a no-op on a freshly-migrated DB.
TIERS = [
    {"slug": "free", "level": 0, "name": "Free"},
    {"slug": "basic", "level": 10, "name": "Basic"},
    {"slug": "main", "level": 20, "name": "Main"},
    {"slug": "premium", "level": 30, "name": "Premium"},
]


def seed_tiers(apps, schema_editor):
    Tier = apps.get_model("payments", "Tier")
    for tier_data in TIERS:
        Tier.objects.get_or_create(slug=tier_data["slug"], defaults=tier_data)


def remove_tiers(apps, schema_editor):
    Tier = apps.get_model("payments", "Tier")
    Tier.objects.filter(slug__in=["free", "basic", "main", "premium"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_tier"),
    ]

    operations = [
        migrations.RunPython(seed_tiers, remove_tiers),
    ]
