# Generated by Django 6.0.2 on 2026-02-18 22:11

from django.db import migrations


TIERS = [
    {
        "slug": "free",
        "name": "Free",
        "level": 0,
        "price_eur_month": None,
        "price_eur_year": None,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "description": (
            "Subscribe to the newsletter and access open content. "
            "No payment required."
        ),
        "features": [
            "Newsletter emails",
            "Access to open content",
        ],
    },
    {
        "slug": "basic",
        "name": "Basic",
        "level": 10,
        "price_eur_month": 20,
        "price_eur_year": 200,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "description": (
            "Access curated educational content, tutorials, and research. "
            "Perfect for self-directed builders who learn at their own pace."
        ),
        "features": [
            "Exclusive articles",
            "Tutorials with code examples",
            "AI tool breakdowns",
            "Research notes",
            "Curated social posts",
        ],
    },
    {
        "slug": "main",
        "name": "Main",
        "level": 20,
        "price_eur_month": 50,
        "price_eur_year": 500,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "description": (
            "Everything in Basic, plus the structure, accountability, "
            "and peer support to ship your AI projects consistently."
        ),
        "features": [
            "Everything in Basic",
            "Slack community access",
            "Group coding sessions",
            "Project-based learning",
            "Community hackathons",
            "Career discussions",
            "Personal brand guidance",
            "Topic voting",
        ],
    },
    {
        "slug": "premium",
        "name": "Premium",
        "level": 30,
        "price_eur_month": 100,
        "price_eur_year": 1000,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "description": (
            "Everything in Main, plus structured learning paths through "
            "mini-courses and personalized career guidance."
        ),
        "features": [
            "Everything in Main",
            "All mini-courses",
            "Mini-course topic voting",
            "Resume/LinkedIn/GitHub teardowns",
        ],
    },
]


def seed_tiers(apps, schema_editor):
    Tier = apps.get_model("payments", "Tier")
    for tier_data in TIERS:
        Tier.objects.get_or_create(slug=tier_data["slug"], defaults=tier_data)


def remove_tiers(apps, schema_editor):
    Tier = apps.get_model("payments", "Tier")
    Tier.objects.filter(slug__in=["free", "basic", "main", "premium"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_tier"),
    ]

    operations = [
        migrations.RunPython(seed_tiers, remove_tiers),
    ]
