# Generated by Django 6.0.2 on 2026-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_seed_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(help_text='Stripe event ID (e.g. evt_xxx). Used for idempotency.', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Stripe event type (e.g. checkout.session.completed).', max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw event payload for debugging.')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
