# Generated by Django 6.0.2 on 2026-04-17 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_utmcampaign_utmcampaignlink'),
        ('payments', '0004_webhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(help_text='Stripe Checkout session ID. Unique constraint provides a second idempotency layer beyond WebhookEvent.', max_length=255, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', help_text='Stripe subscription ID for subscription mode; blank for one-off course purchases.', max_length=255)),
                ('billing_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Inferred from which Stripe price ID was used at checkout. Blank for one-off course purchases.', max_length=20)),
                ('amount_eur', models.IntegerField(blank=True, help_text="Price the user paid, in whole EUR (matches Tier.price_eur_* convention). Null for free/comped or course-purchase flows where tier price doesn't apply.", null=True)),
                ('mrr_eur', models.IntegerField(blank=True, help_text='Normalized monthly recurring revenue in EUR for this conversion: amount_eur for monthly, amount_eur // 12 for yearly, null for one-off.', null=True)),
                ('first_touch_utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Conversion timestamp (when checkout.session.completed was processed).')),
                ('first_touch_campaign', models.ForeignKey(blank=True, help_text='Resolved by matching first-touch utm_campaign to UtmCampaign.slug at conversion time. Null when no matching campaign exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.utmcampaign')),
                ('last_touch_campaign', models.ForeignKey(blank=True, help_text='Resolved by matching last-touch utm_campaign to UtmCampaign.slug at conversion time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.utmcampaign')),
                ('tier', models.ForeignKey(blank=True, help_text='The tier purchased at this conversion (snapshot — do not follow later tier changes). Null for one-off course purchases where there is no tier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.tier')),
                ('user', models.ForeignKey(help_text='The user who paid. PROTECT so we never silently drop attribution rows when a user is hard-deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='conversion_attributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Attribution',
                'verbose_name_plural': 'Conversion Attributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='payments_co_created_74e9bc_idx'), models.Index(fields=['first_touch_utm_campaign'], name='payments_co_first_t_5f3c62_idx'), models.Index(fields=['last_touch_utm_campaign'], name='payments_co_last_to_db357c_idx')],
            },
        ),
    ]
