# Generated by Django 6.0.2 on 2026-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_conversionattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Exception summary for failed_permanent rows (truncated). Empty for processed rows.'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('failed_permanent', 'Failed (permanent)')], default='processed', help_text="Terminal outcome. 'processed' = handler ran cleanly. 'failed_permanent' = handler raised WebhookPermanentError; Stripe is told to stop retrying.", max_length=32),
        ),
    ]
