# Generated by Django 6.0.2 on 2026-07-02 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_webhookevent_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccountMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(help_text='Stripe Checkout Session ID that produced the conflict.', max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_email', models.EmailField(help_text='Billing email from Stripe.', max_length=254)),
                ('reason', models.CharField(choices=[('primary_email_collision', 'Primary email collision'), ('alias_collision', 'Alias collision'), ('unknown_reference', 'Unknown reference')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('candidate_user', models.ForeignKey(blank=True, help_text='Existing primary/alias owner that collided, when known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_mismatches_as_candidate_user', to=settings.AUTH_USER_MODEL)),
                ('paid_user', models.ForeignKey(help_text='User who received entitlement from client_reference_id.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_mismatches_as_paid_user', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payment_mismatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_f8e2cb_idx'), models.Index(fields=['stripe_customer_id'], name='payments_pa_stripe__90aa91_idx'), models.Index(fields=['stripe_session_id'], name='payments_pa_stripe__3062e0_idx'), models.Index(fields=['stripe_email'], name='payments_pa_stripe__60959b_idx')],
            },
        ),
    ]
