# Generated by Django 6.0.2 on 2026-07-14 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_privacy_retention_user_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccountmismatch',
            name='reason',
            field=models.CharField(choices=[('primary_email_collision', 'Primary email collision'), ('alias_collision', 'Alias collision'), ('unknown_reference', 'Unknown reference'), ('invalid_binding', 'Invalid checkout binding'), ('expired_binding', 'Expired checkout binding'), ('binding_user_unavailable', 'Checkout binding user unavailable'), ('binding_reused', 'Checkout binding already used'), ('binding_purpose_mismatch', 'Checkout binding purpose mismatch'), ('unpaid_checkout', 'Checkout is not paid'), ('incomplete_checkout', 'Checkout is not complete'), ('stripe_mode_mismatch', 'Stripe mode mismatch'), ('missing_price', 'Checkout Price missing'), ('tier_mismatch', 'Purchased tier mismatch'), ('billing_email_mismatch', 'Billing email mismatch'), ('legacy_reference_mismatch', 'Legacy reference mismatch'), ('subscription_conflict', 'Subscription conflict'), ('customer_conflict', 'Customer conflict'), ('out_of_order_subscription_event', 'Out-of-order subscription event')], max_length=40),
        ),
        migrations.CreateModel(
            name='CheckoutAccountBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('source', models.CharField(default='authenticated_pricing', editable=False, max_length=40)),
                ('purpose', models.CharField(default='membership_checkout', editable=False, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.tier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_account_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('quarantined', 'Quarantined')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binding', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment', to='payments.checkoutaccountbinding')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.tier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_fulfillments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_ch_status_86971f_idx'), models.Index(fields=['stripe_customer_id'], name='payments_ch_stripe__42deae_idx'), models.Index(fields=['stripe_subscription_id'], name='payments_ch_stripe__b7d61e_idx')],
            },
        ),
    ]
