# Generated by Django 6.0.2 on 2026-07-24 07:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_paymentaccountmismatch_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEndpointCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('studio', 'Studio'), ('api', 'API')], default='studio', max_length=16)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('fail', 'Fail')], max_length=16)),
                ('key_mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('expected_url', models.CharField(blank=True, default='', max_length=500)),
                ('matching_endpoint_id', models.CharField(blank=True, default='', max_length=255)),
                ('endpoint_status', models.CharField(blank=True, default='', max_length=64)),
                ('enabled_events', models.JSONField(blank=True, default=list)),
                ('missing_events', models.JSONField(blank=True, default=list)),
                ('unexpected_events', models.JSONField(blank=True, default=list)),
                ('api_version', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_endpoint_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('stripe_delivery', 'Stripe delivery'), ('operator_replay', 'Operator replay')], default='stripe_delivery', max_length=32)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('stripe_object_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('livemode', models.BooleanField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('outcome', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('already_processed', 'Already processed'), ('ignored_stale', 'Ignored (stale subscription)'), ('unmatched_user', 'Unmatched user (retryable)'), ('ambiguous_user', 'Ambiguous user (terminal)'), ('failed_transient', 'Failed (transient)'), ('failed_permanent', 'Failed (permanent)')], default='received', max_length=32)),
                ('http_status', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('requested_by', models.ForeignKey(blank=True, help_text='Operator who requested a replay; null for Stripe deliveries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_webhook_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'received_at'], name='payments_st_event_t_0bcdc9_idx'), models.Index(fields=['outcome', 'received_at'], name='payments_st_outcome_fee0fb_idx')],
            },
        ),
    ]
