# Generated by Django 6.0.2 on 2026-07-25 02:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_stripewebhookendpointcheck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('mode', models.CharField(choices=[('diagnostic', 'Diagnostic (read-only)'), ('apply', 'Apply (confirmed writes)')], default='diagnostic', max_length=16)),
                ('source', models.CharField(choices=[('scheduled', 'Scheduled'), ('studio', 'Studio'), ('api', 'API')], default='scheduled', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cohort_count', models.IntegerField(default=0)),
                ('ok_count', models.IntegerField(default=0)),
                ('scheduled_cancellation_count', models.IntegerField(default=0)),
                ('actionable_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('changed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_reconciliation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionReconciliationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('current_tier', models.CharField(blank=True, default='', max_length=64)),
                ('current_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_status', models.CharField(blank=True, default='', max_length=64)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_period_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_tier', models.CharField(blank=True, default='', max_length=64)),
                ('webhook_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_event_type', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_event_status', models.CharField(blank=True, default='', max_length=64)),
                ('webhook_processed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_evidence', models.CharField(choices=[('processed', 'Processed'), ('failed_permanent', 'Failed (permanent)'), ('missing', 'Missing'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=32)),
                ('classification', models.CharField(max_length=64)),
                ('action', models.CharField(blank=True, default='', max_length=64)),
                ('outcome', models.CharField(choices=[('reported', 'Reported'), ('would_change', 'Would change'), ('changed', 'Changed'), ('skipped', 'Skipped'), ('warning', 'Warning'), ('error', 'Error')], default='reported', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('conflicting_user_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_reconciliation_findings', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='payments.subscriptionreconciliationrun')),
            ],
            options={
                'ordering': ['classification', 'email'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionreconciliationrun',
            index=models.Index(fields=['status', 'started_at'], name='payments_su_status_abe2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionreconciliationrun',
            index=models.Index(fields=['mode', 'started_at'], name='payments_su_mode_3463ab_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionreconciliationfinding',
            index=models.Index(fields=['run', 'classification'], name='payments_su_run_id_51d52e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionreconciliationfinding',
            index=models.Index(fields=['user', 'run'], name='payments_su_user_id_868e81_idx'),
        ),
    ]
