# Generated by Django 6.0.2 on 2026-08-12 07:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0021_reconcile_emaillog_subject_default'),
        ('payments', '0011_subscriptionreconciliationrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='collection_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='effective_tier',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='interval',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='interval_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='latest_invoice_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='latest_invoice_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='latest_invoice_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='latest_invoice_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='payment_grace_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='payment_grace_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='payment_grace_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='MonthlyPaymentGrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('stripe_invoice_id', models.CharField(max_length=255)),
                ('livemode', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(choices=[('webhook', 'Webhook'), ('reconciliation', 'Reconciliation')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('recovered', 'Recovered'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('review', 'Review')], default='active', max_length=16)),
                ('interval', models.CharField(max_length=16)),
                ('interval_count', models.PositiveIntegerField()),
                ('grace_started_at', models.DateTimeField()),
                ('grace_expires_at', models.DateTimeField()),
                ('policy_enforced_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_failure_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_tier_at_start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_payment_graces', to='payments.tier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payment_graces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-grace_started_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionreconciliationfinding',
            name='payment_grace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_findings', to='payments.monthlypaymentgrace'),
        ),
        migrations.CreateModel(
            name='MonthlyPaymentGraceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('failure_member', 'Initial member failure'), ('failure_team', 'Initial team failure'), ('reminder_member', 'Member reminder'), ('expired_member', 'Member expiry')], max_length=32)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('transport_started_at', models.DateTimeField(blank=True, null=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_payment_grace_deliveries', to='email_app.emaillog')),
                ('grace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='payments.monthlypaymentgrace')),
            ],
            options={
                'ordering': ['grace_id', 'kind', 'recipient'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlypaymentgrace',
            index=models.Index(fields=['status', 'grace_expires_at'], name='payments_mo_status_474839_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypaymentgrace',
            index=models.Index(fields=['user', 'status'], name='payments_mo_user_id_9b9130_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypaymentgrace',
            index=models.Index(fields=['stripe_subscription_id'], name='payments_mo_stripe__2d8998_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypaymentgrace',
            index=models.Index(fields=['stripe_invoice_id'], name='payments_mo_stripe__0b5dd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlypaymentgrace',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='payments_one_active_monthly_grace_per_user'),
        ),
        migrations.AddConstraint(
            model_name='monthlypaymentgrace',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('stripe_invoice_id', ''), _negated=True), ('livemode__isnull', False)), fields=('stripe_invoice_id', 'livemode'), name='payments_unique_monthly_grace_invoice_mode'),
        ),
        migrations.AddConstraint(
            model_name='monthlypaymentgrace',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('stripe_invoice_id', ''), _negated=True), ('livemode__isnull', True)), fields=('stripe_invoice_id',), name='payments_unique_monthly_grace_invoice_unknown_mode'),
        ),
        migrations.AddConstraint(
            model_name='monthlypaymentgrace',
            constraint=models.CheckConstraint(condition=models.Q(('interval_count__gt', 0)), name='payments_monthly_grace_interval_count_positive'),
        ),
        migrations.AddIndex(
            model_name='monthlypaymentgracedelivery',
            index=models.Index(fields=['status', 'claimed_at'], name='payments_mo_status_ffba50_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlypaymentgracedelivery',
            constraint=models.UniqueConstraint(fields=('grace', 'kind', 'recipient'), name='payments_unique_monthly_grace_delivery'),
        ),
        migrations.AddConstraint(
            model_name='monthlypaymentgracedelivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='payments_monthly_grace_attempts_nonnegative'),
        ),
    ]
