# Generated by Django 6.0.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_monthly_payment_grace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutfulfillment",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("payment_failed", "Payment failed"),
                    ("fulfilled", "Fulfilled"),
                    ("quarantined", "Quarantined"),
                ],
                max_length=20,
            ),
        ),
    ]
