# Generated by Django 6.0.2 on 2026-09-02 08:43

import re

from django.db import migrations, models

_BATCH_SIZE = 500
_MAX_BIGINT = 2**63 - 1
_INTEGER_RE = re.compile(r"[0-9]+\Z")

_CHECKOUT_EVENT_TYPES = frozenset({
    "checkout.session.completed",
    "checkout.session.async_payment_succeeded",
    "checkout.session.async_payment_failed",
})
_INVOICE_EVENT_TYPES = frozenset({
    "invoice.payment_failed",
    "invoice.paid",
})
_CUSTOMER_EVENT_TYPES = frozenset({"customer.updated"})
_SUBSCRIPTION_EVENT_TYPES = frozenset({
    "customer.subscription.updated",
    "customer.subscription.deleted",
})
_REFUND_EVENT_TYPES = frozenset({"charge.refunded"})
_PROVIDER_EVENT_TYPES = (
    _CHECKOUT_EVENT_TYPES
    | _INVOICE_EVENT_TYPES
    | _CUSTOMER_EVENT_TYPES
    | _SUBSCRIPTION_EVENT_TYPES
    | _REFUND_EVENT_TYPES
    | frozenset({"charge.dispute.created", "charge.dispute.closed"})
)
_INTERNAL_EVENT_TYPES = frozenset({
    "backfill_stripe_tiers",
    "subscription_reconciliation_apply",
})


def _safe_string(value, max_length):
    """Return an exact, bounded string correlation value."""
    if not isinstance(value, str) or not value or value != value.strip():
        return ""
    if len(value) > max_length:
        return ""
    return value


def _safe_provider_id(value):
    """Read a provider ID from a string or an expanded object ID."""
    if isinstance(value, dict):
        value = value.get("id")
    return _safe_string(value, 255)


def _safe_user_id(value):
    """Read only a positive decimal local user ID."""
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        number = value
    elif (
        isinstance(value, str)
        and len(value) <= len(str(_MAX_BIGINT))
        and _INTEGER_RE.fullmatch(value)
    ):
        number = int(value)
    else:
        return None
    if number <= 0 or number > _MAX_BIGINT:
        return None
    return number


def _subject_user_id(obj):
    if not isinstance(obj, dict):
        return None
    metadata = obj.get("metadata")
    candidates = []
    if isinstance(metadata, dict) and "user_id" in metadata:
        candidate = _safe_user_id(metadata["user_id"])
        if candidate is not None:
            candidates.append(candidate)
    if "client_reference_id" in obj:
        candidate = _safe_user_id(obj["client_reference_id"])
        if candidate is not None:
            candidates.append(candidate)
    distinct = set(candidates)
    return next(iter(distinct)) if len(distinct) == 1 else None


def _stripe_event_correlations(event_type, payload):
    """Extract only the frozen, event-owned Stripe paths."""
    if event_type not in _PROVIDER_EVENT_TYPES:
        return None, "", ""
    if not isinstance(payload, dict):
        return None, "", ""
    data = payload.get("data")
    obj = data.get("object") if isinstance(data, dict) else None
    if not isinstance(obj, dict):
        return None, "", ""

    customer_id = ""
    subscription_id = ""
    if event_type in _CHECKOUT_EVENT_TYPES | _INVOICE_EVENT_TYPES:
        customer_id = _safe_provider_id(obj.get("customer"))
        subscription_id = _safe_provider_id(obj.get("subscription"))
    elif event_type in _CUSTOMER_EVENT_TYPES:
        customer_id = _safe_provider_id(obj.get("id"))
    elif event_type in _SUBSCRIPTION_EVENT_TYPES:
        customer_id = _safe_provider_id(obj.get("customer"))
        subscription_id = _safe_provider_id(obj.get("id"))
    elif event_type in _REFUND_EVENT_TYPES:
        customer_id = _safe_provider_id(obj.get("customer"))

    return _subject_user_id(obj), customer_id, subscription_id


def _internal_event_correlations(event_type, payload):
    if event_type not in _INTERNAL_EVENT_TYPES or not isinstance(payload, dict):
        return None, "", ""

    customer_id = _safe_provider_id(payload.get("stripe_customer_id"))
    subscriptions = {
        value
        for key in ("stripe_subscription_id", "subscription_id", "old_subscription_id")
        for value in [_safe_provider_id(payload.get(key))]
        if value
    }
    subscription_id = next(iter(subscriptions)) if len(subscriptions) == 1 else ""
    return _safe_user_id(payload.get("user_id")), customer_id, subscription_id


def _stripe_correlations(row):
    if row.event_type in _INTERNAL_EVENT_TYPES:
        return _internal_event_correlations(row.event_type, row.payload)
    return _stripe_event_correlations(row.event_type, row.payload)


def _calendly_correlations(payload):
    if not isinstance(payload, dict):
        return "", ""
    inner = payload.get("payload")
    if not isinstance(inner, dict):
        return "", ""
    scheduled_event = inner.get("scheduled_event")
    event_uri = _safe_string(
        scheduled_event.get("uri") if isinstance(scheduled_event, dict) else None,
        500,
    )
    invitee_uri = _safe_string(inner.get("uri"), 500)
    return event_uri, invitee_uri


def _flush_updates(model, rows, fields):
    if rows:
        model.objects.bulk_update(rows, fields, batch_size=_BATCH_SIZE)


def _backfill_stripe_events(WebhookEvent):
    pending = []
    fields = ["subject_user_id", "stripe_customer_id", "stripe_subscription_id"]
    for row in WebhookEvent.objects.order_by("pk").iterator(chunk_size=_BATCH_SIZE):
        subject_user_id, customer_id, subscription_id = _stripe_correlations(row)
        changed = False
        if row.subject_user_id is None and subject_user_id is not None:
            row.subject_user_id = subject_user_id
            changed = True
        if not row.stripe_customer_id and customer_id:
            row.stripe_customer_id = customer_id
            changed = True
        if not row.stripe_subscription_id and subscription_id:
            row.stripe_subscription_id = subscription_id
            changed = True
        if changed:
            pending.append(row)
            if len(pending) >= _BATCH_SIZE:
                _flush_updates(WebhookEvent, pending, fields)
                pending = []
    _flush_updates(WebhookEvent, pending, fields)


def _backfill_calendly_logs(WebhookLog):
    pending = []
    fields = ["calendly_event_uri", "calendly_invitee_uri"]
    rows = WebhookLog.objects.filter(service="calendly").order_by("pk")
    for row in rows.iterator(chunk_size=_BATCH_SIZE):
        event_uri, invitee_uri = _calendly_correlations(row.payload)
        changed = False
        if not row.calendly_event_uri and event_uri:
            row.calendly_event_uri = event_uri
            changed = True
        if not row.calendly_invitee_uri and invitee_uri:
            row.calendly_invitee_uri = invitee_uri
            changed = True
        if changed:
            pending.append(row)
            if len(pending) >= _BATCH_SIZE:
                _flush_updates(WebhookLog, pending, fields)
                pending = []
    _flush_updates(WebhookLog, pending, fields)


def backfill_webhook_correlations(apps, schema_editor):
    """Populate safe correlation columns without rewriting retained JSON."""
    _backfill_stripe_events(apps.get_model("payments", "WebhookEvent"))
    _backfill_calendly_logs(apps.get_model("integrations", "WebhookLog"))


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_stripewebhookdeliveryattempt_refund_review'),
        ('integrations', '0029_webhooklog_calendly_event_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', help_text='Safe Stripe customer correlation identifier.', max_length=255),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', help_text='Safe Stripe subscription correlation identifier.', max_length=255),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='subject_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Stable local user identifier from an app-owned Stripe correlation. Intentionally not a foreign key so retained events survive account deletion.', null=True),
        ),
        migrations.RunPython(
            backfill_webhook_correlations,
            migrations.RunPython.noop,
        ),
    ]
