# Generated by Django 6.0.2 on 2026-09-08 21:27

from django.conf import settings
from django.db import migrations, models

_BATCH_SIZE = 500


def _flush_updates(Attempt, rows):
    if rows:
        Attempt.objects.bulk_update(
            rows,
            ["attempt_number"],
            batch_size=_BATCH_SIZE,
        )


def renumber_delivery_attempts(apps, schema_editor):
    """Make every event's attempt sequence dense before adding uniqueness."""
    Attempt = apps.get_model("payments", "StripeWebhookDeliveryAttempt")
    current_event_id = None
    next_number = 0
    pending = []
    attempts = Attempt.objects.order_by(
        "stripe_event_id",
        "received_at",
        "pk",
    )
    for attempt in attempts.iterator(chunk_size=_BATCH_SIZE):
        if attempt.stripe_event_id != current_event_id:
            current_event_id = attempt.stripe_event_id
            next_number = 1
        else:
            next_number += 1

        if attempt.attempt_number != next_number:
            attempt.attempt_number = next_number
            pending.append(attempt)
        if len(pending) >= _BATCH_SIZE:
            _flush_updates(Attempt, pending)
            pending = []

    _flush_updates(Attempt, pending)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_webhookevent_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            renumber_delivery_attempts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='stripewebhookdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('stripe_event_id', 'attempt_number'), name='uniq_stripe_event_attempt'),
        ),
    ]
