# Generated by Django 6.0.2 on 2026-09-08 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_unique_webhook_attempt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period. Null for free users.', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', help_text='Stripe customer ID.', max_length=255)),
                ('subscription_id', models.CharField(blank=True, default='', help_text='Stripe/MoR subscription ID.', max_length=255)),
                ('pending_tier', models.ForeignKey(blank=True, help_text='Tier scheduled after downgrade at billing_period_end.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_memberships', to='payments.tier')),
                ('tier', models.ForeignKey(blank=True, help_text="Current membership tier. Defaults to 'free' on creation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='payments.tier')),
                ('user', models.OneToOneField(help_text='The user this membership profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
