# Generated by Django 6.0.2 on 2026-09-15 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mail', '0005_callbackevent_occurred_at_callbackevent_sequence_and_more'),
        ('payments', '0018_backfill_memberships_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypaymentgracedelivery',
            name='email_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cb_mail.emaildelivery'),
        ),
    ]
