# Generated by Django 6.0.2 on 2026-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_monthlypaymentgracedelivery_email_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypaymentgracedelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=16),
        ),
    ]
