# Generated by Django 6.0.2 on 2026-02-19 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0007_course_module_unit_usercourseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown description of the event.')),
                ('description_html', models.TextField(blank=True, default='', help_text='Auto-generated HTML from description markdown.')),
                ('event_type', models.CharField(choices=[('live', 'Live'), ('async', 'Async')], default='live', max_length=10)),
                ('start_datetime', models.DateTimeField(help_text='Start date/time of the event.')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='End date/time of the event (optional).', null=True)),
                ('timezone', models.CharField(default='Europe/Berlin', help_text='Timezone for the event (e.g. Europe/Berlin).', max_length=100)),
                ('zoom_meeting_id', models.CharField(blank=True, default='', help_text='Zoom meeting ID (populated for live events).', max_length=255)),
                ('zoom_join_url', models.URLField(blank=True, default='', help_text='Zoom join URL (populated for live events).', max_length=500)),
                ('location', models.CharField(blank=True, default='', help_text='Location description (e.g. "Zoom" for live, or a GitHub repo for async).', max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to register.')),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants. Null means unlimited.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(blank=True, help_text='Link to the recording after event completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.recording')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
