# Generated by Django 6.0.2 on 2026-02-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('custom', 'Custom URL')], default='zoom', help_text='Platform for the event: Zoom or a custom external URL.', max_length=20),
        ),
    ]
