# Generated by Django 6.0.2 on 2026-03-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recording',
        ),
        migrations.AddField(
            model_name='event',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='core_tools',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of tool names.'),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='Cover image URL from content repo.', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of objective strings.'),
        ),
        migrations.AddField(
            model_name='event',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {title, url, type}.'),
        ),
        migrations.AddField(
            model_name='event',
            name='outcome',
            field=models.TextField(blank=True, default='', help_text='Text describing expected outcome.'),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, help_text='Controls visibility on the recordings page.'),
        ),
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Datetime of first publish.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recording_embed_url',
            field=models.URLField(blank=True, default='', help_text='Legacy Google Drive embed URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='recording_s3_url',
            field=models.URLField(blank=True, default='', help_text='S3 raw recording file URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='recording_url',
            field=models.URLField(blank=True, default='', help_text='Primary video URL (YouTube, S3, etc.).', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='related_course',
            field=models.CharField(blank=True, default='', help_text='Slug of a related course.', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_bio',
            field=models.TextField(blank=True, default='', help_text='Speaker bio from content repo frontmatter.'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_name',
            field=models.CharField(blank=True, default='', help_text='Speaker name from content repo frontmatter.', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='timestamps',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {time_seconds, label}.'),
        ),
        migrations.AddField(
            model_name='event',
            name='transcript_text',
            field=models.TextField(blank=True, default='', help_text='Plain-text transcript content for display and search.'),
        ),
        migrations.AddField(
            model_name='event',
            name='transcript_url',
            field=models.URLField(blank=True, default='', help_text='URL to the VTT transcript file.', max_length=500),
        ),
    ]
