# Generated by Django 6.0.2 on 2026-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventjoinclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ics_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Sequence number for .ics calendar invite updates.'),
        ),
    ]
