# Generated by Django 6.0.2 on 2026-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_ics_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recap',
            field=models.JSONField(blank=True, default=dict, help_text='Structured recap landing page sections. See docs for schema.'),
        ),
    ]
