# Generated by Django 6.0.2 on 2026-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_recap'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('q_and_a', 'Q&A')], default='standard', help_text='Event sub-type used by the unified events feed: standard recording, workshop (linked to a Workshop row), meetup, or Q&A.', max_length=20),
        ),
    ]
