# Generated by Django 6.0.2 on 2026-04-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, help_text='Controls visibility on the /events?filter=past page.'),
        ),
    ]
