# Generated by Django 6.0.2 on 2026-04-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_instructor_models'),
        ('events', '0009_alter_event_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order; 0 is the primary speaker.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.instructor')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('event', 'instructor')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors / speakers for this event. Order is controlled via the EventInstructor.position field. The first instructor is mirrored into the legacy speaker_name/speaker_bio fields by the sync pipeline.', related_name='events', through='events.EventInstructor', to='content.instructor'),
        ),
    ]
