# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recap_file',
            field=models.CharField(blank=True, default='', help_text='Content-repo markdown file used to render the recap page.', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_markdown',
            field=models.TextField(blank=True, default='', help_text='Raw synced markdown body for the recap page.'),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_html',
            field=models.TextField(blank=True, default='', help_text='Rendered recap HTML, including content-repo includes.'),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data from recap frontmatter / event recap_data for include rendering.'),
        ),
    ]
