# Generated by Django 6.0.2 on 2026-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_remove_course_instructor_bio_and_more'),
        ('events', '0012_remove_event_type_and_live_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker_bio',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors / speakers for this event. Order is controlled via the EventInstructor.position field; the first instructor is the primary speaker shown on listings and cards.', related_name='events', through='events.EventInstructor', to='content.instructor'),
        ),
    ]
