# Generated by Django 6.0.2 on 2026-05-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_event_speaker_bio_remove_event_speaker_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown description shown on the public series page.')),
                ('description_html', models.TextField(blank=True, default='', help_text='Auto-generated HTML from description markdown.')),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly')], default='weekly', help_text='Cadence label. v1 supports weekly only.', max_length=20)),
                ('cadence_weeks', models.PositiveIntegerField(default=1, help_text='Reserved for the "every N weeks" stretch goal. v1 always stores 1 and the generator uses 7 days between occurrences.')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Day of the week of the first occurrence. Stored on the series so the cadence label survives per-event drift.')),
                ('start_time', models.TimeField(help_text='Time of day (24-hour) of the first occurrence.')),
                ('timezone', models.CharField(default='Europe/Berlin', help_text='IANA timezone name, e.g. Europe/Berlin.', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='origin',
            field=models.CharField(choices=[('github', 'GitHub'), ('studio', 'Studio')], default='studio', help_text='Authoritative source-of-truth gate. ``github`` rows are managed by the sync pipeline; ``studio`` rows are authored in Studio and never touched by sync.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='series_position',
            field=models.PositiveIntegerField(blank=True, help_text='1-indexed position within the parent event group.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ForeignKey(blank=True, help_text='Optional parent series. Deleting the group preserves the events but unlinks them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventgroup'),
        ),
    ]
