# Generated by Django 6.0.2 on 2026-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_backfill_event_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_host',
            field=models.CharField(blank=True, default='', help_text='Display name of the third-party host (e.g. "Maven", "Luma", "DataTalksClub"). Leave blank for community-hosted events.', max_length=100),
        ),
    ]
