# Generated by Django 6.0.2 on 2026-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_event_group_to_event_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hide flag. When False the series is hidden from public series listings; existing occurrences keep their own per-event status.'),
        ),
    ]
