# Generated by Django 6.0.2 on 2026-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventseries_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_event_summary',
            field=models.TextField(blank=True, default='', help_text='Markdown summary used as the body of the post-event follow-up email. Leave blank for the generic fallback copy.'),
        ),
    ]
