# Generated by Django 6.0.2 on 2026-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_seriesregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the title used to render the current ``auto_banner_url``. Used to detect title drift between syncs.', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #895). Overwritten by the auto-banner pipeline; templates should prefer ``cover_image_url`` and fall back to this.', max_length=500),
        ),
    ]
