# Generated by Django 6.0.2 on 2026-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_auto_banner_title_hash_event_auto_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the series ``name`` used to render the current ``auto_banner_url``. Used to detect name drift between renders.', max_length=64),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #788). Templates should prefer an operator cover and fall back to this. Series have no operator cover today, so this is the only banner image.', max_length=500),
        ),
    ]
