# Generated by Django 6.0.2 on 2026-06-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_eventseries_auto_banner_title_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseries',
            name='cadence_weeks',
        ),
    ]
