# Generated by Django 6.0.2 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_eventseries_cadence_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
    ]
