# Generated by Django 6.0.2 on 2026-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_custom_banner_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='zoom_meetings_last_run',
            field=models.JSONField(blank=True, default=None, help_text="Issue #859: structured summary of the most recent 'Create Zoom meetings for all events' background run. Shape: ``{finished_at, created: [event_id], skipped_existing: n, skipped_ineligible: n, failed: [{event_id, title, error}]}``. Null until the action has run at least once.", null=True),
        ),
    ]
