# Generated by Django 6.0.2 on 2026-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_eventseries_zoom_meetings_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_email',
            field=models.EmailField(blank=True, default='', help_text='Email address that receives the host calendar invite (with host-only management links). Leave blank to use the default host mailbox configured in Studio settings.', max_length=254),
        ),
    ]
