# Generated by Django 6.0.2 on 2026-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_host_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
