# Generated by Django 6.0.2 on 2026-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_eventregistration_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title_is_auto',
            field=models.BooleanField(default=True, help_text='True when the occurrence title is auto-generated from the series name + chronological position, so it is rewritten on series rename / renumber. Set False the moment an operator supplies an explicit title (then it is sacrosanct).'),
        ),
    ]
