# Generated by Django 6.0.2 on 2026-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_heal_series_draft_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Canonical access level for the series (issue #958). New occurrences inherit this level when no level is supplied, and occurrence writes via the API are validated against it (a mismatch is rejected; Studio allows a human-confirmed override). Changing this value never rewrites the levels of occurrences that already exist.'),
        ),
    ]
