# Generated by Django 6.0.2 on 2026-06-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_backfill_description_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
    ]
