# Generated by Django 6.0.2 on 2026-06-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_host_eventhost_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_email',
            field=models.EmailField(blank=True, default='', help_text='Email address of a platform user who should be auto-registered as the event host attendee. Leave blank to skip host auto-registration.', max_length=254),
        ),
    ]
