# Generated by Django 6.0.2 on 2026-06-17 15:52

from django.db import migrations, models

HOST_TITLES = {
    'alexey-grigorev': 'Chief Agent Officer at AI Shipping Labs',
    'valeriia-kuka': 'Content Strategist',
}


def backfill_host_titles(apps, schema_editor):
    Host = apps.get_model('events', 'Host')
    for slug, title in HOST_TITLES.items():
        Host.objects.filter(slug=slug).update(title=title)


def clear_host_titles(apps, schema_editor):
    Host = apps.get_model('events', 'Host')
    Host.objects.filter(slug__in=HOST_TITLES).update(title='')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_event_host_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(backfill_host_titles, clear_host_titles),
    ]
