# Generated by Django 6.0.2 on 2026-07-14 19:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0019_emaillog_dedupe_key'),
        ('events', '0041_event_recording_upload_enqueued_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_access_version',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Rotated whenever host_email changes so previously issued host-management links are revoked.', null=True),
        ),
        migrations.CreateModel(
            name='HostInviteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_ics_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('access_version', models.UUIDField()),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_app.emaillog')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_invite_deliveries', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_invite_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user', 'access_version'), name='unique_host_invite_delivery')],
            },
        ),
    ]
