# Generated by Django 6.0.2 on 2026-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_event_host_access_version_hostinvitedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseries',
            name='cadence',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('none', 'No fixed cadence')], default='weekly', help_text="Cadence label. 'weekly' or 'none' (No fixed cadence, a plain collection with no schedule).", max_length=20),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text="Day of the week of the first occurrence. Stored on the series so the cadence label survives per-event drift. Null for a 'No fixed cadence' collection (issue #1358).", null=True),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='start_time',
            field=models.TimeField(blank=True, help_text="Time of day (24-hour) of the first occurrence. Null for a 'No fixed cadence' collection (issue #1358).", null=True),
        ),
    ]
