# Generated by Django 6.0.2 on 2026-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_eventseries_cadence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recap_notes',
            field=models.TextField(blank=True, default='', help_text='Studio/API-authored recap notes for this event (Markdown). Never written by content sync.'),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_notes_html',
            field=models.TextField(blank=True, default='', editable=False, help_text='Rendered HTML for recap_notes.'),
        ),
    ]
