# Generated by Django 6.0.2 on 2026-08-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_event_recap_notes_event_recap_notes_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesOccurrenceOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_opt_outs', to='events.event')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_opt_outs', to='events.eventseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_occurrence_opt_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
