# Generated by Django 6.0.2 on 2026-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_seriesoccurrenceoptout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, help_text='Controls visibility on the public past events list (/events?filter=past).'),
        ),
    ]
