# Generated by Django 6.0.2 on 2026-08-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0021_reconcile_emaillog_subject_default'),
        ('events', '0046_alter_event_published_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInviteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_ics_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=64)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_app.emaillog')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_invite_delivery', to='events.eventregistration')),
            ],
        ),
    ]
