# Generated by Django 6.0.2 on 2026-08-31 17:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_guestinvitedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_access_version',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Rotated whenever host_email changes so a reassigned host receives a fresh invitation.', null=True),
        ),
    ]
