# Generated by Django 6.0.2 on 2026-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_event_host_access_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recording_zoom_download_url',
            field=models.URLField(blank=True, db_default='', default='', help_text='Zoom MP4 download URL from recording.completed. Stored so a stuck upload can be reclaimed without the original queue args.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='recording_upload_enqueued_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Renewable 20-minute lease for the Zoom-to-S3 upload job. Presence of recording_s3_url is what stops further uploads.', null=True),
        ),
    ]
