# Generated by Django 6.0.2 on 2026-09-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_recording_zoom_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transcript_fetch_attempts',
            field=models.PositiveIntegerField(db_default=0, default=0, editable=False, help_text='Failed transcript-fetch attempts for this event. Used to stop retrying when Zoom has no transcript for the meeting.'),
        ),
        migrations.AddField(
            model_name='event',
            name='transcript_unavailable_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set when Zoom has no transcript for this meeting after the retries are exhausted. Cleared if a transcript shows up later.', null=True),
        ),
    ]
