# Generated by Django 6.0.2 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_event_transcript_fetch_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transcript_s3_url',
            field=models.URLField(
                blank=True,
                db_default='',
                default='',
                editable=False,
                help_text='Private S3 object URL for the archived raw VTT transcript.',
                max_length=500,
            ),
        ),
    ]
