# Generated by Django 6.0.2 on 2026-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_event_transcript_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public listing'), ('hidden', 'Hidden series')], default='public', help_text="Issue #1660: 'hidden' removes every occurrence in this series from every discovery surface (/events, the calendar, the ICS feed, related-content rails, homepage/dashboard feed candidates) for everyone, including staff. This is separate from 'is_active', which only 404s the public series page. The series/event/recap pages stay reachable to staff and to members entitled through a linked Cohort or Sprint.", max_length=10),
        ),
    ]
