# Generated by Django 6.0.2 on 2026-06-23 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Referenced by the markdown shortcode, e.g. 'v0-claim'.", unique=True)),
                ('event_name', models.CharField(help_text="The name passed to emit_event when claimed (e.g. 'v0_workshop').", max_length=100)),
                ('min_level', models.IntegerField(default=5, help_text='Minimum access level required to claim (server-enforced).')),
                ('claim_label', models.CharField(default='Claim', help_text='Button label shown in the claimable state.', max_length=120)),
                ('claim_body', models.TextField(blank=True, default='', help_text='Supporting copy shown in the claimable state.')),
                ('signin_cta', models.CharField(default='Sign in to claim', help_text='CTA label shown to anonymous visitors.', max_length=120)),
                ('claimed_label', models.CharField(default='Claimed', help_text='Label shown once the user has claimed.', max_length=120)),
                ('exhausted_label', models.CharField(default='No longer available', help_text='Label for the exhausted state (reserved for Phase 2).', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event widget',
                'verbose_name_plural': 'Event widgets',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TriggerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='custom', help_text="The event type this subscription listens for (e.g. 'custom').", max_length=100)),
                ('property_filter', models.JSONField(blank=True, default=dict, help_text="Exact-match map. ALL keys must equal the emitted event's properties for this subscription to fire. Empty {} matches every event of this type.")),
                ('target_url', models.URLField(help_text='The external handler (e.g. a Lambda Function URL).', max_length=500)),
                ('secret', models.CharField(help_text='HMAC signing secret shared with the handler. Write-only.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', help_text='Operator note describing this subscription.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trigger subscription',
                'verbose_name_plural': 'Trigger subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('envelope_id', models.CharField(help_text="The 'evt_<uuid>' id put on the wire.", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who triggered the event (null for system emits).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_emissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event emission',
                'verbose_name_plural': 'Event emissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('request_body', models.TextField(blank=True, default='', help_text='The signed JSON envelope sent to the handler.')),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('attempt', models.IntegerField(default=1)),
                ('succeeded', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='triggers.eventemission')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='triggers.triggersubscription')),
            ],
            options={
                'verbose_name': 'Webhook delivery',
                'verbose_name_plural': 'Webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventemission',
            constraint=models.UniqueConstraint(fields=('user', 'event_name'), name='uniq_emission_user_event'),
        ),
    ]
