"""Host calendar-invite sends (issue #861).

A host should receive their OWN copy of the event in their calendar,
Luma-style, the moment the event is scheduled — and an updated copy when
it is rescheduled. Unlike the attendee invite, the host copy carries
host-only management links (edit, manage/notify registrations, create/
join Zoom, the Studio event page) and deliberately does NOT present the
public attendee join flow as the primary call to action.

The ``.ics`` is generated by the existing ``generate_ics(event)`` so the
host's calendar entry shares the SAME per-event UID and SEQUENCE as the
attendee invites: a host who also (accidentally) registers sees one
de-duped entry, and a reschedule UPDATEs that entry rather than
duplicating it. No second iCalendar generator is introduced.

Two entry points, both best-effort (the send MUST NOT break the Studio
save/edit):

- ``maybe_send_initial_host_invite(event)`` — called after an event is
  created/edited in Studio. Sends once per event for the initial
  schedule, guarded by an ``EmailLog`` row so re-saving does not re-send.
  Drafts never trigger an invite.
- ``send_host_reschedule_invite(event)`` — called from the reschedule
  flow after ``ics_sequence`` is bumped. Always sends a fresh
  ``METHOD:REQUEST`` invite with the higher SEQUENCE so the host's
  calendar entry moves.
"""

import logging
from types import SimpleNamespace

from django.contrib.auth import get_user_model
from django.template.loader import render_to_string

from accounts.services.timezones import (
    build_timezone_account_url,
    build_timezone_email_line,
    format_user_datetime,
)
from email_app.services.email_service import EmailService
from events.services.calendar_invite import generate_ics
from events.services.registration_email import _send_raw_email
from integrations.config import get_config, site_base_url

logger = logging.getLogger(__name__)

HOST_INVITE_EMAIL_TYPE = 'event_host_invite'


def resolve_host_email(event):
    """Return the address the host invite should go to, or ``''``.

    Prefers the per-event ``host_email`` and falls back to the
    Studio-configurable default mailbox (``EVENTS_HOST_INVITE_EMAIL``).
    Returns an empty string when neither is set — the caller logs and
    skips rather than erroring the save.
    """
    explicit = (getattr(event, 'host_email', '') or '').strip()
    if explicit:
        return explicit
    return (get_config('EVENTS_HOST_INVITE_EMAIL', '') or '').strip()


def _resolve_recipient(host_email):
    """Return ``(user_or_none, render_target)`` for ``host_email``.

    When the host address belongs to a registered platform user we attach
    the ``EmailLog`` to that user (and render in their timezone). When it
    does not, ``user`` is ``None`` and we render against a lightweight
    stand-in carrying just the address, logging the send via
    ``recipient_email`` instead.
    """
    User = get_user_model()
    user = User.objects.filter(email__iexact=host_email).first()
    if user is not None:
        return user, user
    return None, SimpleNamespace(first_name='', email=host_email)


def _host_links(event):
    """Build the absolute host-only management links for the email body."""
    site_url = site_base_url()
    studio_edit = f'{site_url}/studio/events/{event.pk}/edit'
    return {
        'edit_url': studio_edit,
        # Manage registrations / notify attendees live on the edit page
        # (the Registered attendees panel + the notify action).
        'manage_url': studio_edit,
        'create_zoom_url': f'{site_url}/studio/events/{event.pk}/create-zoom',
        'studio_url': studio_edit,
        'zoom_join_url': getattr(event, 'zoom_join_url', '') or '',
    }


def _send(event, host_email):
    """Render and send the host invite to ``host_email``; write an EmailLog.

    Returns the created ``EmailLog`` instance.
    """
    user, render_target = _resolve_recipient(host_email)

    links = _host_links(event)
    email_service = EmailService()
    subject, body_html = email_service._render_template(
        HOST_INVITE_EMAIL_TYPE,
        render_target,
        {
            'event_title': event.title,
            'event_datetime': format_user_datetime(
                event.start_datetime, user,
            ),
            'timezone_help': build_timezone_email_line(
                user, build_timezone_account_url(site_base_url()),
            ),
            **links,
        },
    )
    full_html = render_to_string('email_app/base_email.html', {
        'subject': subject,
        'body_html': body_html,
    })

    ics_content = generate_ics(event, method='REQUEST')
    ses_message_id = _send_raw_email(
        to_email=host_email,
        subject=subject,
        html_body=full_html,
        ics_content=ics_content,
        method='REQUEST',
    )

    from email_app.models import EmailLog
    email_log = EmailLog.objects.create(
        user=user,
        event=event,
        recipient_email=host_email,
        email_type=HOST_INVITE_EMAIL_TYPE,
        ses_message_id=ses_message_id,
    )
    logger.info(
        'Sent host invite for event "%s" to %s (SES: %s)',
        event.slug, host_email, ses_message_id,
    )
    return email_log


def maybe_send_initial_host_invite(event):
    """Send the one-time initial host invite, best-effort and idempotent.

    No-ops for drafts (status ``draft``) and when the host invite has
    already been sent for this event (``EmailLog`` guard, mirroring the
    imported-welcome flow). A missing host email or an SES failure is
    logged and swallowed so it never breaks the Studio save.

    Returns the created ``EmailLog``, or ``None`` when skipped.
    """
    try:
        if event.status == 'draft':
            return None

        from email_app.models import EmailLog
        already_sent = EmailLog.objects.filter(
            event=event, email_type=HOST_INVITE_EMAIL_TYPE,
        ).exists()
        if already_sent:
            return None

        host_email = resolve_host_email(event)
        if not host_email:
            logger.warning(
                'Skipping host invite for event "%s": no host email '
                'resolved (host_email blank and EVENTS_HOST_INVITE_EMAIL '
                'unset).',
                event.slug,
            )
            return None

        return _send(event, host_email)
    except Exception:
        logger.exception(
            'Failed to send initial host invite for event "%s"',
            getattr(event, 'slug', event.pk),
        )
        return None


def send_host_reschedule_invite(event):
    """Send an updated host invite after a reschedule, best-effort.

    Called from the Studio reschedule flow AFTER ``ics_sequence`` is
    bumped, so the re-issued ``.ics`` carries the higher SEQUENCE and the
    host's calendar entry moves (UID is unchanged) instead of
    duplicating. A missing host email or an SES failure is logged and
    swallowed so it never breaks the Studio save.

    Returns the created ``EmailLog``, or ``None`` when skipped.
    """
    try:
        host_email = resolve_host_email(event)
        if not host_email:
            logger.warning(
                'Skipping host reschedule invite for event "%s": no host '
                'email resolved.',
                event.slug,
            )
            return None
        return _send(event, host_email)
    except Exception:
        logger.exception(
            'Failed to send host reschedule invite for event "%s"',
            getattr(event, 'slug', event.pk),
        )
        return None
