# Generated by Django 6.0.2 on 2026-04-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0014_utmcampaign_utmcampaignlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, help_text='Landing path, no querystring.', max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA-256 of (client_ip + IP_HASH_SALT). Empty if salt not configured.', max_length=64)),
                ('anonymous_id', models.CharField(db_index=True, help_text='UUID4 from the aslab_aid cookie. Stable across visits for the same browser.', max_length=36)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Resolved by matching utm_campaign to UtmCampaign.slug at write time. NULL when no matching campaign exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='integrations.utmcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Visit',
                'verbose_name_plural': 'Campaign Visits',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['campaign', '-ts'], name='analytics_visit_camp_ts_idx'), models.Index(fields=['anonymous_id', '-ts'], name='analytics_visit_anon_ts_idx'), models.Index(fields=['utm_campaign', '-ts'], name='analytics_visit_utmc_ts_idx')],
            },
        ),
    ]
