# Generated by Django 6.0.2 on 2026-04-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tieroverride'),
        ('analytics', '0001_initial'),
        ('integrations', '0014_utmcampaign_utmcampaignlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribution',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attribution', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_touch_utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('first_touch_ts', models.DateTimeField(blank=True, null=True)),
                ('last_touch_utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('last_touch_ts', models.DateTimeField(blank=True, null=True)),
                ('signup_path', models.CharField(choices=[('email_password', 'Email + password'), ('newsletter', 'Newsletter'), ('slack_oauth', 'Slack OAuth'), ('google_oauth', 'Google OAuth'), ('github_oauth', 'GitHub OAuth'), ('stripe_checkout', 'Stripe Checkout'), ('admin_created', 'Admin / createsuperuser'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('anonymous_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_touch_campaign', models.ForeignKey(blank=True, help_text='Resolved by matching first-touch utm_campaign to UtmCampaign.slug at signup. NULL when no matching campaign exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.utmcampaign')),
                ('last_touch_campaign', models.ForeignKey(blank=True, help_text='Resolved by matching last-touch utm_campaign to UtmCampaign.slug at signup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.utmcampaign')),
            ],
            options={
                'verbose_name': 'User Attribution',
                'verbose_name_plural': 'User Attributions',
            },
        ),
    ]
