# Generated by Django 6.0.2 on 2026-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_userattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribution',
            name='first_touch_referrer_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userattribution',
            name='first_touch_referrer_source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('chatgpt', 'ChatGPT'), ('perplexity', 'Perplexity'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('google', 'Google'), ('bing', 'Bing'), ('duckduckgo', 'DuckDuckGo'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('github', 'GitHub'), ('medium', 'Medium'), ('substack', 'Substack'), ('internal', 'Internal (aishippinglabs.com)'), ('other', 'Other'), ('direct', 'Direct (no referrer)')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userattribution',
            name='last_touch_referrer_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userattribution',
            name='last_touch_referrer_source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('chatgpt', 'ChatGPT'), ('perplexity', 'Perplexity'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('google', 'Google'), ('bing', 'Bing'), ('duckduckgo', 'DuckDuckGo'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('github', 'GitHub'), ('medium', 'Medium'), ('substack', 'Substack'), ('internal', 'Internal (aishippinglabs.com)'), ('other', 'Other'), ('direct', 'Direct (no referrer)')], default='', max_length=64),
        ),
    ]
