# Generated by Django 6.0.2 on 2026-06-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_userattribution_referrer_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('signup', 'Signup'), ('course_enroll', 'Enrolled'), ('lesson_open', 'Lesson'), ('event_register', 'Registered'), ('event_join', 'Joined'), ('payment', 'Payment'), ('email_click', 'Email click')], db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the action happened. For backfilled/derived rows this is set to the source timestamp so the timeline is chronologically correct.')),
                ('object_type', models.CharField(blank=True, default='', help_text='Optional content-type label, e.g. course, unit, event, campaign.', max_length=40)),
                ('object_id', models.CharField(blank=True, default='', help_text='Optional identifier (slug or pk) of the related object.', max_length=64)),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable summary rendered in the timeline. Denormalised on write so the timeline survives target deletion.', max_length=255)),
                ('target_url', models.CharField(blank=True, default='', help_text='Optional Studio-side deep link to the related object. Blank when there is no sensible Studio target.', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='analytics_activity_user_ts_idx')],
            },
        ),
    ]
