# Generated by Django 6.0.2 on 2026-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_useractivity_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='event_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('course_enroll', 'Enrolled'), ('lesson_open', 'Lesson'), ('event_register', 'Registered'), ('event_join', 'Joined'), ('payment', 'Payment'), ('email_click', 'Email click'), ('slack_join_click', 'Slack join'), ('resource_view', 'Viewed')], db_index=True, max_length=40),
        ),
    ]
