# Generated by Django 6.0.2 on 2026-05-05 23:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary_current_situation', models.TextField(blank=True, default='')),
                ('summary_goal', models.TextField(blank=True, default='')),
                ('summary_main_gap', models.TextField(blank=True, default='')),
                ('summary_weekly_hours', models.CharField(blank=True, default='', max_length=120)),
                ('summary_why_this_plan', models.TextField(blank=True, default='')),
                ('focus_main', models.TextField(blank=True, default='')),
                ('focus_supporting', models.JSONField(blank=True, default=list)),
                ('accountability', models.TextField(blank=True, default='')),
                ('assigned_persona', models.CharField(blank=True, default='', max_length=120)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_label', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, default='', max_length=600)),
                ('note', models.TextField(blank=True, default='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('start_date', models.DateField()),
                ('duration_weeks', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='plans_sprin_status_7859c5_idx')],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='plans.sprint'),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('theme', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'position', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='plans.week')),
            ],
            options={
                'ordering': ['week', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeekNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='plans.week')),
            ],
            options={
                'ordering': ['week', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('internal', 'Internal (staff only)'), ('external', 'External (shareable with member)')], default='internal', max_length=10)),
                ('kind', models.CharField(choices=[('persona', 'Persona'), ('background', 'Background'), ('intake', 'Intake'), ('meeting', 'Meeting Notes'), ('recommendation', 'Internal Recommendation'), ('action_item', 'Internal Action Item'), ('source', 'Source'), ('general', 'General')], default='general', max_length=20)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_interview_notes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to='plans.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'visibility'], name='plans_inter_member__b1e411_idx'), models.Index(fields=['plan', 'visibility'], name='plans_inter_plan_id_1901eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status'], name='plans_plan_status_bc420d_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['sprint', 'status'], name='plans_plan_sprint__f9b8cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('member', 'sprint'), name='unique_plan_per_member_per_sprint'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('plan', 'week_number'), name='unique_week_number_per_plan'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['week', 'position'], name='plans_check_week_id_a860f6_idx'),
        ),
    ]
