# Generated by Django 6.0.2 on 2026-05-06 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private (only the member and staff)'), ('cohort', 'Cohort (visible to other members of the same sprint)')], default='private', max_length=10),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['sprint', 'visibility'], name='plans_plan_sprint__f4f432_idx'),
        ),
    ]
