# Generated by Django 6.0.2 on 2026-05-06 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='min_tier_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=30, help_text='Minimum tier level required to join this sprint. Default 30 (Premium); staff can lower per-sprint, e.g. 0 for an open pilot or 20 for a Main+ sprint.'),
        ),
        migrations.CreateModel(
            name='SprintEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, help_text='Staff user who enrolled this member, or NULL when the member self-joined.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='plans.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['sprint'], name='plans_sprin_sprint__956d8b_idx'), models.Index(fields=['user'], name='plans_sprin_user_id_88546d_idx')],
                'constraints': [models.UniqueConstraint(fields=('sprint', 'user'), name='unique_sprint_enrollment')],
            },
        ),
    ]
