# Generated by Django 6.0.2 on 2026-05-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_backfill_sprint_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='min_tier_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=20, help_text='Minimum tier level required to join this sprint. Default 20 (Main); staff can lower per-sprint, e.g. 0 for an open pilot, or raise to Premium for high-touch sprints.'),
        ),
    ]
