# Generated by Django 6.0.2 on 2026-05-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_sprint_min_tier_level_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextstep',
            name='assignee_label',
        ),
    ]
