# Generated by Django 6.0.2 on 2026-05-08 00:16
"""Add the ``Plan.comment_content_id`` UUID bridge to comments (issue #499).

Three-step migration so existing rows get UNIQUE UUIDs:

1. Add the column nullable, no unique constraint, no default.
2. Backfill: assign a fresh ``uuid4`` to every existing plan.
3. Tighten: NOT NULL + unique + db_index + default ``uuid.uuid4`` for
   future inserts. ``editable=False`` keeps the field out of any
   ModelForm so a stray ``ModelForm(plan)`` cannot accidentally
   present this UUID for editing.

This UUID is the ONLY bridge from plans to the existing comments
app. The comments app already exposes
``/api/comments/<uuid:content_id>``; we reuse that endpoint with
``content_id = plan.comment_content_id``.
"""

import uuid

from django.db import migrations, models


def backfill_comment_content_ids(apps, schema_editor):
    """Assign a fresh UUID to every existing Plan row."""
    Plan = apps.get_model('plans', 'Plan')
    for plan in Plan.objects.all():
        plan.comment_content_id = uuid.uuid4()
        plan.save(update_fields=['comment_content_id'])


def reverse_backfill_noop(apps, schema_editor):
    """Reverse is a no-op: the column gets dropped in the previous step."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_nextstep_assignee_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='comment_content_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(
            backfill_comment_content_ids,
            reverse_code=reverse_backfill_noop,
        ),
        migrations.AlterField(
            model_name='plan',
            name='comment_content_id',
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
