# Generated by Django 6.0.2 on 2026-05-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_backfill_event_origin'),
        ('plans', '0007_add_comment_content_id_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='event_group',
            field=models.ForeignKey(blank=True, help_text='Optional recurring meeting series whose occurrences are surfaced on the sprint detail page. Deleting the group unlinks the sprint; the sprint itself is preserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprints', to='events.eventgroup'),
        ),
    ]
