# Generated by Django 6.0.2 on 2026-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_rename_sprint_event_group_to_event_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='goal',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
