# Generated by Django 6.0.2 on 2026-05-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_plan_goal'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plan',
            name='plans_plan_status_bc420d_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='plans_plan_sprint__f9b8cf_idx',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='status',
        ),
    ]
