# Generated by Django 6.0.2 on 2026-05-29 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_drop_plan_status'),
        ('questionnaires', '0002_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='assigned_persona_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='questionnaires.persona'),
        ),
    ]
