# Generated by Django 6.0.2 on 2026-05-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_plan_assigned_persona_ref'),
        ('plans', '0013_sprintfeedbackrequest'),
    ]

    operations = [
    ]
