# Generated by Django 6.0.2 on 2026-05-29 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_merge_20260529_1043'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintFeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_json', models.JSONField(help_text='The validated FeedbackSynthesisResult as a dict (themes, what_went_well, what_to_improve, recommendations, next_sprint_signal, response_count).')),
                ('response_count', models.IntegerField(help_text='Number of submitted responses synthesized.')),
                ('model_name', models.CharField(blank=True, default='', help_text='Resolved LLM model used, for provenance.', max_length=200)),
                ('generated_at', models.DateTimeField()),
                ('feedback_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='plans.sprintfeedbackrequest')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
