# Generated by Django 6.0.2 on 2026-06-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_sprintfeedbacksummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NextSprintPlanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_json', models.JSONField(default=dict, help_text='The validated NextSprintDraftResult as a dict (summary_* fields, goal, suggested_next_steps, rationale).')),
                ('update_count', models.IntegerField(default=0, help_text='How many recent #plan-sprints messages informed the draft.')),
                ('model_name', models.CharField(blank=True, default='', help_text='Resolved LLM model used, for provenance.', max_length=200)),
                ('generated_at', models.DateTimeField()),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_sprint_draft', to='plans.plan')),
                ('source_plan', models.ForeignKey(blank=True, help_text='The carry-over / recent-updates source plan, for audit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plans.plan')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
