# Generated by Django 6.0.2 on 2026-06-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_nextsprintplandraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='assigned_persona',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='assigned_persona_ref',
        ),
    ]
