# Generated by Django 6.0.2 on 2026-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_alter_sprint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstep',
            name='kind',
            field=models.CharField(choices=[('pre_sprint', 'Pre-sprint action'), ('next_step', 'Next step')], default='pre_sprint', max_length=20),
        ),
    ]
