# Generated by Django 6.0.2 on 2026-06-18 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0017_emaillog_event_emaillog_recipient_email_and_more'),
        ('notifications', '0007_alter_notification_notification_type'),
        ('plans', '0020_weeknote_singleton'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanReadyEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='sending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_app.emaillog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_ready_email_logs', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ready_email_log', to='plans.plan')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_ready_email_logs', to='plans.sprint')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sprint', 'status'], name='plans_planr_sprint__f576b9_idx'), models.Index(fields=['member', 'status'], name='plans_planr_member__a789cf_idx')],
            },
        ),
    ]
