# Generated by Codex on 2026-06-18

from django.db import migrations, models

PLAN_TITLE_MAX_LENGTH = 280


def _display_name(user):
    first = (getattr(user, 'first_name', '') or '').strip()
    last = (getattr(user, 'last_name', '') or '').strip()
    full = f'{first} {last}'.strip()
    if full:
        return full
    email = getattr(user, 'email', '') or ''
    if '@' in email:
        return email.split('@', 1)[0]
    return email


def _fallback_title(plan):
    for candidate in (plan.title, plan.goal, plan.summary_goal):
        value = (candidate or '').strip()
        if value:
            return value[:PLAN_TITLE_MAX_LENGTH]

    member_label = _display_name(plan.member).strip() or 'Member'
    sprint_name = getattr(plan.sprint, 'name', '') or 'Sprint'
    return f"{member_label}'s {sprint_name} plan"[:PLAN_TITLE_MAX_LENGTH]


def backfill_plan_titles(apps, schema_editor):
    Plan = apps.get_model('plans', 'Plan')

    plans = (
        Plan.objects
        .select_related('member', 'sprint')
        .only(
            'id',
            'title',
            'goal',
            'summary_goal',
            'member__email',
            'member__first_name',
            'member__last_name',
            'sprint__name',
        )
    )
    for plan in plans.iterator():
        title = _fallback_title(plan)
        if plan.title != title:
            Plan.objects.filter(pk=plan.pk).update(title=title)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_planreadyemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Short non-sensitive headline shown on sprint boards.',
                max_length=PLAN_TITLE_MAX_LENGTH,
            ),
        ),
        migrations.RunPython(backfill_plan_titles, noop_reverse),
    ]
