# Generated by Django 6.0.2 on 2026-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
