# Generated by Django 6.0.2 on 2026-07-03 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0023_interviewnote_source_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintAccountabilityPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('random', 'Random')], default='manual', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_accountability_partners', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_accountability_partner_for', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountability_partners', to='plans.sprint')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['sprint', 'member'], name='plans_sprin_sprint__9d9262_idx'), models.Index(fields=['sprint', 'partner'], name='plans_sprin_sprint__3a9607_idx')],
                'constraints': [models.UniqueConstraint(fields=('sprint', 'member', 'partner'), name='unique_sprint_accountability_partner'), models.CheckConstraint(condition=models.Q(('member', models.F('partner')), _negated=True), name='sprint_accountability_no_self_partner')],
            },
        ),
    ]
