# Generated by Django 6.0.2 on 2026-07-03 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0018_emailcampaign_target_event'),
        ('plans', '0024_sprintaccountabilitypartner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintPartnerIntroEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='sending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('partner_snapshot', models.JSONField(blank=True, default=list)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_app.emaillog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_partner_intro_email_logs', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_intro_email_logs', to='plans.sprint')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sprint', 'status'], name='plans_sprin_sprint__81d339_idx'), models.Index(fields=['member', 'status'], name='plans_sprin_member__ea4995_idx')],
                'constraints': [models.UniqueConstraint(fields=('sprint', 'member'), name='unique_sprint_partner_intro_email_recipient')],
            },
        ),
    ]
