# Generated by Django 6.0.2 on 2026-07-10 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0018_emailcampaign_target_event'),
        ('notifications', '0008_alter_notification_notification_type'),
        ('plans', '0025_sprintpartnerintroemaillog'),
        ('questionnaires', '0006_update_onboarding_questionnaire_copy_1099'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintEndDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('email_failed', 'Email failed'), ('skipped', 'Skipped')], db_index=True, default='sent', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_app.emaillog')),
                ('feedback_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionnaires.response')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_end_delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('next_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plans.sprint')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_end_delivery_logs', to='plans.plan')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_end_delivery_logs', to='plans.sprint')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sprint', 'status'], name='plans_sprin_sprint__c1a83b_idx'), models.Index(fields=['member', 'status'], name='plans_sprin_member__977bd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('sprint', 'member'), name='unique_sprint_end_delivery_recipient')],
            },
        ),
    ]
