# Generated by Django 6.0.2 on 2026-07-10 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_slackthread_interview_note'),
        ('email_app', '0018_emailcampaign_target_event'),
        ('notifications', '0008_alter_notification_notification_type'),
        ('plans', '0025_sprintpartnerintroemaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintCadenceDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('week_start', 'Week start'), ('week_note_prompt', 'Week note prompt'), ('slack_progress', 'Slack progress')], db_index=True, max_length=32)),
                ('source_message_ts', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('email_failed', 'Email failed'), ('skipped', 'Skipped')], db_index=True, default='skipped', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_app.emaillog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_cadence_delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_cadence_delivery_logs', to='plans.plan')),
                ('progress_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_delivery_logs', to='crm.ingestedprogressevent')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadence_delivery_logs', to='plans.week')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='plans_sprin_kind_435b90_idx'), models.Index(fields=['plan', 'kind'], name='plans_sprin_plan_id_9a1a36_idx'), models.Index(fields=['member', 'kind'], name='plans_sprin_member__251440_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ['week_start', 'week_note_prompt']), ('week__isnull', False)), fields=('kind', 'plan', 'week'), name='unique_sprint_cadence_plan_week'), models.UniqueConstraint(condition=models.Q(('kind', 'slack_progress'), ('progress_event__isnull', False), models.Q(('source_message_ts', ''), _negated=True)), fields=('kind', 'progress_event', 'source_message_ts'), name='unique_sprint_cadence_slack_progress')],
            },
        ),
    ]
