# Generated by Codex for issue #1205

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0026_sprintcadencedeliverylog'),
        ('questionnaires', '0006_update_onboarding_questionnaire_copy_1099'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSprintPlanDraft',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'result_json',
                    models.JSONField(
                        default=dict,
                        help_text='The validated FirstSprintDraftResult as a dict.',
                    ),
                ),
                (
                    'model_name',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Resolved LLM model used, for provenance.',
                        max_length=200,
                    ),
                ),
                ('generated_at', models.DateTimeField()),
                (
                    'generated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'plan',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='first_sprint_draft',
                        to='plans.plan',
                    ),
                ),
                (
                    'source_response',
                    models.ForeignKey(
                        blank=True,
                        help_text='Submitted onboarding response used as source input.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='questionnaires.response',
                    ),
                ),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
