# Generated by Django 6.0.2 on 2026-07-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0026_sprintcadencedeliverylog'),
        ('plans', '0026_sprintenddeliverylog'),
    ]

    operations = []
