# Generated by Codex for issue #1205

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0027_firstsprintplandraft'),
        ('plans', '0027_merge_sprint_cadence_and_end_delivery'),
    ]

    operations = []
