# Generated by Django 6.0.2 on 2026-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0028_merge_0027_firstsprintplandraft_0027_merge_sprint_cadence_and_end_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='audience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sprint',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sprint',
            name='outcomes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
