# Generated by Django 6.0.2 on 2026-09-09 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0029_sprint_audience_sprint_description_sprint_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointDeletionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_id', models.PositiveBigIntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_deletion_receipts', to='plans.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'checkpoint_id'), name='unique_checkpoint_deletion_per_plan')],
            },
        ),
    ]
