# Generated by Django 6.0.2 on 2026-09-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mail', '0004_emaildelivery_transport_options'),
        ('plans', '0030_checkpointdeletionreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='planreadyemaillog',
            name='email_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cb_mail.emaildelivery'),
        ),
    ]
