# Generated by Django 6.0.2 on 2026-09-16 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_.]+$', 'Enter a slug: letters, digits, dots, dashes or underscores.')])),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='', editable=False)),
                ('related', models.JSONField(blank=True, default=list)),
                ('required_level', models.PositiveIntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
            ],
            options={
                'ordering': ('slug',),
                'indexes': [models.Index(fields=['status'], name='topics_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_content_id__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_content_id__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='topics_topicpage_source_complete')],
            },
        ),
    ]
