# Generated by Django 6.0.2 on 2026-09-08 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiReplyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_identity', models.CharField(max_length=64)),
                ('token_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('token_prefix_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_digest', models.CharField(max_length=64)),
                ('resulting_comment_id_snapshot', models.PositiveBigIntegerField()),
                ('actor_id_snapshot', models.PositiveBigIntegerField()),
                ('actor_email_snapshot', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resulting_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_reply_operations', to='comments.comment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('token_identity', 'idempotency_key'), name='uniq_comment_api_reply_key')],
            },
        ),
    ]
