# Generated by Django 6.0.2 on 2026-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_apireplyoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Set when a staff edit rewrote the body; never cleared.', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when staff hid the comment; null while visible.', null=True),
        ),
    ]
