# Generated by Django 6.0.2 on 2026-06-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Which assistant tool ran (e.g. add_member_note).', max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='The exact reviewed payload that was executed.')),
                ('target_email', models.CharField(blank=True, default='', help_text='Email the action targeted (kept even if user is gone).', max_length=254)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Human-readable result or error detail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Staff member who confirmed and executed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_member', models.ForeignKey(blank=True, help_text='The member the action targeted, when resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='studio_assi_created_ec332c_idx'), models.Index(fields=['tool_name'], name='studio_assi_tool_na_e7e84c_idx')],
            },
        ),
    ]
