# Generated by Django 6.0.2 on 2026-02-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invite', 'Invite'), ('remove', 'Remove'), ('reactivate', 'Reactivate'), ('link', 'Link')], help_text='Type of community action performed.', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred.')),
                ('details', models.TextField(blank=True, default='', help_text='Additional details about the action (e.g. Slack API response, error info).')),
                ('user', models.ForeignKey(help_text='The user this action was performed for.', on_delete=django.db.models.deletion.CASCADE, related_name='community_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Audit Log',
                'verbose_name_plural': 'Community Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
