# Generated by Django 6.0.2 on 2026-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityauditlog',
            name='action',
            field=models.CharField(choices=[('invite', 'Invite'), ('remove', 'Remove'), ('reactivate', 'Reactivate'), ('link', 'Link'), ('check', 'Check')], help_text='Type of community action performed.', max_length=20),
        ),
    ]
