# Generated by Django 6.0.2 on 2026-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_communityauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityauditlog',
            name='action',
            field=models.CharField(choices=[('invite', 'Invite'), ('remove', 'Remove'), ('reactivate', 'Reactivate'), ('link', 'Link'), ('check', 'Check'), ('email_synced_from_stripe', 'Email synced from Stripe'), ('api_unsubscribe', 'API: unsubscribe toggle'), ('api_verify', 'API: email verification'), ('api_tag', 'API: tag add/remove')], help_text='Type of community action performed.', max_length=32),
        ),
    ]
