# Generated by Django 6.0.2 on 2026-06-08 14:02

from django.db import migrations, models

# Seed hosts for the "Request a call" feature (#870). Alexey's Calendly
# link is left blank for staff to fill in Studio (configurable, no
# deploy). Valeria's Google appointment-scheduling link is seeded
# directly. Capacity starts at 0 (no availability) so staff explicitly
# opt a host in before the page advertises them as available.
SEED_HOSTS = [
    {
        'slug': 'alexey',
        'name': 'Alexey Grigorev',
        'role_label': 'Co-founder & ML Engineer',
        'booking_url': '',
        'order': 1,
    },
    {
        'slug': 'valeria',
        'name': 'Valeriia Kuka',
        'role_label': 'Co-founder & Content Strategist',
        'booking_url': 'https://calendar.app.google/Rh5oWPU9ZAuuDLPt9',
        'order': 2,
    },
]


def seed_hosts(apps, schema_editor):
    CallHost = apps.get_model('community', 'CallHost')
    for data in SEED_HOSTS:
        CallHost.objects.update_or_create(slug=data['slug'], defaults=data)


def unseed_hosts(apps, schema_editor):
    CallHost = apps.get_model('community', 'CallHost')
    CallHost.objects.filter(slug__in=[h['slug'] for h in SEED_HOSTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_communityauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Alexey Grigorev".', max_length=120)),
                ('slug', models.SlugField(help_text='Stable key, e.g. "alexey", "valeria".', unique=True)),
                ('role_label', models.CharField(blank=True, help_text='e.g. "Co-founder & ML Engineer".', max_length=160)),
                ('photo_url', models.CharField(blank=True, help_text='Photo URL. Falls back to the static asset for the slug when blank.', max_length=500)),
                ('booking_url', models.URLField(blank=True, help_text="The host's scheduler link (Calendly / Google appointment scheduling).", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Show this host on the request-a-call page.')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='How many people can be taken now. 0 means none.')),
                ('current_load', models.PositiveIntegerField(default=0, help_text='Staff-maintained count of pending/booked calls.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(seed_hosts, unseed_hosts),
    ]
