# Generated by Django 6.0.2 on 2026-06-12 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_communityauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(help_text='Email the invitee booked with (raw, before user matching).', max_length=254)),
                ('invitee_name', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Start time of the booked call (from the Calendly event).', null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=20)),
                ('calendly_event_uri', models.CharField(help_text='Calendly scheduled-event URI. Stable idempotency key so webhook re-deliveries never double-count capacity.', max_length=500, unique=True)),
                ('calendly_invitee_uri', models.CharField(blank=True, default='', help_text='Calendly invitee URI (used to match cancellations).', max_length=500)),
                ('reschedule_url', models.URLField(blank=True, default='', max_length=500)),
                ('cancel_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_calls', to='community.callhost')),
                ('member', models.ForeignKey(blank=True, help_text='The member who booked, matched by invitee email when known.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='community_b_member__acb014_idx'), models.Index(fields=['host', 'status'], name='community_b_host_id_d5ded9_idx')],
            },
        ),
    ]
