# Generated by Django 6.0.2 on 2026-07-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_communityauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityauditlog',
            name='action',
            field=models.CharField(choices=[('invite', 'Invite'), ('remove', 'Remove'), ('reactivate', 'Reactivate'), ('link', 'Link'), ('check', 'Check'), ('email_synced_from_stripe', 'Email synced from Stripe'), ('api_unsubscribe', 'API: unsubscribe toggle'), ('api_verify', 'API: email verification'), ('api_tag', 'API: tag add/remove'), ('api_mark_bounced', 'API: mark bounced'), ('api_tier_override', 'API: tier override grant'), ('email_alias_added', 'API: email alias added'), ('email_alias_removed', 'API: email alias removed'), ('payment_mismatch_recorded', 'Payment mismatch recorded'), ('payment_mismatch_updated', 'Payment mismatch updated'), ('merge_accounts', 'API: account merge'), ('merge_events', 'Studio: duplicate event merge'), ('maven_enrollment_override', 'Maven: cohort enrollment override')], help_text='Type of community action performed.', max_length=32),
        ),
    ]
