# Generated by Django 6.0.2 on 2026-08-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_questionnaire_response_audit_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callhost',
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Call profile',
                'verbose_name_plural': 'Call profiles',
            },
        ),
        migrations.AlterField(
            model_name='bookedcall',
            name='host',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='booked_calls',
                to='community.callhost',
            ),
        ),
        migrations.AlterField(
            model_name='callhost',
            name='booking_url',
            field=models.URLField(
                blank=True,
                help_text="The profile's scheduler link.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name='callhost',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Show on Request a call (requires a booking URL).',
            ),
        ),
        migrations.AlterField(
            model_name='callhost',
            name='photo_url',
            field=models.CharField(
                blank=True,
                help_text='Optional profile photo URL.',
                max_length=500,
            ),
        ),
    ]
