# Generated by Django 6.0.2 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('main', 'Main'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hook', models.TextField(blank=True, default='')),
                ('positioning', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('highlighted', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
