# Generated by Django 6.0.2 on 2026-02-18 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payments', '0003_seed_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified.")),
                ('unsubscribed', models.BooleanField(default=False, help_text='Whether the user has unsubscribed from emails.')),
                ('email_preferences', models.JSONField(blank=True, default=dict, help_text='User email preferences as a JSON object.')),
                ('stripe_customer_id', models.CharField(blank=True, default='', help_text='Stripe customer ID.', max_length=255)),
                ('subscription_id', models.CharField(blank=True, default='', help_text='Stripe/MoR subscription ID.', max_length=255)),
                ('billing_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period. Null for free users.', null=True)),
                ('slack_user_id', models.CharField(blank=True, default='', help_text='Slack user ID for community integration.', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('pending_tier', models.ForeignKey(blank=True, help_text='Tier scheduled after downgrade at billing_period_end.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_users', to='payments.tier')),
                ('tier', models.ForeignKey(blank=True, help_text="Current membership tier. Defaults to 'free' on creation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='payments.tier')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
