# Generated by Django 6.0.2 on 2026-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(blank=True, default='', help_text="User's preferred theme: 'dark', 'light', or '' (follow system).", max_length=10),
        ),
    ]
