# Generated by Django 6.0.2 on 2026-02-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_theme_preference'),
        ('payments', '0004_webhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(help_text='When the override expires (UTC).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set False on expiry or manual revocation.')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who created the override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_overrides', to=settings.AUTH_USER_MODEL)),
                ('original_tier', models.ForeignKey(blank=True, help_text="User's tier when override was created (for audit).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides_from', to='payments.tier')),
                ('override_tier', models.ForeignKey(help_text='The upgraded tier.', on_delete=django.db.models.deletion.PROTECT, related_name='overrides_to', to='payments.tier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tieroverride_user_active_idx')],
            },
        ),
    ]
