# Generated by Django 6.0.2 on 2026-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tieroverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Operator-managed contact tags (Studio-only; staff-only data).'),
        ),
    ]
