# Generated by Django 6.0.2 on 2026-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tieroverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When the user's Slack workspace membership was last verified.", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_member',
            field=models.BooleanField(db_index=True, default=False, help_text="Whether the user's email is verified to be in the Slack workspace."),
        ),
    ]
