# Generated by Django 6.0.2 on 2026-04-29 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_slack_checked_at_user_slack_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='import_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Source-keyed import metadata for audit/debugging, not querying.'),
        ),
        migrations.AddField(
            model_name='user',
            name='import_source',
            field=models.CharField(choices=[('manual', 'Manual / self signup'), ('slack', 'Slack workspace'), ('course_db', 'Course database'), ('stripe', 'Stripe customers')], db_index=True, default='manual', help_text='Earliest non-manual source that imported or reconciled this user.', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='imported_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the import pipeline first created or reconciled this user.', null=True),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('slack', 'Slack workspace'), ('course_db', 'Course database'), ('stripe', 'Stripe customers')], db_index=True, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dry_run', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('users_created', models.PositiveIntegerField(default=0)),
                ('users_updated', models.PositiveIntegerField(default=0)),
                ('users_skipped', models.PositiveIntegerField(default=0)),
                ('emails_queued', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
