# Generated by Django 6.0.2 on 2026-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_import_metadata_user_import_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
