# Generated by Django 6.0.2 on 2026-04-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_importbatch_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone used for signed-in event time display.', max_length=100),
        ),
    ]
