# Generated by Django 6.0.2 on 2026-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, the unverified user is hard-deleted by the daily purge task once this timestamp is in the past.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="When the one-shot 'verify or expire' reminder email was sent. Prevents the daily reminder task from spamming.", null=True),
        ),
    ]
