# Generated by Django 6.0.2 on 2026-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_unverified_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='soft_bounce_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Running count of transient (soft) SES bounces. Reset to 0 once the user is auto-unsubscribed at the configured threshold.'),
        ),
    ]
