# Generated by Django 6.0.2 on 2026-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cleanup_member_plan_editor_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_activated',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the user has taken a platform action (issue #768). Used to gate platform-only UI for newsletter-only subscribers.'),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(choices=[('unknown', 'Unknown (pre-existing row)'), ('newsletter', 'Newsletter subscribe'), ('signup', 'Email + password signup'), ('oauth', 'OAuth signup'), ('imported', 'Bulk import (Stripe / CSV / course DB)'), ('staff_create', 'Staff-created (Studio)')], db_index=True, default='unknown', help_text='How the user row was created (issue #768).', max_length=32),
        ),
    ]
