# Generated by Django 6.0.2 on 2026-05-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_account_activated_user_signup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bounce_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When ``bounce_state`` last flipped to a non-``none`` value. Powers the 24h eager-purge gate for unverified bounced rows.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bounce_state',
            field=models.CharField(choices=[('none', 'No bounce'), ('soft', 'Soft bounce'), ('permanent', 'Permanent bounce')], db_index=True, default='none', help_text='Current SES bounce state for this user.', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='last_bounce_diagnostic',
            field=models.TextField(blank=True, default='', help_text='SMTP diagnostic from the most recent bounce (truncated to 500 chars for operator triage).'),
        ),
    ]
