# Generated by Django 6.0.2 on 2026-06-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_bounce_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Normalized alias email (lower-cased). Unique across the table; must not equal any primary User.email.', max_length=254, unique=True)),
                ('source', models.CharField(choices=[('merge', 'Added by an account merge'), ('manual', 'Operator-added'), ('stripe_relay', 'Billing relay address')], default='manual', help_text='How this alias came to exist.', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Operator context for why this alias exists.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who added the alias (NULL if deleted / system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The canonical account this email routes to.', on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Alias',
                'verbose_name_plural': 'Email Aliases',
                'ordering': ['-created_at'],
            },
        ),
    ]
