# Generated by Django 6.0.2 on 2026-06-03 18:45
"""Backfill: scrub already-merged secondary emails (#845).

Before #845 the account-merge engine deactivated the secondary User but left its
``email`` intact, while also recording that same address as an ``EmailAlias`` of
canonical. That violates the invariant "EmailAlias.email MUST NOT equal any
User.email". This data migration restores the invariant for rows that were
merged before #845 shipped: every deactivated User whose (normalized) email
still equals an existing ``EmailAlias.email`` gets its email scrubbed to the
same ``merged+<pk>@merged.invalid`` placeholder the engine now writes. The alias
row keeps the ORIGINAL email, so login / Stripe resolution still routes to
canonical.

At least one such row exists in prod: the stefano relay merge, whose secondary
``47-gentle.virtual@icloud.com`` is already deactivated + aliased.
"""

from django.db import migrations


def scrub_already_merged(apps, schema_editor):
    # Import lazily so the migration uses the same backfill logic the service
    # exposes (single source of truth), but with the historical model versions.
    from accounts.services.account_merge import (
        backfill_scrub_legacy_merged_emails,
    )

    User = apps.get_model("accounts", "User")
    EmailAlias = apps.get_model("accounts", "EmailAlias")
    backfill_scrub_legacy_merged_emails(User, EmailAlias)


def noop_reverse(apps, schema_editor):
    # Irreversible: the scrubbed placeholder is non-routable and the original
    # address lives on as the alias. There is no safe automatic un-scrub.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailalias'),
    ]

    operations = [
        migrations.RunPython(scrub_already_merged, noop_reverse),
    ]
