# Generated by Django 6.0.2 on 2026-06-03 18:45
"""Backfill: scrub already-merged secondary emails (#845).

Before #845 the account-merge engine deactivated the secondary User but left its
``email`` intact, while also recording that same address as an ``EmailAlias`` of
canonical. That violates the invariant "EmailAlias.email MUST NOT equal any
User.email". This data migration restores the invariant for rows that were
merged before #845 shipped: every deactivated User whose (normalized) email
still equals an existing ``EmailAlias.email`` gets its email scrubbed to the
same ``merged+<pk>@merged.invalid`` placeholder the engine now writes. The alias
row keeps the ORIGINAL email, so login / Stripe resolution still routes to
canonical.

At least one such row exists in prod: the stefano relay merge, whose secondary
``47-gentle.virtual@icloud.com`` is already deactivated + aliased.
"""

from django.db import migrations


def scrub_already_merged(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    EmailAlias = apps.get_model("accounts", "EmailAlias")
    scrubbed_email_suffix = "@merged.invalid"
    alias_emails = set(EmailAlias.objects.values_list("email", flat=True))
    if not alias_emails:
        return

    for user in User.objects.filter(is_active=False):
        current = (user.email or "").strip().lower()
        if not current or current.endswith(scrubbed_email_suffix):
            continue
        if current in alias_emails:
            user.email = f"merged+{user.pk}{scrubbed_email_suffix}"
            user.save(update_fields=["email"])


def noop_reverse(apps, schema_editor):
    # Irreversible: the scrubbed placeholder is non-routable and the original
    # address lives on as the alias. There is no safe automatic un-scrub.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailalias'),
    ]

    operations = [
        migrations.RunPython(scrub_already_merged, noop_reverse),
    ]
