# Generated by Django 6.0.2 on 2026-07-02 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_backfill_scrub_merged_secondary_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(max_length=128)),
                ('lookup_prefix', models.CharField(db_index=True, max_length=32)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='accounts_me_user_id_435d1d_idx'), models.Index(fields=['lookup_prefix', 'revoked_at'], name='accounts_me_lookup__cc9407_idx')],
            },
        ),
    ]
