# Generated by Django 6.0.2 on 2026-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_memberapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_dismissals',
            field=models.JSONField(blank=True, default=list, help_text='Dismissed dashboard card keys (per-user member state).'),
        ),
    ]
