# Generated by Django 6.0.2 on 2026-07-11 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_hash_operator_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalias',
            name='source',
            field=models.CharField(choices=[('merge', 'Added by an account merge'), ('manual', 'Operator-added'), ('stripe_relay', 'Billing relay address'), ('account_change', 'Former login email after account change')], default='manual', help_text='How this alias came to exist.', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_email', models.EmailField(max_length=254)),
                ('new_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('confirmed_at__isnull', True), ('invalidated_at__isnull', True)), fields=('user',), name='unique_active_email_change_request_per_user')],
            },
        ),
    ]
