# Generated by Django 6.0.2 on 2026-07-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_privacyrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieroverride',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable grant source. Maven uses maven:<occurrence identity> so its entitlement can coexist with staff and billing grants.', max_length=80),
        ),
    ]
