# Generated by Django 6.0.2 on 2026-08-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_signup_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyrequestlog',
            name='request_type',
            field=models.CharField(choices=[('export', 'Export'), ('delete', 'Delete'), ('deletion_request', 'Deletion request')], max_length=16),
        ),
        migrations.AlterField(
            model_name='privacyrequestlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('blocked', 'Blocked'), ('pending_delivery', 'Pending delivery'), ('requested', 'Requested'), ('delivery_failed', 'Delivery failed')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='privacyrequestlog',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'deletion_request'), ('status__in', ['pending_delivery', 'requested']), ('old_user_id__isnull', False)), fields=('old_user_id',), name='unique_active_deletion_request'),
        ),
    ]
