# Generated by Django 6.0.2 on 2026-09-04 02:09

from django.db import migrations, models


def add_account_id_column(apps, schema_editor):
    AccountSession = apps.get_model("accounts", "AccountSession")
    field = AccountSession._meta.get_field("account_id")
    schema_editor.add_field(AccountSession, field)


def remove_account_id_column(apps, schema_editor):
    AccountSession = apps.get_model("accounts", "AccountSession")
    field = AccountSession._meta.get_field("account_id")
    schema_editor.remove_field(AccountSession, field)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_deletion_request_lifecycle"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSession",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                (
                    "expire_date",
                    models.DateTimeField(db_index=True, verbose_name="expire date"),
                ),
                (
                    "account_id",
                    models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "db_table": "django_session",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.RunPython(add_account_id_column, remove_account_id_column),
    ]
