# Generated by Django 6.0.2 on 2026-09-08 18:53

import re

from django.db import migrations, models

BACKFILL_CHUNK_SIZE = 500


def _normalize_tag(tag):
    if not tag or not isinstance(tag, str):
        return ""
    tag = tag.strip().lower().replace(" ", "-").replace("_", "-")
    tag = re.sub(r"[^a-z0-9:-]", "", tag)
    tag = re.sub(r"-{2,}", "-", tag)
    return tag.strip("-")


def _normalize_tags(tags):
    if not isinstance(tags, list):
        return []
    normalized = []
    seen = set()
    for raw in tags:
        slug = _normalize_tag(raw)
        if slug and slug not in seen:
            seen.add(slug)
            normalized.append(slug)
    return normalized


def backfill_contact_tags(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    ContactTag = apps.get_model("accounts", "ContactTag")
    through = User.contact_tags.through
    alias = schema_editor.connection.alias
    last_pk = 0

    while True:
        users = list(
            User.objects.using(alias)
            .filter(pk__gt=last_pk)
            .only("pk", "tags")
            .order_by("pk")[:BACKFILL_CHUNK_SIZE]
        )
        if not users:
            break
        last_pk = users[-1].pk
        normalized_by_user = {}
        all_slugs = set()
        changed = []
        for user in users:
            normalized = _normalize_tags(user.tags)
            normalized_by_user[user.pk] = normalized
            all_slugs.update(normalized)
            if user.tags != normalized:
                user.tags = normalized
                changed.append(user)

        if changed:
            User.objects.using(alias).bulk_update(
                changed,
                ["tags"],
                batch_size=BACKFILL_CHUNK_SIZE,
            )
        ContactTag.objects.using(alias).bulk_create(
            [ContactTag(slug=slug) for slug in all_slugs],
            ignore_conflicts=True,
            batch_size=BACKFILL_CHUNK_SIZE,
        )
        tag_ids = dict(
            ContactTag.objects.using(alias)
            .filter(slug__in=all_slugs)
            .values_list("slug", "pk")
        )
        user_ids = list(normalized_by_user)
        through.objects.using(alias).filter(user_id__in=user_ids).delete()
        through.objects.using(alias).bulk_create(
            [
                through(user_id=user_id, contacttag_id=tag_ids[slug])
                for user_id, slugs in normalized_by_user.items()
                for slug in slugs
            ],
            ignore_conflicts=True,
            batch_size=BACKFILL_CHUNK_SIZE,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_accountsession_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='contact_tags',
            field=models.ManyToManyField(blank=True, help_text='Indexed membership relation mirroring the tags JSON payload.', related_name='users', to='accounts.contacttag'),
        ),
        migrations.RunPython(backfill_contact_tags, migrations.RunPython.noop),
    ]
