# Generated by Django 6.0.2 on 2026-09-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_contact_tags_relation'),
        ('email_app', '0024_emaillog_ses_msgid_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyCompletionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('outcome_unknown', 'Outcome unknown')], default='pending', max_length=24)),
                ('recipient_ciphertext', models.TextField()),
                ('normalized_email_hash', models.CharField(db_index=True, max_length=64)),
                ('email_domain', models.CharField(blank=True, default='', max_length=255)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('transport_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='privacyrequestlog',
            name='error_code',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='privacyrequestlog',
            name='operator_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='privacyrequestlog',
            name='originating_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_audits', to='accounts.privacyrequestlog'),
        ),
        migrations.AddField(
            model_name='privacyrequestlog',
            name='workflow_version',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='privacyrequestlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('blocked', 'Blocked'), ('pending_delivery', 'Pending delivery'), ('requested', 'Requested'), ('delivery_failed', 'Delivery failed'), ('failed', 'Failed')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='privacyrequestlog',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'delete'), ('status', 'completed'), ('originating_request__isnull', False)), fields=('originating_request',), name='unique_completed_delete_per_request'),
        ),
        migrations.AddField(
            model_name='privacycompletiondelivery',
            name='email_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_completion_deliveries', to='email_app.emaillog'),
        ),
        migrations.AddField(
            model_name='privacycompletiondelivery',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_delivery', to='accounts.privacyrequestlog'),
        ),
        migrations.AddIndex(
            model_name='privacycompletiondelivery',
            index=models.Index(fields=['status', '-created_at'], name='accounts_pr_status_602ff3_idx'),
        ),
    ]
