# Generated by Django 6.0.2 on 2026-10-01 06:03

import django.db.models.functions.text
from django.db import migrations, models

INDEX_NAME = "accounts_user_email_upper"
TABLE_NAME = "accounts_user"


def create_email_upper_index(apps, schema_editor):
    concurrently = " CONCURRENTLY"
    if schema_editor.connection.vendor != "postgresql":
        concurrently = ""
    schema_editor.execute(
        f'CREATE INDEX{concurrently} IF NOT EXISTS "{INDEX_NAME}" '
        f'ON "{TABLE_NAME}" (UPPER("email"))',
    )


def drop_email_upper_index(apps, schema_editor):
    concurrently = " CONCURRENTLY"
    if schema_editor.connection.vendor != "postgresql":
        concurrently = ""
    schema_editor.execute(f'DROP INDEX{concurrently} IF EXISTS "{INDEX_NAME}"')


class Migration(migrations.Migration):
    # PostgreSQL forbids CREATE/DROP INDEX CONCURRENTLY in a transaction.
    # SQLite uses the same portable expression-index SQL without CONCURRENTLY.
    atomic = False

    dependencies = [
        ('accounts', '0033_move_tieroverride_to_payments'),
        ('accounts_ext', '0002_backfill_member_extra'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payments', '0021_tieroverride'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_email_upper_index,
                    drop_email_upper_index,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="user",
                    index=models.Index(
                        django.db.models.functions.text.Upper("email"),
                        name=INDEX_NAME,
                    ),
                ),
            ],
        ),
    ]
