"""``python manage.py generate_openapi`` -- regenerate ``_docs/openapi.json``.

Two modes:

- Default: build the spec from ``api/urls.py`` and write to
  ``_docs/openapi.json``. Use ``sort_keys=True`` and a trailing
  newline so diffs are stable across machines.
- ``--check``: build the spec but do NOT write. If the generated bytes
  differ from the committed file, print a unified diff and exit 1.
  This is what CI runs to detect drift between the decorators and
  the committed spec.

No other flags. The output path is fixed (``_docs/openapi.json``)
because the only reason to support an output flag is to put the file
somewhere else, and there is no other right place to put it.
"""

import difflib
import json
import sys
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from api.openapi.builder import build_spec

DEFAULT_OUTPUT_PATH = Path("_docs") / "openapi.json"


class Command(BaseCommand):
    help = "Generate the OpenAPI 3.1 document for the operator API."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help=(
                "Do not write the file. Exit 0 if the committed spec "
                "is up to date, exit 1 with a unified diff if it has "
                "drifted from the decorators."
            ),
        )

    def handle(self, *args, **options):
        # Import locally so this command pays the URL-resolver cost
        # only when invoked, not at app-startup time.
        from api.urls import urlpatterns

        document = build_spec(urlpatterns)
        generated_bytes = self._serialize(document)

        output_path = Path(settings.BASE_DIR) / DEFAULT_OUTPUT_PATH

        if options["check"]:
            self._check_against_committed(output_path, generated_bytes)
            return

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_bytes(generated_bytes)
        self.stdout.write(
            self.style.SUCCESS(
                f"Wrote OpenAPI spec to {output_path} "
                f"({len(document.get('paths', {}))} paths)."
            ),
        )

    @staticmethod
    def _serialize(document):
        """Serialize the document to bytes with stable formatting.

        ``sort_keys=True`` plus a trailing newline keep the diff
        deterministic across Python builds and editors.
        """
        text = json.dumps(document, indent=2, sort_keys=True)
        if not text.endswith("\n"):
            text += "\n"
        return text.encode("utf-8")

    def _check_against_committed(self, path, generated_bytes):
        """Compare committed file to generated bytes; exit non-zero on drift."""
        if not path.exists():
            self.stderr.write(
                f"OpenAPI spec missing at {path}. Run "
                "``uv run python manage.py generate_openapi`` and commit.",
            )
            sys.exit(1)

        committed_bytes = path.read_bytes()
        if committed_bytes == generated_bytes:
            self.stdout.write(self.style.SUCCESS("OpenAPI spec is up to date."))
            return

        diff_lines = list(difflib.unified_diff(
            committed_bytes.decode("utf-8").splitlines(keepends=True),
            generated_bytes.decode("utf-8").splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (regenerated)",
        ))
        # Concatenate the header + diff into a single ``self.stderr.write``
        # call so the message is captured by ``call_command(..., stderr=...)``
        # in tests AND the diff lines stream verbatim (no ANSI styling per
        # line, because the BaseCommand styler only styles the outermost
        # write call). Falling through to ``sys.stderr`` would bypass the
        # test capture entirely.
        header = (
            f"OpenAPI spec drift detected at {path}. "
            "Run ``uv run python manage.py generate_openapi`` and commit "
            "the result.\n\nDiff:\n"
        )
        self.stderr.write(header + "".join(diff_lines))
        sys.exit(1)
