# Generated by Django 6.0.2 on 2026-05-29 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('archetype', models.CharField(help_text='Short label shown next to the name everywhere in Studio, e.g. "The Engineer transitioning to AI". Required.', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_questionnaire', models.ForeignKey(blank=True, help_text='Optional default onboarding questionnaire for this persona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
