# Generated by Django 6.0.2 on 2026-05-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_seed_personas_and_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('persona_signal', models.CharField(blank=True, default='', max_length=20)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation', to='questionnaires.response')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
