# Generated by Django 6.0.2 on 2026-07-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_onboardingconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='allows_free_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsequestionoption',
            name='allows_free_text',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnswerOptionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_texts', to='questionnaires.answer')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_texts', to='questionnaires.responsequestionoption')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('answer', 'selected_option'), name='unique_text_per_answer_option')],
            },
        ),
    ]
