# Generated by Django 6.0.2 on 2026-07-17 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Coalesce


def grandfather_submitted_responses(apps, schema_editor):
    Response = apps.get_model('questionnaires', 'Response')
    Response.objects.filter(status='submitted').update(
        reviewed_at=Coalesce(
            F('submitted_at'), F('updated_at'), F('created_at'),
        ),
        reviewed_by=None,
    )


def noop_reverse(apps, schema_editor):
    # Dropping the review fields removes the grandfathered state naturally.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_onboarding_turn_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questionnaire_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            grandfather_submitted_responses,
            noop_reverse,
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['status', 'reviewed_at', '-submitted_at'], name='response_review_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'submitted'), models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), _connector='OR'), name='response_draft_review_fields_null'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), ('reviewed_at__isnull', False), _connector='OR'), name='response_reviewer_requires_timestamp'),
        ),
    ]
