"""Studio views for manually provisioning a user (issue #234).

Operators occasionally need to onboard someone (speakers, partners, comp
accounts, support cases, fellow operators) without going through the public
signup flow. Today the only path is Django admin or a shell, which is
awkward and not delegable.

This module exposes a "New user" form at ``/studio/users/new/`` that:

- creates a ``User`` immediately on the free tier with a verified email and a
  random password generated by ``secrets.token_urlsafe``
- optionally promotes the new account to admin (``is_staff`` AND
  ``is_superuser``) when "Make admin" is checked -- admins skip tier gates so
  no tier is assigned in that case
- stashes the generated password in the session, redirects to a confirmation
  page that renders it exactly once with a Copy button, and then drops it so
  the secret is unrecoverable from the UI (mirrors the
  ``content-sources/created/`` pattern from issue #213)

The view is gated on ``is_superuser`` rather than ``is_staff`` because it can
mint other superusers; staff alone is intentionally not enough.
"""

import secrets

from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render

from studio.decorators import superuser_required

User = get_user_model()

# Generated password length, in bytes of entropy fed to ``token_urlsafe``.
# 16 bytes -> ~22-character base64 token, safely above the 16-character floor
# in the acceptance criteria.
PASSWORD_TOKEN_BYTES = 16

# Session key holding the one-shot stash of the generated password and the
# new user's identity. The confirmation view pops this and never writes it
# back, so refreshing or revisiting the page leaves nothing behind.
SESSION_KEY = 'studio_user_create_result'


def _render_form(request, *, email='', first_name='', last_name='',
                 make_admin=False, error='', status=200):
    context = {
        'email': email,
        'first_name': first_name,
        'last_name': last_name,
        'make_admin': make_admin,
        'error': error,
    }
    return render(request, 'studio/users/create.html', context, status=status)


@superuser_required
def user_create(request):
    """Show / handle the "New user" form.

    GET renders an empty form. POST validates, creates the user, stashes the
    password in the session, and redirects to the one-time confirmation page.
    """
    if request.method != 'POST':
        return _render_form(request)

    email = (request.POST.get('email') or '').strip()
    first_name = (request.POST.get('first_name') or '').strip()
    last_name = (request.POST.get('last_name') or '').strip()
    make_admin = request.POST.get('make_admin') == 'on'

    if not email:
        return _render_form(
            request,
            email=email,
            first_name=first_name,
            last_name=last_name,
            make_admin=make_admin,
            error='Email is required.',
            status=400,
        )

    normalized_email = User.objects.normalize_email(email)
    if User.objects.filter(email__iexact=normalized_email).exists():
        return _render_form(
            request,
            email=email,
            first_name=first_name,
            last_name=last_name,
            make_admin=make_admin,
            error=(
                f'A user with email "{normalized_email}" already exists. '
                'Pick a different email or send a password reset to the '
                'existing account.'
            ),
            status=400,
        )

    password = secrets.token_urlsafe(PASSWORD_TOKEN_BYTES)

    user = User(
        email=normalized_email,
        first_name=first_name,
        last_name=last_name,
        is_active=True,
        email_verified=True,
    )
    if make_admin:
        # Admins bypass tier gates everywhere they appear, so the tier value
        # on the row is moot. We still let the default-free-tier branch in
        # User.save() run -- keeping ``tier`` non-null preserves row
        # invariants the rest of the codebase relies on (e.g. the tier
        # override page reads ``user.tier`` directly).
        user.is_staff = True
        user.is_superuser = True
    user.set_password(password)
    user.save()

    request.session[SESSION_KEY] = {
        'user_id': user.pk,
        'email': user.email,
        'password': password,
        'is_admin': bool(user.is_staff or user.is_superuser),
    }
    return redirect('studio_user_create_done')


@superuser_required
def user_create_done(request):
    """Render the generated password exactly once, then drop the stash.

    Reads (and pops) the session stash written by ``user_create``. If the
    operator reloads or navigates back to this URL the stash is gone and they
    are redirected to the form with a hint.
    """
    stash = request.session.pop(SESSION_KEY, None)
    if not stash:
        return _render_form(
            request,
            error=(
                'The generated password is only displayed once, immediately '
                'after creating a user. Use "Send password reset" or create '
                'a new account if the operator missed it.'
            ),
            status=200,
        )

    context = {
        'user_id': stash.get('user_id'),
        'email': stash.get('email', ''),
        'password': stash.get('password', ''),
        'is_admin': bool(stash.get('is_admin')),
    }
    return render(request, 'studio/users/created.html', context)
