"""Studio views for user management.

Two flows live here:

1. Listing / CSV export at ``/studio/users/`` (issue #271). The page now
   filters primarily by effective membership tier: All, Paid, Main+, and
   Premium, with a separate Subscribers chip for newsletter membership.
   Tier overrides are reflected in both filtering and display so a user with
   a temporary upgrade appears under the upgraded tier instead of their base
   subscription row.

2. Manual user provisioning (issue #234). Operators occasionally need to
   onboard someone (speakers, partners, comp accounts, support cases, fellow
   operators) without going through the public signup flow. ``/studio/users/new/``
   creates a ``User`` immediately on the free tier with a verified email and a
   random password generated by ``secrets.token_urlsafe``; the
   ``/studio/users/created/`` confirmation page renders the password exactly
   once and then drops it from the session.

The list/export views require staff (matching the old subscribers page); the
provisioning views require ``is_superuser`` because they can mint other
superusers.
"""

import csv
import datetime
import secrets

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from accounts.models import TierOverride
from accounts.utils.tags import (
    add_tag as _add_tag_to_user,
)
from accounts.utils.tags import (
    normalize_tag,
    normalize_tags,
)
from accounts.utils.tags import (
    remove_tag as _remove_tag_from_user,
)
from studio.decorators import staff_required, superuser_required

User = get_user_model()


# Filter chip values accepted on the list view and CSV export. Anything else
# falls back to "all" so the page lands on the broadest operator view.
FILTER_ALL = 'all'
FILTER_PAID = 'paid'
FILTER_MAIN_PLUS = 'main_plus'
FILTER_PREMIUM = 'premium'
FILTER_SUBSCRIBERS = 'subscribers'
VALID_FILTERS = {
    FILTER_ALL,
    FILTER_PAID,
    FILTER_MAIN_PLUS,
    FILTER_PREMIUM,
    FILTER_SUBSCRIBERS,
}
DEFAULT_FILTER = FILTER_ALL

# Slack-membership filter (issue #358). Tri-state: any/yes/no.
SLACK_FILTER_ANY = 'any'
SLACK_FILTER_YES = 'yes'
SLACK_FILTER_NO = 'no'
VALID_SLACK_FILTERS = {SLACK_FILTER_ANY, SLACK_FILTER_YES, SLACK_FILTER_NO}
DEFAULT_SLACK_FILTER = SLACK_FILTER_ANY


def _normalize_filter(value):
    """Map the raw ``filter`` query param to one of ``VALID_FILTERS``.

    Empty / unknown values land on the default (all) so the page always opens
    on the broadest operator view unless a specific chip is requested.
    """
    if value in VALID_FILTERS:
        return value
    return DEFAULT_FILTER


def _normalize_slack_filter(value):
    """Map the raw ``slack`` query param to one of ``VALID_SLACK_FILTERS``."""
    if value in VALID_SLACK_FILTERS:
        return value
    return DEFAULT_SLACK_FILTER


def _slack_status(user):
    """Return a tri-state Slack membership label for the listing.

    - "Member" — verified to be in the Slack workspace.
    - "Not in Slack" — verified to be absent.
    - "Never checked" — never probed (slack_checked_at IS NULL).
    """
    if user.slack_checked_at is None:
        return 'Never checked'
    return 'Member' if user.slack_member else 'Not in Slack'


def _base_tier_level(user):
    """Return the user's stored subscription level, treating null as free."""
    if user.tier_id is None:
        return 0
    return user.tier.level


def _active_override_map(users):
    """Return the active non-expired override for each listed user, if any."""
    user_ids = [user.pk for user in users]
    if not user_ids:
        return {}

    overrides = (
        TierOverride.objects
        .filter(
            user_id__in=user_ids,
            is_active=True,
            expires_at__gt=timezone.now(),
        )
        .select_related('override_tier')
        .order_by('user_id', '-created_at')
    )

    override_map = {}
    for override in overrides:
        override_map.setdefault(override.user_id, override)
    return override_map


def _effective_tier_level(user, override=None):
    """Return the effective level used for Studio filtering/display."""
    base_level = _base_tier_level(user)
    if override is None:
        return base_level
    return max(base_level, override.override_tier.level)


def _effective_tier_name(user, override=None):
    """Return a human-readable tier label, including active overrides."""
    base_name = user.tier.name if user.tier_id else 'Free'
    if override is None:
        return base_name

    base_level = _base_tier_level(user)
    override_level = override.override_tier.level
    if override_level <= base_level:
        return base_name
    return f'{override.override_tier.name} (override)'


def _matches_filter(user, active_filter, override=None):
    """Check whether a user belongs in the active Studio chip."""
    if active_filter == FILTER_SUBSCRIBERS:
        return not user.unsubscribed

    effective_level = _effective_tier_level(user, override)
    if active_filter == FILTER_PAID:
        return effective_level > 0
    if active_filter == FILTER_MAIN_PLUS:
        return effective_level >= 20
    if active_filter == FILTER_PREMIUM:
        return effective_level >= 30
    return True


def _matches_slack_filter(user, slack_filter):
    """Apply the Slack-membership filter on top of the tier filter."""
    if slack_filter == SLACK_FILTER_YES:
        return bool(user.slack_member)
    if slack_filter == SLACK_FILTER_NO:
        return not user.slack_member
    return True


def _build_user_listing(active_filter, search, tag_filter='', slack_filter=DEFAULT_SLACK_FILTER):
    """Build filtered rows plus aggregate counts for the users page/export.

    ``tag_filter`` is the raw ``?tag=`` query value; we normalize it
    server-side so ``?tag=Early%20Adopter`` matches ``early-adopter``. An
    empty / whitespace tag filter is treated as "no tag filter".

    ``slack_filter`` is the tri-state Slack-membership filter (issue
    #358). It ANDs with the tier and tag filters.
    """
    all_users = list(User.objects.select_related('tier').all())
    override_map = _active_override_map(all_users)
    search_lower = search.lower()
    normalized_tag = normalize_tag(tag_filter) if tag_filter else ''

    user_rows = []
    for user in all_users:
        if search and search_lower not in user.email.lower():
            continue

        override = override_map.get(user.pk)
        if not _matches_filter(user, active_filter, override):
            continue

        if normalized_tag and normalized_tag not in (user.tags or []):
            continue

        if not _matches_slack_filter(user, slack_filter):
            continue

        user_rows.append({
            'pk': user.pk,
            'email': user.email,
            'date_joined': user.date_joined,
            'last_login': user.last_login,
            'is_subscribed': not user.unsubscribed,
            'unsubscribed': user.unsubscribed,
            'email_verified': user.email_verified,
            'tier_name': _effective_tier_name(user, override),
            'status': _user_status(user),
            'tags': list(user.tags or []),
            'slack_status': _slack_status(user),
            'slack_member': bool(user.slack_member),
            'slack_checked_at': user.slack_checked_at,
        })

    counts = {
        'total_users': len(all_users),
        'paid_count': sum(
            1
            for user in all_users
            if _effective_tier_level(user, override_map.get(user.pk)) > 0
        ),
        'main_plus_count': sum(
            1
            for user in all_users
            if _effective_tier_level(user, override_map.get(user.pk)) >= 20
        ),
        'premium_count': sum(
            1
            for user in all_users
            if _effective_tier_level(user, override_map.get(user.pk)) >= 30
        ),
        'subscriber_count': sum(
            1 for user in all_users if not user.unsubscribed
        ),
        'slack_member_count': sum(
            1 for user in all_users if user.slack_member
        ),
    }

    return user_rows, counts


def _user_status(user):
    """Compact human-readable status: Staff / Inactive / Active."""
    if not user.is_active:
        return 'Inactive'
    if user.is_staff:
        return 'Staff'
    return 'Active'


@staff_required
def user_list(request):
    """List platform Users with tier and subscriber filter chips."""
    active_filter = _normalize_filter(request.GET.get('filter', ''))
    slack_filter = _normalize_slack_filter(request.GET.get('slack', ''))
    search = request.GET.get('q', '')
    raw_tag = request.GET.get('tag', '')
    active_tag = normalize_tag(raw_tag) if raw_tag else ''

    user_rows, counts = _build_user_listing(
        active_filter, search, tag_filter=raw_tag, slack_filter=slack_filter,
    )

    return render(request, 'studio/users/list.html', {
        'user_rows': user_rows,
        'active_filter': active_filter,
        'slack_filter': slack_filter,
        'search': search,
        'active_tag': active_tag,
        'total_users': counts['total_users'],
        'paid_count': counts['paid_count'],
        'main_plus_count': counts['main_plus_count'],
        'premium_count': counts['premium_count'],
        'subscriber_count': counts['subscriber_count'],
        'slack_member_count': counts['slack_member_count'],
        'filter_all': FILTER_ALL,
        'filter_paid': FILTER_PAID,
        'filter_main_plus': FILTER_MAIN_PLUS,
        'filter_premium': FILTER_PREMIUM,
        'filter_subscribers': FILTER_SUBSCRIBERS,
        'slack_filter_any': SLACK_FILTER_ANY,
        'slack_filter_yes': SLACK_FILTER_YES,
        'slack_filter_no': SLACK_FILTER_NO,
    })


@staff_required
def user_export_csv(request):
    """Export the currently-filtered user list as CSV.

    Honours the same ``filter``, ``q``, ``tag``, and ``slack`` query
    params as ``user_list`` so operators can grab the exact rows they're
    looking at.

    Columns (locked by issue #355, with ``slack`` appended in #358):
    ``email, tier, tags, email_verified, unsubscribed, date_joined,
    last_login, slack``. ``tags`` is a comma-separated list of normalized
    strings; ``csv.writer`` quotes the cell when it contains commas.
    Datetimes use ISO 8601, with empty cells for nulls. Filename
    includes a UTC timestamp so repeat downloads do not collide.
    """
    active_filter = _normalize_filter(request.GET.get('filter', ''))
    slack_filter = _normalize_slack_filter(request.GET.get('slack', ''))
    search = request.GET.get('q', '')
    raw_tag = request.GET.get('tag', '')

    user_rows, _counts = _build_user_listing(
        active_filter, search, tag_filter=raw_tag, slack_filter=slack_filter,
    )

    timestamp = (
        timezone.now()
        .astimezone(datetime.timezone.utc)
        .strftime('%Y%m%d-%H%M%S')
    )
    filename = f'aishippinglabs-contacts-{timestamp}.csv'

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    writer = csv.writer(response)
    writer.writerow([
        'email',
        'tier',
        'tags',
        'email_verified',
        'unsubscribed',
        'date_joined',
        'last_login',
        'slack',
    ])
    for row in user_rows:
        writer.writerow([
            row['email'],
            row['tier_name'],
            ','.join(row['tags']),
            'Yes' if row['email_verified'] else 'No',
            'Yes' if row['unsubscribed'] else 'No',
            row['date_joined'].isoformat() if row['date_joined'] else '',
            row['last_login'].isoformat() if row['last_login'] else '',
            row['slack_status'],
        ])

    return response

# Generated password length, in bytes of entropy fed to ``token_urlsafe``.
# 16 bytes -> ~22-character base64 token, safely above the 16-character floor
# in the acceptance criteria.
PASSWORD_TOKEN_BYTES = 16

# Session key holding the one-shot stash of the generated password and the
# new user's identity. The confirmation view pops this and never writes it
# back, so refreshing or revisiting the page leaves nothing behind.
SESSION_KEY = 'studio_user_create_result'


def _render_form(request, *, email='', first_name='', last_name='',
                 make_admin=False, error='', status=200):
    context = {
        'email': email,
        'first_name': first_name,
        'last_name': last_name,
        'make_admin': make_admin,
        'error': error,
    }
    return render(request, 'studio/users/create.html', context, status=status)


@superuser_required
def user_create(request):
    """Show / handle the "New user" form.

    GET renders an empty form. POST validates, creates the user, stashes the
    password in the session, and redirects to the one-time confirmation page.
    """
    if request.method != 'POST':
        return _render_form(request)

    email = (request.POST.get('email') or '').strip()
    first_name = (request.POST.get('first_name') or '').strip()
    last_name = (request.POST.get('last_name') or '').strip()
    make_admin = request.POST.get('make_admin') == 'on'

    if not email:
        return _render_form(
            request,
            email=email,
            first_name=first_name,
            last_name=last_name,
            make_admin=make_admin,
            error='Email is required.',
            status=400,
        )

    normalized_email = User.objects.normalize_email(email)
    if User.objects.filter(email__iexact=normalized_email).exists():
        return _render_form(
            request,
            email=email,
            first_name=first_name,
            last_name=last_name,
            make_admin=make_admin,
            error=(
                f'A user with email "{normalized_email}" already exists. '
                'Pick a different email or send a password reset to the '
                'existing account.'
            ),
            status=400,
        )

    password = secrets.token_urlsafe(PASSWORD_TOKEN_BYTES)

    user = User(
        email=normalized_email,
        first_name=first_name,
        last_name=last_name,
        is_active=True,
        email_verified=True,
    )
    if make_admin:
        # Admins bypass tier gates everywhere they appear, so the tier value
        # on the row is moot. We still let the default-free-tier branch in
        # User.save() run -- keeping ``tier`` non-null preserves row
        # invariants the rest of the codebase relies on (e.g. the tier
        # override page reads ``user.tier`` directly).
        user.is_staff = True
        user.is_superuser = True
    user.set_password(password)
    user.save()

    request.session[SESSION_KEY] = {
        'user_id': user.pk,
        'email': user.email,
        'password': password,
        'is_admin': bool(user.is_staff or user.is_superuser),
    }
    return redirect('studio_user_create_done')


@superuser_required
def user_create_done(request):
    """Render the generated password exactly once, then drop the stash.

    Reads (and pops) the session stash written by ``user_create``. If the
    operator reloads or navigates back to this URL the stash is gone and they
    are redirected to the form with a hint.
    """
    stash = request.session.pop(SESSION_KEY, None)
    if not stash:
        return _render_form(
            request,
            error=(
                'The generated password is only displayed once, immediately '
                'after creating a user. Use "Send password reset" or create '
                'a new account if the operator missed it.'
            ),
            status=200,
        )

    context = {
        'user_id': stash.get('user_id'),
        'email': stash.get('email', ''),
        'password': stash.get('password', ''),
        'is_admin': bool(stash.get('is_admin')),
    }
    return render(request, 'studio/users/created.html', context)


# ---------------------------------------------------------------------------
# User detail page + tag add/remove (issue #354)
# ---------------------------------------------------------------------------


def _all_known_contact_tags():
    """Return the sorted, deduped union of every contact tag across users.

    Powers the ``<datalist>`` typeahead on the detail page so operators see
    suggestions for tags already in use without having to remember the exact
    spelling. Stays staff-only (callers all gate on ``staff_required``).
    """
    seen = set()
    for tag_list in User.objects.values_list('tags', flat=True):
        if not tag_list:
            continue
        # Normalize defensively in case any rows pre-date the helper.
        for tag in normalize_tags(tag_list):
            seen.add(tag)
    return sorted(seen)


def _active_override_for_user(user):
    """Return the user's active non-expired override, or None."""
    return (
        TierOverride.objects
        .filter(
            user_id=user.pk,
            is_active=True,
            expires_at__gt=timezone.now(),
        )
        .select_related('override_tier')
        .order_by('-created_at')
        .first()
    )


@staff_required
def user_detail(request, user_id):
    """Staff-only user detail page with the contact-tags editor.

    Reads from the same effective-tier helpers as the list view so the
    displayed tier matches what operators see in the table (including any
    active override).
    """
    user = get_object_or_404(User.objects.select_related('tier'), pk=user_id)
    override = _active_override_for_user(user)

    context = {
        'detail_user': user,
        'tier_name': _effective_tier_name(user, override),
        'has_override': override is not None,
        'is_subscribed': not user.unsubscribed,
        'tags': list(user.tags or []),
        'known_tags': _all_known_contact_tags(),
        'status': _user_status(user),
    }
    return render(request, 'studio/users/detail.html', context)


@staff_required
@require_POST
def user_tag_add(request, user_id):
    """POST handler: add a normalized tag to the user.

    Empty / whitespace input is rejected with a flash. Adding a tag the user
    already has is a silent no-op (idempotent). Always redirects back to the
    detail page.
    """
    user = get_object_or_404(User, pk=user_id)
    raw = (request.POST.get('tag') or '').strip()
    if not raw:
        messages.error(request, 'Enter a tag before clicking Add.')
        return redirect('studio_user_detail', user_id=user.pk)

    normalized = _add_tag_to_user(user, raw)
    if not normalized:
        messages.error(request, 'That tag normalized to an empty string. Use letters, digits, or hyphens.')
        return redirect('studio_user_detail', user_id=user.pk)

    messages.success(request, f'Tag "{normalized}" added.')
    return redirect('studio_user_detail', user_id=user.pk)


@staff_required
@require_POST
def user_tag_remove(request, user_id):
    """POST handler: remove a normalized tag from the user (idempotent)."""
    user = get_object_or_404(User, pk=user_id)
    raw = (request.POST.get('tag') or '').strip()
    if raw:
        _remove_tag_from_user(user, raw)
    return redirect('studio_user_detail', user_id=user.pk)
