# Generated by Django 6.0.2 on 2026-02-19 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Campaign body in markdown or HTML.')),
                ('target_min_level', models.IntegerField(default=0, help_text='Minimum tier level to receive this campaign. 0 = everyone, 1 = Basic+, 2 = Main+, 3 = Premium.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the campaign was sent.', null=True)),
                ('sent_count', models.IntegerField(default=0, help_text='Number of recipients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(help_text='Type of email: "campaign", "welcome", "payment_failed", "cancellation", "community_invite", "lead_magnet_delivery", "event_reminder", etc.', max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the email was sent.')),
                ('ses_message_id', models.CharField(blank=True, default='', help_text='Amazon SES message ID for delivery tracking.', max_length=255)),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated campaign (null for transactional emails).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='email_app.emailcampaign')),
                ('user', models.ForeignKey(help_text='User who received the email.', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
