# Generated by Django 6.0.2 on 2026-02-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('email_app', '0002_emailcampaign_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
