# Generated by Django 6.0.2 on 2026-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='target_min_level',
            field=models.IntegerField(choices=[(0, 'Everyone (including free)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level to receive this campaign. 0 = everyone, 10 = Basic+, 20 = Main+, 30 = Premium.'),
        ),
    ]
