# Generated by Django 6.0.2 on 2026-04-17 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_alter_emailcampaign_target_min_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', False)), fields=('campaign', 'user'), name='unique_campaign_recipient'),
        ),
    ]
