# Generated by Django 6.0.2 on 2026-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_emaillog_unique_campaign_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='target_tags_any',
            field=models.JSONField(blank=True, default=list, help_text='Recipient must carry at least one of these contact tags. Empty list = no include filter.'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='target_tags_none',
            field=models.JSONField(blank=True, default=list, help_text='Recipient must not carry any of these contact tags. Empty list = no exclude filter.'),
        ),
    ]
