# Generated by Django 6.0.2 on 2026-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_emaillog_unique_campaign_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='slack_filter',
            field=models.CharField(choices=[('any', 'Any'), ('yes', 'Members only'), ('no', 'Non-members only')], default='any', help_text='Restrict recipients by verified Slack workspace membership. "any" applies no filter; "yes" sends only to members; "no" sends only to non-members. Issue #358.', max_length=10),
        ),
    ]
