# Generated by Django 6.0.2 on 2026-05-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0008_migrate_newsletter_subscribers_to_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the SNS notification reached our webhook.')),
                ('event_type', models.CharField(choices=[('bounce_permanent', 'Bounce (permanent)'), ('bounce_transient', 'Bounce (transient)'), ('bounce_other', 'Bounce (other)'), ('complaint', 'Complaint'), ('delivery', 'Delivery'), ('subscription_confirmation', 'SubscriptionConfirmation'), ('unsubscribe_confirmation', 'UnsubscribeConfirmation'), ('other', 'Other')], db_index=True, help_text='Classified event type derived from the SNS payload.', max_length=40)),
                ('message_id', models.CharField(help_text='SNS MessageId. Used as the idempotency key for retried deliveries of the same notification.', max_length=255, unique=True)),
                ('raw_payload', models.JSONField(help_text='The unmodified SNS payload as posted to the webhook.')),
                ('recipient_email', models.EmailField(blank=True, db_index=True, default='', help_text='Recipient address parsed from the inner SES message, if any. Blank for SubscriptionConfirmation / Delivery events without a single recipient.', max_length=254)),
                ('action_taken', models.CharField(blank=True, default='', help_text="Short description of what the webhook did with this event (e.g. 'unsubscribed and tagged bounced', 'soft_bounce_count=2', 'no-op').", max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text='Matched User row, if any. Null when the recipient address is not in our database (still logged for audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ses_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
