# Generated by Django 6.0.2 on 2026-05-06 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0009_sesevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.SlugField(help_text='Slug of the on-disk template this row overrides (e.g. "welcome", "email_verification").', max_length=64, unique=True)),
                ('subject', models.CharField(help_text='Overrides the subject from the file frontmatter.', max_length=200)),
                ('body_markdown', models.TextField(help_text='Overrides the markdown body of the file template.')),
                ('footer_note', models.CharField(blank=True, default='', help_text='Per-template footer note appended to the email chrome. Useful for "P.S." messages or per-email disclaimers.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last operator who saved this override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_name'],
            },
        ),
    ]
