# Generated by Django 6.0.2 on 2026-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0010_emailtemplateoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the first SES click event, if any.', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Count of SES click events received for this email.'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the first SES open event, if any.', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opens',
            field=models.PositiveIntegerField(default=0, help_text='Count of SES open events received for this email.'),
        ),
        migrations.AlterField(
            model_name='sesevent',
            name='event_type',
            field=models.CharField(choices=[('bounce_permanent', 'Bounce (permanent)'), ('bounce_transient', 'Bounce (transient)'), ('bounce_other', 'Bounce (other)'), ('complaint', 'Complaint'), ('delivery', 'Delivery'), ('open', 'Open'), ('click', 'Click'), ('subscription_confirmation', 'SubscriptionConfirmation'), ('unsubscribe_confirmation', 'UnsubscribeConfirmation'), ('other', 'Other')], db_index=True, help_text='Classified event type derived from the SNS payload.', max_length=40),
        ),
    ]
