# Generated by Django 6.0.2 on 2026-05-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0011_emaillog_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='bounce_diagnostic',
            field=models.TextField(blank=True, default='', help_text='Diagnostic / status / reason text from the bounced recipient entry (e.g. "smtp; 550 5.1.1 user unknown").'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounce_subtype',
            field=models.CharField(blank=True, default='', help_text='SES bounceSubType, e.g. "General", "NoEmail", "Suppressed".', max_length=64),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounce_type',
            field=models.CharField(blank=True, default='', help_text='SES bounceType: "Permanent", "Transient", or "Undetermined".', max_length=32),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounced_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the first SES bounce event for this email.', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='complained_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the first SES complaint event for this email.', null=True),
        ),
        migrations.AddField(
            model_name='sesevent',
            name='bounce_subtype',
            field=models.CharField(blank=True, default='', help_text='SES bounceSubType (e.g. "General", "NoEmail", "Suppressed").', max_length=64),
        ),
        migrations.AddField(
            model_name='sesevent',
            name='bounce_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SES bounceType ("Permanent", "Transient", "Undetermined") for bounce events; empty for non-bounce events.', max_length=32),
        ),
        migrations.AddField(
            model_name='sesevent',
            name='diagnostic_code',
            field=models.TextField(blank=True, default='', help_text='Diagnostic / status / reason text from the bounced or complained recipient entry (where present).'),
        ),
        migrations.AddField(
            model_name='sesevent',
            name='email_log',
            field=models.ForeignKey(blank=True, help_text='Matched EmailLog row when the SES mail.messageId on the incoming event lines up with a transactional/campaign send.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ses_events', to='email_app.emaillog'),
        ),
    ]
