# Generated by Django 6.0.2 on 2026-05-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0013_create_django_q_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the campaign is archived (hidden from default list views). API callers flip this via PATCH; there is no DELETE endpoint.'),
        ),
    ]
