# Generated by Django 6.0.2 on 2026-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0014_emailcampaign_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='audience_verification',
            field=models.CharField(choices=[('verified_only', 'Verified only'), ('everyone', 'Everyone (including unverified)')], default='verified_only', help_text='Whether to require email_verified=True. "everyone" drops the verified-only filter; unsubscribed=False is always enforced.', max_length=20),
        ),
    ]
