# Generated by Django 6.0.2 on 2026-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0015_emailcampaign_audience_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplateoverride',
            name='template_name',
            field=models.SlugField(help_text='Slug of the on-disk template this row overrides (e.g. "welcome", "email_verification_signup").', max_length=64, unique=True),
        ),
    ]
