# Generated by Django 6.0.2 on 2026-06-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0016_alter_emailtemplateoverride_template_name'),
        ('events', '0028_event_host_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this email relates to (null for non-event emails).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='events.event'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', help_text='Destination address. Populated for sends to a non-user mailbox (e.g. an event host); blank when ``user`` carries the address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who received the email. Null for sends to an address that is not a registered platform user (e.g. an event host mailbox); see ``recipient_email`` in that case.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
