# Generated by Django 6.0.2 on 2026-06-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0017_emaillog_event_emaillog_recipient_email_and_more'),
        ('events', '0038_host_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='target_event',
            field=models.ForeignKey(blank=True, help_text='When set, the audience is everyone registered for this event (the tier/tag/Slack/verification filters AND on top). Null = the historical tier/tag audience.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event'),
        ),
    ]
