# Generated by Django 6.0.2 on 2026-07-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0018_emailcampaign_target_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='dedupe_key',
            field=models.CharField(blank=True, help_text='Optional application-level idempotency key for lifecycle sends. Null keeps legacy transactional sends unrestricted.', max_length=255, null=True, unique=True),
        ),
    ]
