# Generated by Django 6.0.2 on 2026-08-30 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def quarantine_legacy_sending_campaigns(apps, schema_editor):
    EmailCampaign = apps.get_model('email_app', 'EmailCampaign')
    EmailCampaign.objects.filter(status='sending').update(status='needs_attention')


def reverse_quarantine(apps, schema_editor):
    EmailCampaign = apps.get_model('email_app', 'EmailCampaign')
    EmailCampaign.objects.filter(
        status='needs_attention',
        audience_snapshotted_at__isnull=True,
    ).update(status='sending')


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0021_reconcile_emaillog_subject_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='audience_snapshotted_at',
            field=models.DateTimeField(blank=True, help_text='When the immutable delivery audience and batch schedules were created for this campaign.', null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('needs_attention', 'Needs attention'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_user_pk', models.PositiveBigIntegerField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('dispatching', 'Dispatching'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('ambiguous', 'Ambiguous'), ('assumed_sent', 'Assumed sent')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ses_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=100)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('resolution', models.CharField(blank=True, choices=[('retry', 'Retry'), ('assume_sent', 'Assume sent')], default='', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='email_app.emailcampaign')),
                ('email_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_delivery', to='email_app.emaillog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_campaign_deliveries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recipient_email', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'recipient_user_pk'), name='unique_campaign_delivery_recipient')],
            },
        ),
        migrations.RunPython(quarantine_legacy_sending_campaigns, reverse_quarantine),
    ]
