# Generated by Django 6.0.2 on 2026-09-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0024_emaillog_ses_msgid_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='audience_verification',
            field=models.CharField(choices=[('verified_only', 'Verified only'), ('unverified_only', 'Unverified only'), ('everyone', 'Everyone (including unverified)')], default='verified_only', help_text='Whether to require verified, unverified, or either verification state. unsubscribed=False is always enforced.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('needs_attention', 'Needs attention'), ('paused', 'Paused'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('monitoring', 'Monitoring'), ('complete', 'Complete'), ('paused', 'Paused')], db_index=True, default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='email_app.emailcampaign')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_campaign_waves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='campaigndelivery',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='email_app.campaignwave'),
        ),
        migrations.AddConstraint(
            model_name='campaignwave',
            constraint=models.UniqueConstraint(fields=('campaign', 'number'), name='unique_campaign_wave_number'),
        ),
        migrations.AddConstraint(
            model_name='campaignwave',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='campaign_wave_number_positive'),
        ),
    ]
