# Generated by Django 6.0.2 on 2026-05-11 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('persona', models.CharField(blank=True, default='', help_text='Free-text persona label, e.g. "Sam — The Technical Professional Moving to AI". Lives on the relationship so it survives across sprints.', max_length=120)),
                ('summary', models.TextField(blank=True, default='', help_text='Short staff summary of who this person is and why we are tracking them. Staff-only; never rendered to the member.')),
                ('next_steps', models.TextField(blank=True, default='', help_text='What is next for this member. Staff-only; never rendered to the member.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hypothesis', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='crm.crmrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crmrecord',
            index=models.Index(fields=['status'], name='crm_crmreco_status_01ef09_idx'),
        ),
    ]
