# Generated by Django 6.0.2 on 2026-06-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_crmrecord_persona_ref'),
        ('plans', '0015_sprintfeedbacksummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannelIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('oldest_ts', models.CharField(blank=True, default='', max_length=64)),
                ('latest_ts', models.CharField(blank=True, default='', max_length=64)),
                ('messages_seen', models.IntegerField(default=0)),
                ('threads_persisted', models.IntegerField(default=0)),
                ('replies_added', models.IntegerField(default=0)),
                ('members_matched', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='crm_slackch_status_8029c4_idx'), models.Index(fields=['-started_at'], name='crm_slackch_started_187025_idx')],
            },
        ),
        migrations.CreateModel(
            name='SlackThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64)),
                ('thread_ts', models.CharField(max_length=64)),
                ('slack_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('posted_at', models.DateTimeField()),
                ('permalink', models.URLField(blank=True, default='', max_length=600)),
                ('reply_count', models.IntegerField(default=0)),
                ('ingest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_captured_threads', to='crm.slackchannelingest')),
                ('last_seen_ingest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_threads', to='crm.slackchannelingest')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_threads', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_threads', to='plans.plan')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=64)),
                ('slack_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('author_display', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField()),
                ('is_root', models.BooleanField(default=False)),
                ('first_seen_ingest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_captured_messages', to='crm.slackchannelingest')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.slackthread')),
            ],
            options={
                'ordering': ['posted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='slackthread',
            index=models.Index(fields=['member', '-posted_at'], name='crm_slackth_member__980b38_idx'),
        ),
        migrations.AddIndex(
            model_name='slackthread',
            index=models.Index(fields=['plan'], name='crm_slackth_plan_id_6e9505_idx'),
        ),
        migrations.AddConstraint(
            model_name='slackthread',
            constraint=models.UniqueConstraint(fields=('channel_id', 'thread_ts'), name='unique_slack_thread_per_channel'),
        ),
        migrations.AddIndex(
            model_name='slackmessage',
            index=models.Index(fields=['thread', 'posted_at'], name='crm_slackme_thread__cf2675_idx'),
        ),
        migrations.AddConstraint(
            model_name='slackmessage',
            constraint=models.UniqueConstraint(fields=('thread', 'ts'), name='unique_slack_message_per_thread'),
        ),
    ]
