# Generated by Django 6.0.2 on 2026-06-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_slackchannelingest_slackthread_slackmessage_and_more'),
        ('plans', '0015_sprintfeedbacksummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('source_message_ts', models.CharField(blank=True, default='', max_length=64)),
                ('ingest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_events', to='crm.slackchannelingest')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_progress_events', to='plans.plan')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='crm.slackthread')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AppliedProgressChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_kind', models.CharField(choices=[('checkpoint', 'Checkpoint'), ('deliverable', 'Deliverable'), ('next_step', 'Next step')], max_length=20)),
                ('previous_done_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_progress_changes', to='plans.checkpoint')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_progress_changes', to='plans.deliverable')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_progress_changes', to='plans.nextstep')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='crm.ingestedprogressevent')),
            ],
            options={
                'ordering': ['applied_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ingestedprogressevent',
            constraint=models.UniqueConstraint(fields=('thread',), name='unique_progress_event_per_thread'),
        ),
        migrations.AddIndex(
            model_name='appliedprogresschange',
            index=models.Index(fields=['event'], name='crm_applied_event_i_549e3d_idx'),
        ),
    ]
