# Generated by Django 6.0.2 on 2026-06-18 16:05

import re

import django.db.models.deletion
from django.db import migrations, models


def _normalize_tag(tag):
    if not tag or not isinstance(tag, str):
        return ''
    tag = tag.strip().lower()
    tag = tag.replace(' ', '-').replace('_', '-')
    tag = re.sub(r'[^a-z0-9:-]', '', tag)
    tag = re.sub(r'-{2,}', '-', tag)
    tag = tag.strip('-')
    return tag


def _normalize_tags(tags):
    seen = set()
    result = []
    for tag in tags:
        normalized = _normalize_tag(tag)
        if normalized and normalized not in seen:
            seen.add(normalized)
            result.append(normalized)
    return result


def _normalize_slack_body(body):
    if not body:
        return ''
    text = str(body).replace('\r\n', '\n').replace('\r', '\n')
    text = re.sub(r'\bB_?locker:_\b', 'Blocker:', text)
    text = re.sub(r'(?<!\w)_([^_\n]+?)_(?!\w)', r'\1', text)
    lines = []
    for raw_line in text.split('\n'):
        line = raw_line.strip()
        if re.fullmatch(r'(?:[•*-]\s*)?[.]', line):
            continue
        if re.fullmatch(r'[•*-]\s*', line):
            continue
        lines.append(line)
    return re.sub(r'\n{3,}', '\n\n', '\n'.join(lines)).strip()


def _message_author(message):
    return (
        (getattr(message, 'author_display', '') or '').strip()
        or (getattr(message, 'slack_user_id', '') or '').strip()
        or 'Unknown'
    )


def _thread_body(messages):
    include_prefix = len(messages) > 1
    blocks = []
    for message in messages:
        text = _normalize_slack_body(message.text)
        if not text:
            continue
        if include_prefix:
            timestamp = message.posted_at.strftime('%Y-%m-%d %H:%M')
            text = f'{_message_author(message)} · {timestamp}\n{text}'
        blocks.append(text)
    return '\n\n'.join(blocks).strip()


def _thread_tags(thread):
    tags = ['slack', 'plan-sprints']
    sprint = getattr(getattr(thread, 'plan', None), 'sprint', None)
    if sprint is not None:
        sprint_slug = sprint.slug or sprint.name
        tags.append(f'sprint:{sprint_slug}')
    return _normalize_tags(tags)


def _thread_metadata(thread, messages):
    root = messages[0] if messages else None
    latest = messages[-1] if messages else None
    sprint = getattr(getattr(thread, 'plan', None), 'sprint', None)
    metadata = {
        'channel_id': thread.channel_id,
        'thread_ts': thread.thread_ts,
        'latest_message_ts': latest.ts if latest else thread.thread_ts,
        'permalink': thread.permalink,
        'author_display': _message_author(root) if root else '',
        'slack_user_id': thread.slack_user_id,
        'plan_id': thread.plan_id,
        'ingest_id': thread.last_seen_ingest_id,
    }
    if sprint is not None:
        metadata['sprint_name'] = sprint.name
        metadata['sprint_slug'] = sprint.slug
    return {key: value for key, value in metadata.items() if value not in (None, '')}


def backfill_slack_threads_to_notes(apps, schema_editor):
    SlackThread = apps.get_model('crm', 'SlackThread')
    SlackMessage = apps.get_model('crm', 'SlackMessage')
    CRMRecord = apps.get_model('crm', 'CRMRecord')
    InterviewNote = apps.get_model('plans', 'InterviewNote')

    threads = (
        SlackThread.objects
        .filter(member__isnull=False, interview_note__isnull=True)
        .select_related('plan__sprint')
        .order_by('posted_at', 'id')
    )
    for thread in threads.iterator():
        messages = list(
            SlackMessage.objects
            .filter(thread_id=thread.pk)
            .order_by('posted_at', 'id')
        )
        body = _thread_body(messages) or '(Slack update had no readable text.)'
        note = InterviewNote.objects.create(
            plan_id=thread.plan_id,
            member_id=thread.member_id,
            visibility='internal',
            kind='general',
            body=body,
            tags=_thread_tags(thread),
            source_type='slack',
            source_metadata=_thread_metadata(thread, messages),
        )
        SlackThread.objects.filter(pk=thread.pk).update(interview_note_id=note.pk)
        CRMRecord.objects.get_or_create(
            user_id=thread.member_id,
            defaults={'status': 'active'},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_ingestedprogressevent_appliedprogresschange_and_more'),
        ('plans', '0023_interviewnote_source_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackthread',
            name='interview_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_thread', to='plans.interviewnote'),
        ),
        migrations.RunPython(backfill_slack_threads_to_notes, noop_reverse),
    ]
