# Generated by Django 6.0.2 on 2026-02-20 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(help_text='Full GitHub repo name (e.g. AI-Shipping-Labs/blog).', max_length=300, unique=True)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('course', 'Course'), ('resource', 'Resource'), ('project', 'Project')], help_text='Type of content this repo contains.', max_length=20)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret for validating GitHub webhook signatures.', max_length=200)),
                ('is_private', models.BooleanField(default=False, help_text='Whether the repo is private (requires GitHub App auth).')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When the last sync completed.', null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running')], default=None, help_text='Status of the last sync.', max_length=20, null=True)),
                ('last_sync_log', models.TextField(blank=True, default=None, help_text='Log output from the last sync.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['repo_name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running')], default='running', max_length=20)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_deleted', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error objects: [{file, error}, ...]')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.contentsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
