# Generated by Django 6.0.2 on 2026-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_contentsource_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='content_path',
            field=models.CharField(blank=True, default='', help_text='Subdirectory within the repo to sync from (e.g. blog/). Empty means repo root.', max_length=300),
        ),
        migrations.AlterField(
            model_name='contentsource',
            name='repo_name',
            field=models.CharField(help_text='Full GitHub repo name (e.g. AI-Shipping-Labs/content).', max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='contentsource',
            unique_together={('repo_name', 'content_type')},
        ),
    ]
