# Generated by Django 6.0.2 on 2026-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_contentsource_content_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(db_index=True, help_text='Source URL path, e.g. /ai-engineer-resources', max_length=500, unique=True)),
                ('target_path', models.CharField(help_text='Target URL path, e.g. /interview', max_length=500)),
                ('redirect_type', models.IntegerField(choices=[(301, 'Permanent (301)'), (302, 'Temporary (302)')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_path'],
            },
        ),
    ]
