# Generated by Django 6.0.2 on 2026-03-20 20:58

from django.db import migrations

SEED_REDIRECTS = [
    ('/ai-engineer-resources', '/interview', 301),
    ('/ai-engineer-interview-questions', '/interview', 301),
    ('/ai-engineer-interview-questions/theory-interview-questions', '/interview/theory', 301),
    ('/ai-engineer-learning-path', '/learning-path/ai-engineer', 301),
]


def seed_redirects(apps, schema_editor):
    Redirect = apps.get_model('integrations', 'Redirect')
    for source, target, rtype in SEED_REDIRECTS:
        Redirect.objects.get_or_create(
            source_path=source,
            defaults={
                'target_path': target,
                'redirect_type': rtype,
                'is_active': True,
            },
        )


def unseed_redirects(apps, schema_editor):
    Redirect = apps.get_model('integrations', 'Redirect')
    sources = [s for s, _, _ in SEED_REDIRECTS]
    Redirect.objects.filter(source_path__in=sources).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_redirect'),
    ]

    operations = [
        migrations.RunPython(seed_redirects, unseed_redirects),
    ]
