# Generated by Django 6.0.2 on 2026-03-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_seed_redirects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('course', 'Course'), ('resource', 'Resource'), ('project', 'Project'), ('interview_question', 'Interview Question'), ('learning_path', 'Learning Path')], help_text='Type of content this repo contains.', max_length=30),
        ),
    ]
