# Generated by Django 6.0.2 on 2026-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_contentsource_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last webhook received.', null=True),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='max_files',
            field=models.PositiveIntegerField(default=1000, help_text='Safety limit on number of content files to process per sync.'),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='sync_locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of current sync lock. NULL when unlocked.', null=True),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='sync_requested',
            field=models.BooleanField(default=False, help_text='Flag indicating a sync was requested while another was running.'),
        ),
        migrations.AlterField(
            model_name='contentsource',
            name='last_sync_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running'), ('skipped', 'Skipped')], default=None, help_text='Status of the last sync.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running'), ('skipped', 'Skipped')], default='running', max_length=20),
        ),
    ]
