# Generated by Django 6.0.2 on 2026-03-24 13:26

from django.db import migrations, models


def remove_learning_path_sources(apps, schema_editor):
    """Remove ContentSource records with content_type='learning_path'.

    Learning path content now lives in the blog content path and is synced
    as articles with page_type='learning_path'.
    """
    ContentSource = apps.get_model('integrations', 'ContentSource')
    ContentSource.objects.filter(content_type='learning_path').delete()


def reverse_remove(apps, schema_editor):
    """Reverse: re-create learning_path content sources."""
    ContentSource = apps.get_model('integrations', 'ContentSource')
    import uuid
    ContentSource.objects.get_or_create(
        repo_name='AI-Shipping-Labs/content',
        content_type='learning_path',
        defaults={
            'id': uuid.uuid4(),
            'content_path': 'learning-path',
            'is_private': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_contentsource_last_webhook_at_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_learning_path_sources, reverse_remove),
        migrations.AlterField(
            model_name='contentsource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('course', 'Course'), ('resource', 'Resource'), ('project', 'Project'), ('interview_question', 'Interview Question')], help_text='Type of content this repo contains.', max_length=30),
        ),
    ]
