# Generated by Django 6.0.2 on 2026-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_update_learning_path_to_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('course', 'Course'), ('resource', 'Resource (legacy)'), ('recording', 'Recording'), ('curated_link', 'Curated Link'), ('project', 'Project'), ('interview_question', 'Interview Question')], help_text='Type of content this repo contains.', max_length=30),
        ),
    ]
