# Generated by Django 6.0.2 on 2026-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_contentsource_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('course', 'Course'), ('resource', 'Resource'), ('project', 'Project'), ('interview_question', 'Interview Question'), ('event', 'Event')], help_text='Type of content this repo contains.', max_length=30),
        ),
    ]
