# Generated by Django 6.0.2 on 2026-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_alter_contentsource_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Shared UUID grouping SyncLogs from the same Sync All action.', null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='items_detail',
            field=models.JSONField(blank=True, default=list, help_text='List of changed items: [{title, slug, action, content_type, url}, ...]'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='tiers_count',
            field=models.IntegerField(default=0, help_text='Number of tiers found in tiers.yaml.'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='tiers_synced',
            field=models.BooleanField(default=False, help_text='Whether tiers.yaml was synced during this operation.'),
        ),
    ]
