# Generated by Django 6.0.2 on 2026-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_integrationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Banner text shown between the dot and the link suffix.', max_length=200)),
                ('link_url', models.CharField(blank=True, default='', help_text='URL the banner links to. May be a relative path or absolute URL.', max_length=500)),
                ('link_label', models.CharField(blank=True, default='Read more', help_text='Text of the trailing accent-underlined link.', max_length=60)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master on/off switch.')),
                ('is_dismissible', models.BooleanField(default=True, help_text='When True, render an X close button.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Bumped when message or link_url changes; used as the dismissal cookie key.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement banner',
                'verbose_name_plural': 'Announcement banners',
            },
        ),
    ]
