# Generated by Django 6.0.2 on 2026-04-17 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_announcementbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtmCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name shown in Studio.', max_length=200)),
                ('slug', models.SlugField(help_text='Used as utm_campaign value. Lowercase letters, digits, and underscores only.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, and underscores only.', regex='^[a-z0-9_]+$')])),
                ('default_utm_source', models.CharField(help_text='Default source for new links in this campaign (e.g. newsletter).', max_length=100)),
                ('default_utm_medium', models.CharField(help_text='Default medium for new links in this campaign (e.g. email).', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the team.')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utm_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UTM Campaign',
                'verbose_name_plural': 'UTM Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtmCampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_content', models.SlugField(help_text='Audience or placement tag (e.g. ai_hero_list).', max_length=100, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, and underscores only.', regex='^[a-z0-9_]+$')])),
                ('utm_term', models.CharField(blank=True, help_text='Optional term, included in the URL only if non-empty.', max_length=100)),
                ('utm_source', models.CharField(blank=True, help_text='Overrides campaign default source when non-empty.', max_length=100)),
                ('utm_medium', models.CharField(blank=True, help_text='Overrides campaign default medium when non-empty.', max_length=100)),
                ('destination', models.CharField(help_text='Either a path (e.g. /events/...) or a full URL.', max_length=1000)),
                ('label', models.CharField(blank=True, help_text='Short human description (e.g. AI Hero newsletter list).', max_length=200)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='integrations.utmcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utm_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UTM Campaign Link',
                'verbose_name_plural': 'UTM Campaign Links',
                'ordering': ['utm_content'],
                'unique_together': {('campaign', 'utm_content')},
            },
        ),
    ]
