# Generated by Django 6.0.2 on 2026-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_utmcampaign_utmcampaignlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='items_unchanged',
            field=models.IntegerField(default=0, help_text='Items found in the repo whose content matched the DB row exactly and were skipped (no save, no items_detail entry). See issue #225.'),
        ),
    ]
