# Generated by Django 6.0.2 on 2026-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_synclog_items_unchanged'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='last_synced_commit',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Git commit SHA from the last successful sync. Used to skip no-op syncs when the upstream HEAD has not changed (issue #235).', max_length=40),
        ),
        migrations.AddField(
            model_name='synclog',
            name='commit_sha',
            field=models.CharField(blank=True, default='', help_text='Git commit SHA this sync ran against. For ``skipped`` rows this is the SHA we compared HEAD against (issue #235).', max_length=40),
        ),
    ]
