# Generated by Django 6.0.2 on 2026-04-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_contentsource_last_synced_commit_synclog_commit_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='last_sync_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('skipped', 'Skipped')], default=None, help_text='Status of the last sync.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('skipped', 'Skipped')], default='running', max_length=20),
        ),
    ]
