# Generated by Django 6.0.2 on 2026-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_add_queued_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('course', 'Course'), ('resource', 'Resource'), ('project', 'Project'), ('interview_question', 'Interview Question'), ('event', 'Event'), ('workshop', 'Workshop')], help_text='Type of content this repo contains.', max_length=30),
        ),
    ]
