# Generated by Django 6.0.2 on 2026-04-25 16:02
"""Relax ``ContentSource`` uniqueness to include ``content_path`` (issue #286).

Old constraint: ``unique_together = [('repo_name', 'content_type')]``.
New constraint: ``unique_together = [('repo_name', 'content_type', 'content_path')]``.

This is a strict relaxation — every pair allowed by the old constraint is
also allowed by the new one. No existing row can violate the new constraint
unless two existing rows share all three fields, which the old constraint
already forbade. Therefore no data cleanup is required.

We still run a defensive duplicate check before applying the new constraint:
if some out-of-band write somehow produced duplicates, we want a clear error
listing them rather than a confusing IntegrityError later.
"""

from django.db import migrations


def _check_no_duplicates(apps, schema_editor):
    """Fail loudly if existing rows already violate the new constraint."""
    ContentSource = apps.get_model('integrations', 'ContentSource')
    seen = {}
    duplicates = []
    for source in ContentSource.objects.all().values(
        'pk', 'repo_name', 'content_type', 'content_path',
    ):
        key = (
            source['repo_name'],
            source['content_type'],
            source['content_path'],
        )
        if key in seen:
            duplicates.append((seen[key], source['pk'], key))
        else:
            seen[key] = source['pk']

    if duplicates:
        details = '\n'.join(
            f'  - existing pk={a}, duplicate pk={b}, '
            f'(repo_name, content_type, content_path)={k!r}'
            for a, b, k in duplicates
        )
        raise RuntimeError(
            'Cannot add unique_together '
            '(repo_name, content_type, content_path): duplicate rows '
            f'detected:\n{details}\n'
            'Resolve the duplicates manually before re-running migrate.'
        )


def _noop_reverse(apps, schema_editor):
    """Reverse is a no-op — the check is read-only."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_add_instructor_content_type'),
    ]

    operations = [
        migrations.RunPython(_check_no_duplicates, _noop_reverse),
        migrations.AlterUniqueTogether(
            name='contentsource',
            unique_together={('repo_name', 'content_type', 'content_path')},
        ),
    ]
