# Generated by Django 6.0.2 on 2026-06-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_consolidate_content_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MavenEnrollmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(help_text='Normalized email + cohort + event type. Unique per processed event.', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('course', models.CharField(blank=True, default='', max_length=255)),
                ('cohort', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('outcome', models.CharField(blank=True, choices=[('onboarded', 'Onboarded'), ('refreshed', 'Refreshed'), ('already_member', 'Already a member'), ('removal_notified', 'Removal notified'), ('ignored', 'Ignored')], default='', help_text='Terminal outcome recorded for this event.', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maven Enrollment Event',
                'verbose_name_plural': 'Maven Enrollment Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
