# Generated by Django 6.0.2 on 2026-07-14 14:18

import django.db.models.deletion
import django.db.models.functions
from django.conf import settings
from django.db import migrations, models


def mark_existing_rows_legacy(apps, schema_editor):
    apps.get_model('integrations', 'MavenEnrollmentEvent').objects.update(
        lifecycle='legacy'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_seed_cloudflare_workshop_redirect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='cohort_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='course_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='identity_hash',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('legacy', 'Legacy')], db_default='legacy', db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='override_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='override_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='override_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='override_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='override_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_default='pending', default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='payload_redacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='removal_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='removal_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='removal_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='removal_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='removal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_default='skipped', default='skipped', max_length=16),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='slack_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='slack_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='slack_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='slack_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='slack_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_default='pending', default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.Now()),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maven_enrollment_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='welcome_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='welcome_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='welcome_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='welcome_eligible',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='welcome_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='welcome_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_default='pending', default='pending', max_length=16),
        ),
        migrations.RunPython(mark_existing_rows_legacy, migrations.RunPython.noop),
    ]
