# Generated by Django 6.0.2 on 2026-09-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_maven_enrollment_notification_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='calendly_event_uri',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', help_text='Stable Calendly scheduled-event URI correlation.', max_length=500),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='calendly_invitee_uri',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', help_text='Stable Calendly invitee URI correlation.', max_length=500),
        ),
    ]
