# Generated by Django 6.0.2 on 2026-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0030_copy_integration_settings_to_cb_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='content_sync_slug',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', help_text='A2.3 rollback mapping: the package ContentSource.slug this row was copied to (written by the data migration).', max_length=100),
        ),
    ]
