# Generated by Django 6.0.2 on 2026-09-15 11:02

from django.db import migrations, models


def skip_existing_occurrences(apps, schema_editor):
    apps.get_model("integrations", "MavenEnrollmentEvent").objects.update(
        enrollment_status="skipped",
        enrollment_attempts=0,
        enrollment_attempted_at=None,
        enrollment_completed_at=None,
        enrollment_error="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0032_copy_content_sync_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='enrollment_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='enrollment_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='enrollment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='enrollment_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='enrollment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_default='skipped', default='skipped', max_length=16),
        ),
        migrations.RunPython(skip_existing_occurrences, migrations.RunPython.noop),
    ]
