# Generated by Django 6.0.2 on 2026-09-17 11:20

from django.db import migrations, models


def skip_existing_occurrences(apps, schema_editor):
    """Make every pre-#1732 occurrence terminal for the new ``tagging`` step.

    Cohorts 1-4 were tagged by an operator contact import outside the ledger,
    so their occurrences must never be re-tagged. ``db_default`` already
    writes ``skipped`` for existing rows; this states it explicitly, matching
    the ``enrollment`` step migration (#1659).
    """
    apps.get_model("integrations", "MavenEnrollmentEvent").objects.update(
        tagging_status="skipped",
        tagging_attempts=0,
        tagging_attempted_at=None,
        tagging_completed_at=None,
        tagging_error="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_mavenenrollmentevent_enrollment_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='tagging_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='tagging_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='tagging_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='tagging_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mavenenrollmentevent',
            name='tagging_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_default='skipped', default='skipped', max_length=16),
        ),
        migrations.RunPython(skip_existing_occurrences, migrations.RunPython.noop),
    ]
