"""Playwright E2E for issue #573: cron flips ended events to completed.

Covers the 8 BDD scenarios in the issue:
1. Visitor sees a just-ended event move from upcoming to past on /events.
2. Visitor still sees a future event as upcoming.
3. Visitor sees an event without `end_datetime` treated as ended after 1h.
4. Visitor sees an event that just started still as upcoming.
5. Member dashboard hides ended registered events.
6. Registration POST is rejected for an event whose start has passed.
7. Cancelled event is not silently flipped to completed.
8. Public /events upcoming-section count drops after the cron runs.

The cron task is invoked directly in test setup via
`events.tasks.complete_finished_events.complete_finished_events`. We never
wait for Django-Q to tick.

Usage:
    uv run pytest playwright_tests/test_complete_finished_events.py -v
"""

import datetime
import json
import os
import urllib.error
import urllib.request
from datetime import timedelta

import pytest
from django.utils import timezone

from playwright_tests.conftest import (
    auth_context as _auth_context,
)
from playwright_tests.conftest import (
    create_session_for_user as _create_session_for_user,
)
from playwright_tests.conftest import (
    create_user as _create_user,
)
from playwright_tests.conftest import (
    ensure_tiers as _ensure_tiers,
)

os.environ.setdefault("DJANGO_ALLOW_ASYNC_UNSAFE", "true")
from django.db import connection  # noqa: E402


def _clear_events():
    from events.models import Event, EventRegistration

    EventRegistration.objects.all().delete()
    Event.objects.all().delete()
    connection.close()


def _create_event(
    *,
    slug,
    title=None,
    status="upcoming",
    start_offset=None,
    end_offset=None,
    required_level=0,
):
    from events.models import Event

    if title is None:
        title = slug
    now = timezone.now()
    start_dt = now + (start_offset or timedelta(days=7))
    end_dt = None if end_offset is None else now + end_offset
    event = Event.objects.create(
        slug=slug,
        title=title,
        description="Auto-generated by tests.",
        start_datetime=start_dt,
        end_datetime=end_dt,
        status=status,
        required_level=required_level,
    )
    connection.close()
    return event


def _run_cron():
    from events.tasks.complete_finished_events import complete_finished_events

    flipped = complete_finished_events()
    connection.close()
    return flipped


def _refresh_status(slug):
    from events.models import Event

    status = Event.objects.get(slug=slug).status
    connection.close()
    return status


@pytest.mark.django_db(transaction=True)
class TestJustEndedEventMovesToPast:
    """Scenario 1: just-ended event moves from upcoming to past on /events."""

    def test_just_ended_event_moves_from_upcoming_to_past(
        self, django_server, page,
    ):
        _clear_events()
        _ensure_tiers()
        _create_event(
            slug="today-just-ended",
            title="Today Just Ended",
            start_offset=timedelta(minutes=-90),
            end_offset=timedelta(minutes=-30),
        )

        _run_cron()

        page.goto(
            f"{django_server}/events",
            wait_until="domcontentloaded",
        )

        past_section = page.locator('[data-testid="events-past-section"]')
        assert past_section.count() == 1
        assert "Today Just Ended" in past_section.inner_text()

        # The event must NOT appear in the upcoming section. Scope the
        # locator to the upcoming-section testid so we don't get false
        # positives from sibling text (filter tabs, headings, etc.).
        upcoming_section = page.locator(
            '[data-testid="events-upcoming-section"]'
        )
        assert upcoming_section.count() == 1
        assert "Today Just Ended" not in upcoming_section.inner_text()

        # Detail page shows the Completed badge.
        page.goto(
            f"{django_server}/events/today-just-ended",
            wait_until="domcontentloaded",
        )
        badges_row = page.locator("h1").first.locator(
            "xpath=preceding-sibling::div[1]"
        )
        assert "Completed" in badges_row.inner_text()
        assert "Upcoming" not in badges_row.inner_text()


@pytest.mark.django_db(transaction=True)
class TestFutureEventStaysUpcoming:
    """Scenario 2: future event stays upcoming."""

    def test_future_event_stays_upcoming(self, django_server, page):
        _clear_events()
        _ensure_tiers()
        _create_event(
            slug="next-week",
            title="Next Week",
            start_offset=timedelta(days=7),
            end_offset=None,
        )

        _run_cron()

        page.goto(
            f"{django_server}/events",
            wait_until="domcontentloaded",
        )
        body_text = page.locator("main").inner_text()
        assert "Next Week" in body_text

        # The event must not appear in the past section.
        past_section = page.locator('[data-testid="events-past-section"]')
        assert "Next Week" not in past_section.inner_text()


@pytest.mark.django_db(transaction=True)
class TestImplicitEndTreatedAsEnded:
    """Scenario 3: event with no end_datetime is treated as ended after 1h."""

    def test_flash_qa_without_end_datetime_moves_to_past(
        self, django_server, page,
    ):
        _clear_events()
        _ensure_tiers()
        _create_event(
            slug="flash-qa",
            title="Flash QA",
            start_offset=timedelta(minutes=-75),
            end_offset=None,
        )

        _run_cron()

        page.goto(
            f"{django_server}/events",
            wait_until="domcontentloaded",
        )

        past_section = page.locator('[data-testid="events-past-section"]')
        assert "Flash QA" in past_section.inner_text()

        # Scope the NOT-in-upcoming guard to the upcoming-section testid.
        upcoming_section = page.locator(
            '[data-testid="events-upcoming-section"]'
        )
        assert upcoming_section.count() == 1
        assert "Flash QA" not in upcoming_section.inner_text()


@pytest.mark.django_db(transaction=True)
class TestLiveEventStaysUpcoming:
    """Scenario 4: event that just started (no end_datetime) stays upcoming."""

    def test_live_now_event_stays_upcoming(self, django_server, page):
        _clear_events()
        _ensure_tiers()
        _create_event(
            slug="live-now",
            title="Live Now",
            start_offset=timedelta(minutes=-10),
            end_offset=None,
        )

        _run_cron()

        page.goto(
            f"{django_server}/events",
            wait_until="domcontentloaded",
        )

        # Event must render in the upcoming section and NOT in the past
        # section. Use scoped testid locators so we don't get fooled by
        # filter-tab labels or other sibling text on the page.
        upcoming_section = page.locator(
            '[data-testid="events-upcoming-section"]'
        )
        assert upcoming_section.count() == 1
        assert "Live Now" in upcoming_section.inner_text()

        past_section = page.locator('[data-testid="events-past-section"]')
        if past_section.count() > 0:
            assert "Live Now" not in past_section.inner_text()


@pytest.mark.django_db(transaction=True)
class TestMemberDashboardHidesEndedEvents:
    """Scenario 5: member dashboard hides ended registered events."""

    def test_dashboard_hides_ended_registered_event(
        self, django_server, browser,
    ):
        from events.models import EventRegistration

        _clear_events()
        _ensure_tiers()
        _create_user("member@test.com", tier_slug="free")

        ended_event = _create_event(
            slug="dashboard-ended",
            title="Dashboard Ended",
            start_offset=timedelta(hours=-2),
            end_offset=timedelta(hours=-1),
        )
        future_event = _create_event(
            slug="dashboard-future",
            title="Dashboard Future",
            start_offset=timedelta(days=3),
            end_offset=None,
        )

        from accounts.models import User
        user = User.objects.get(email="member@test.com")
        EventRegistration.objects.create(user=user, event=ended_event)
        EventRegistration.objects.create(user=user, event=future_event)
        connection.close()

        _run_cron()

        context = _auth_context(browser, "member@test.com")
        page = context.new_page()
        page.goto(f"{django_server}/", wait_until="domcontentloaded")

        body_text = page.locator("body").inner_text()
        assert "Dashboard Future" in body_text
        assert "Dashboard Ended" not in body_text
        context.close()


@pytest.mark.django_db(transaction=True)
class TestRegistrationRejectedForEndedEvent:
    """Scenario 6: registration POST is rejected for an event whose start has passed."""

    def test_register_after_start_returns_409(self, django_server, browser):
        _clear_events()
        _ensure_tiers()
        _create_user("member@test.com", tier_slug="free")
        _create_event(
            slug="late-register",
            title="Late Register",
            start_offset=timedelta(minutes=-90),
            end_offset=timedelta(minutes=-30),
            required_level=0,
        )

        _run_cron()

        # POST /api/events/<slug>/register using urllib with session cookie.
        # Django CSRF middleware rejects tokens shorter than 32 chars with
        # 403 before our view runs, so use a 32-char token (mirrors
        # playwright_tests/test_event_time_display.py::_auth_context).
        session_key = _create_session_for_user("member@test.com")
        csrf_token = "a" * 32
        request = urllib.request.Request(
            f"{django_server}/api/events/late-register/register",
            data=b"",
            method="POST",
            headers={
                "Cookie": (
                    f"sessionid={session_key}; csrftoken={csrf_token}"
                ),
                "X-CSRFToken": csrf_token,
                "Referer": django_server,
                "Content-Type": "application/json",
            },
        )

        try:
            urllib.request.urlopen(request, timeout=5)
            pytest.fail("Expected HTTPError 409 but request succeeded")
        except urllib.error.HTTPError as exc:
            assert exc.code == 409
            body = json.loads(exc.read().decode("utf-8"))
            assert body.get("error") == "Event is not open for registration"

        # The detail page must not render the registration card or the
        # external Join card. Browse as the authed user.
        context = _auth_context(browser, "member@test.com")
        page = context.new_page()
        page.goto(
            f"{django_server}/events/late-register",
            wait_until="domcontentloaded",
        )
        assert page.locator(
            '[data-testid="event-registration-card"]'
        ).count() == 0
        assert page.locator(
            '[data-testid="event-external-join-card"]'
        ).count() == 0
        context.close()


@pytest.mark.django_db(transaction=True)
class TestCancelledEventNotFlipped:
    """Scenario 7: cancelled event is not silently flipped to completed."""

    def test_cancelled_event_keeps_cancelled_status(
        self, django_server, page,
    ):
        _clear_events()
        _ensure_tiers()
        _create_event(
            slug="was-cancelled",
            title="Was Cancelled",
            status="cancelled",
            start_offset=timedelta(days=-3),
            end_offset=None,
        )

        _run_cron()

        page.goto(
            f"{django_server}/events/was-cancelled",
            wait_until="domcontentloaded",
        )

        # Status badge reads "Cancelled".
        badges_row = page.locator("h1").first.locator(
            "xpath=preceding-sibling::div[1]"
        )
        assert "Cancelled" in badges_row.inner_text()

        # DB row remains 'cancelled'.
        assert _refresh_status("was-cancelled") == "cancelled"


@pytest.mark.django_db(transaction=True)
class TestPublicEventsUpcomingCountDrops:
    """Scenario 8: the public /events upcoming list drops the ended event after the cron.

    The studio dashboard already double-filters on
    ``status='upcoming' AND start_datetime__gte=now`` (studio/views/dashboard.py:52,89),
    so it visually hides ended events even before the cron flips them.

    The visible regression caused by missing the cron lives on the public
    events list at ``events/views/pages.py:151``, which filters ONLY on
    ``status='upcoming'``. Until the cron runs, the past-start event shows
    up in the Upcoming section. That is what this scenario verifies.
    """

    def test_public_upcoming_count_drops_after_cron(
        self, django_server, page,
    ):
        _clear_events()
        _ensure_tiers()

        _create_event(
            slug="public-ended",
            title="Public Ended",
            start_offset=timedelta(hours=-2),
            end_offset=timedelta(hours=-1),
        )
        _create_event(
            slug="public-soon",
            title="Public Soon",
            start_offset=timedelta(days=2),
            end_offset=None,
        )
        _create_event(
            slug="public-later",
            title="Public Later",
            start_offset=timedelta(days=5),
            end_offset=None,
        )

        # Before the cron runs: all three events have status='upcoming',
        # so the public Upcoming section lists 3.
        page.goto(f"{django_server}/events", wait_until="domcontentloaded")
        upcoming_section = page.locator(
            '[data-testid="events-upcoming-section"]'
        )
        assert upcoming_section.count() == 1
        before_cards = upcoming_section.locator("article")
        assert before_cards.count() == 3
        before_text = upcoming_section.inner_text()
        assert "Public Ended" in before_text
        assert "Public Soon" in before_text
        assert "Public Later" in before_text

        # Run the cron task — flips status of the ended event to completed.
        flipped = _run_cron()
        assert flipped == 1

        # After the cron: the ended event has status='completed' and is no
        # longer in the Upcoming section. Two upcoming cards remain.
        page.goto(f"{django_server}/events", wait_until="domcontentloaded")
        upcoming_section = page.locator(
            '[data-testid="events-upcoming-section"]'
        )
        assert upcoming_section.count() == 1
        after_cards = upcoming_section.locator("article")
        assert after_cards.count() == 2
        after_text = upcoming_section.inner_text()
        assert "Public Soon" in after_text
        assert "Public Later" in after_text
        assert "Public Ended" not in after_text


# Suppress unused-import warnings for import-only modules above.
_ = datetime
