# Generated by Django 6.0.2 on 2026-08-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0042_event_host_access_version_hostinvitedelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe id powering /books/<slug>. Operator-entered, content-derivable (e.g. "inference-engineering").', max_length=160, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='', help_text='Publisher/CDN cover image URL. Blank shows a tinted spine.', max_length=500)),
                ('cover_accent', models.CharField(blank=True, default='from-accent/30', help_text='Tailwind gradient token for the tinted-spine fallback when no cover image exists (e.g. from-accent/30, from-blue-500/30).', max_length=60)),
                ('required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=20, help_text='Minimum tier level required to participate. Default 20 (Main).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('current', 'Current'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Kickoff date. Drives ordering and the "Kickoff …" label.', null=True)),
                ('meeting_cadence', models.CharField(blank=True, default='', help_text='Display label for the meeting cadence, e.g. "Weekly · 17:00 CET". Interim field; the authoritative source is the event series (#1369).', max_length=80)),
                ('buy_url', models.URLField(blank=True, default='', help_text='Publisher/buy page for the book.', max_length=500)),
                ('event_series', models.ForeignKey(blank=True, help_text='Optional recurring meeting series for this book club. Deleting the series unlinks the book; the book itself is preserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='events.eventseries')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Chapter order, starting at 0. Unique per book.')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField(blank=True, help_text='Optional meeting appointment date. No recurrence engine.', null=True)),
                ('week_label', models.CharField(blank=True, default='', help_text='Optional display label, e.g. "Week 1".', max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bookclub.book')),
                ('event', models.ForeignKey(blank=True, help_text='Optional linked event. Deleting the event unlinks the chapter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_chapters', to='events.event')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='bookclub_bo_status_7699b0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='bookclub_bo_slug_2e395c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'number'), name='uniq_book_chapter_number'),
        ),
    ]
