# Generated by Django 6.0.2 on 2026-08-06 18:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_chapterread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(help_text='The note text. An empty submit clears/deletes the note.')),
                ('diagram', models.TextField(blank=True, default='', help_text='Optional mermaid diagram source (no image uploads).')),
                ('comment_content_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bookclub.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chapter'], name='bookclub_no_chapter_b2f548_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter'), name='uniq_book_chapter_note')],
            },
        ),
    ]
