# Generated by Django 6.0.2 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_readerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Full-book overall summary (plain text; blank-line-separated paragraphs). Also holds the working draft before publish.'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_published_at',
            field=models.DateTimeField(blank=True, help_text='When the full-book summary was published. Null = draft.', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Chapter summary (plain text; blank-line-separated paragraphs). Also holds the working draft before publish.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary_published_at',
            field=models.DateTimeField(blank=True, help_text='When the chapter summary was published. Null = draft.', null=True),
        ),
    ]
