# Generated by Django 6.0.2 on 2026-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_chapter_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=20, help_text='Minimum tier level required to participate. Default 20 (Main).'),
        ),
    ]
