# Generated by Django 6.0.2 on 2026-08-27

from django.db import migrations, models


def make_existing_profiles_public(apps, schema_editor):
    ReaderProfile = apps.get_model('bookclub', 'ReaderProfile')
    ReaderProfile.objects.update(visibility='public')


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_alter_book_required_level'),
    ]

    operations = [
        migrations.RunPython(
            make_existing_profiles_public,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='readerprofile',
            name='visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('private', 'Private')],
                default='public',
                help_text=(
                    "Public shows this member's book notes to other members "
                    'in the group feed and on their reader profile. Private '
                    'keeps notes visible only to the member (and staff). '
                    'Default public.'
                ),
                max_length=10,
            ),
        ),
    ]
