# Generated by Django 6.0.2 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('reading_time', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CuratedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('tools', 'Tools'), ('models', 'Models'), ('courses', 'Courses'), ('other', 'Other')], max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reading_time', models.CharField(blank=True, default='', max_length=50)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20)),
                ('estimated_time', models.CharField(blank=True, default='', max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(blank=True, default='', max_length=100)),
                ('google_embed_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('timestamps', models.JSONField(blank=True, default=list)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('core_tools', models.JSONField(blank=True, default=list)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('outcome', models.TextField(blank=True, default='')),
                ('related_course', models.CharField(blank=True, default='', max_length=300)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reading_time', models.CharField(blank=True, default='', max_length=50)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
