# Generated by Django 6.0.2 on 2026-02-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view full content.'),
        ),
        migrations.AddField(
            model_name='curatedlink',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view full content.'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view full content.'),
        ),
        migrations.AddField(
            model_name='recording',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view full content.'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view full content.'),
        ),
    ]
