# Generated by Django 6.0.2 on 2026-02-19 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_cover_image_url_article_published_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='User who submitted this project (community submissions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recording',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
