# Generated by Django 6.0.2 on 2026-02-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_recording_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedlink',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
