# Generated by Django 6.0.2 on 2026-02-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_curatedlink_add_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(help_text='URL to the downloadable file (S3, storage, etc.).', max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('zip', 'ZIP'), ('slides', 'Slides'), ('notebook', 'Notebook'), ('csv', 'CSV'), ('other', 'Other')], default='pdf', help_text='Type of file (pdf, zip, slides, etc.).', max_length=20)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to download. 0 = lead magnet (email signup).')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
