# Generated by Django 6.0.2 on 2026-02-19 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_download'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown description shown on the course detail page.')),
                ('description_html', models.TextField(blank=True, default='', help_text='Auto-rendered HTML from description markdown.')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=200)),
                ('instructor_bio', models.TextField(blank=True, default='')),
                ('required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to access course units.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_free', models.BooleanField(default=False, help_text='True for lead-magnet courses (required_level = 0).')),
                ('discussion_url', models.URLField(blank=True, default='', help_text='Slack channel URL for paid courses, GitHub URL for free courses.', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='', help_text='Markdown lesson text.')),
                ('body_html', models.TextField(blank=True, default='', help_text='Auto-rendered HTML from body markdown.')),
                ('homework', models.TextField(blank=True, default='', help_text='Markdown homework description.')),
                ('homework_html', models.TextField(blank=True, default='', help_text='Auto-rendered HTML from homework markdown.')),
                ('timestamps', models.JSONField(blank=True, default=list, help_text='List of {time_seconds, label} objects.')),
                ('is_preview', models.BooleanField(default=False, help_text='If true, visible to everyone regardless of course access.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.module')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'unit')},
            },
        ),
    ]
