# Generated by Django 6.0.2 on 2026-02-19 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_course_module_unit_usercourseprogress'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Link to the originating event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='events.event'),
        ),
        migrations.AddField(
            model_name='unit',
            name='available_after_days',
            field=models.IntegerField(blank=True, help_text='For cohort drip schedule: unit becomes available this many days after cohort start_date. Null = available immediately.', null=True),
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "March 2026 Cohort"', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants. Leave blank for unlimited.', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='content.course')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CohortEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cohort', 'user')},
            },
        ),
    ]
