# Generated by Django 6.0.2 on 2026-02-19 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_recording_event_unit_available_after_days_cohort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(help_text='Tag to match (e.g. "ai-engineer"). Must be normalized: lowercase, hyphenated.', max_length=200)),
                ('component_type', models.CharField(help_text='Component type identifier (e.g. "course_promo", "download_cta", "roadmap_signup").', max_length=200)),
                ('component_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for the component (e.g. {"course_slug": "python-data-ai", "cta_text": "Start learning"}).')),
                ('position', models.CharField(choices=[('after_content', 'After Content'), ('sidebar', 'Sidebar')], default='after_content', help_text='Where to inject the component on the detail page.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag', 'position'],
            },
        ),
    ]
