# Generated by Django 6.0.2 on 2026-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_tagrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from (e.g. AI-Shipping-Labs/blog).', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='curatedlink',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='curatedlink',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='curatedlink',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
    ]
