# Generated by Django 6.0.2 on 2026-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_article_source_commit_article_source_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='s3_url',
            field=models.URLField(blank=True, default='', help_text='S3 URL for the recording file (auto-populated after upload).', max_length=500),
        ),
    ]
