# Generated by Django 6.0.2 on 2026-02-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_recording_s3_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='individual_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for one-time individual purchase in EUR. Null = not sold individually.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', help_text='Stripe price ID for individual purchase.', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', help_text='Stripe product ID for individual purchase.', max_length=255),
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('purchased', 'Purchased'), ('granted', 'Granted')], default='purchased', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, default='', help_text='Stripe checkout session ID (empty for granted access).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_access', to='content.course')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted access (null for purchased).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_course_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
