# Generated by Django 6.0.2 on 2026-03-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_course_individual_price_eur_course_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('sections_json', models.JSONField(blank=True, default=list, help_text='List of section objects with id, title, intro, qa.')),
                ('body_markdown', models.TextField(blank=True, default='', help_text='Markdown body content from the file.')),
                ('source_repo', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'interview categories',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('data_json', models.JSONField(blank=True, default=dict, help_text='Full YAML content stored as JSON.')),
                ('source_repo', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
