# Generated by Django 6.0.2 on 2026-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_interviewcategory_learningpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='content_hash',
            field=models.CharField(blank=True, help_text='MD5 hex digest of body text for rename detection.', max_length=32, null=True),
        ),
    ]
