# Generated by Django 6.0.2 on 2026-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_unit_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='transcript_text',
            field=models.TextField(blank=True, default='', help_text='Plain-text transcript content for display and search.'),
        ),
        migrations.AddField(
            model_name='recording',
            name='transcript_url',
            field=models.URLField(blank=True, default='', help_text='URL to the VTT transcript file (Zoom cloud URL or S3).', max_length=500),
        ),
    ]
