# Generated by Django 6.0.2 on 2026-03-21 17:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_recording_transcript_text_recording_transcript_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='peer_review_count',
            field=models.IntegerField(default=3, help_text='Number of peers each student must review.'),
        ),
        migrations.AddField(
            model_name='course',
            name='peer_review_criteria',
            field=models.TextField(blank=True, default='', help_text='Markdown rubric/criteria shown to reviewers.'),
        ),
        migrations.AddField(
            model_name='course',
            name='peer_review_criteria_html',
            field=models.TextField(blank=True, default='', help_text='Auto-rendered HTML from peer_review_criteria markdown.'),
        ),
        migrations.AddField(
            model_name='course',
            name='peer_review_deadline_days',
            field=models.IntegerField(default=7, help_text='Days from batch assignment until review deadline.'),
        ),
        migrations.AddField(
            model_name='course',
            name='peer_review_enabled',
            field=models.BooleanField(default=False, help_text='Toggle peer review on/off for this course.'),
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('review_complete', 'Review Complete'), ('certified', 'Certified')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('batch_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('review_deadline', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(blank=True, help_text='Set if student is in a cohort; null for self-paced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_submissions', to='content.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, help_text='Numeric score from 1 to 5.', null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('is_complete', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.projectsubmission')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='content.projectsubmission')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
