# Generated by Django 6.0.2 on 2026-03-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_course_peer_review_count_course_peer_review_criteria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.AddField(
            model_name='article',
            name='data_json',
            field=models.JSONField(blank=True, default=dict, help_text='Stores raw frontmatter data dict for widget rendering.'),
        ),
        migrations.AddField(
            model_name='article',
            name='page_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('learning_path', 'Learning Path')], default='blog', help_text='Determines the outer page template.', max_length=50),
        ),
    ]
