# Generated by Django 6.0.2 on 2026-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_add_page_type_data_json_remove_learningpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='download',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
    ]
