# Generated by Django 6.0.2 on 2026-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_add_slug_to_module_and_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'site config',
                'verbose_name_plural': 'site configs',
            },
        ),
    ]
