# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='testimonials',
            field=models.JSONField(blank=True, default=list, help_text='List of testimonial objects: {quote, name, role?, company?, source_url?}.'),
        ),
    ]
