# Generated by Django 6.0.2 on 2026-03-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_course_testimonials'),
        ('events', '0004_copy_recordings_to_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
