# Generated by Django 6.0.2 on 2026-04-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_delete_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
    ]
