# Generated by Django 6.0.2 on 2026-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_backfill_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='overview',
            field=models.TextField(blank=True, default='', help_text='Markdown overview shown on the module overview page (synced from README.md).'),
        ),
        migrations.AddField(
            model_name='module',
            name='overview_html',
            field=models.TextField(blank=True, default='', help_text='Auto-rendered HTML from overview markdown.'),
        ),
        migrations.AddField(
            model_name='module',
            name='overview_source_path',
            field=models.CharField(blank=True, default=None, help_text='Source repo path of the README.md that backs the overview.', max_length=500, null=True),
        ),
    ]
