# Generated by Django 6.0.2 on 2026-04-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_backfill_module_overview'),
        ('events', '0008_event_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown description shown on the workshop landing page.')),
                ('description_html', models.TextField(blank=True, default='', help_text='Auto-rendered HTML from description markdown.')),
                ('date', models.DateField(help_text='Workshop date (used for ordering and the auto-created Event).')),
                ('instructor_name', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('pages_required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=10, help_text='Minimum tier level required to view workshop pages.')),
                ('recording_required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=20, help_text='Minimum tier level required to watch the recording. Must be >= pages_required_level.')),
                ('code_repo_url', models.URLField(blank=True, default='', help_text='GitHub folder URL with the workshop code.', max_length=500)),
                ('source_repo', models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(blank=True, help_text='Linked Event row that carries the recording metadata.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop', to='events.event')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.UUIDField(blank=True, help_text='Stable UUID. Derived from (repo_name, source_path) when the page markdown has no explicit content_id.', null=True, unique=True)),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True, default='', help_text='Markdown body of the page.')),
                ('body_html', models.TextField(blank=True, default='', help_text='Auto-rendered HTML from body markdown.')),
                ('source_path', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.workshop')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('workshop', 'slug')},
            },
        ),
    ]
