# Generated by Django 6.0.2 on 2026-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_workshop_workshoppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='landing_required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view the workshop landing page. Must be <= pages_required_level.'),
        ),
    ]
