# Generated by Django 6.0.2 on 2026-04-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_workshop_landing_required_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='video_start',
            field=models.CharField(blank=True, default='', help_text='Optional MM:SS or H:MM:SS timestamp marking where this page begins in the linked workshop recording. When set, a "Watch this section" link is shown above the page title for users with recording access.', max_length=10),
        ),
    ]
