# Generated by Django 6.0.2 on 2026-04-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_workshoppage_video_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.SlugField(help_text="Stable, human-readable slug (e.g. 'alexey-grigorev').", max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, default='', help_text='Markdown bio rendered to HTML on save.')),
                ('bio_html', models.TextField(blank=True, default='', editable=False, help_text='Auto-rendered HTML from bio markdown.')),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('links', models.JSONField(blank=True, default=list, help_text='List of {label, url} dicts for social/profile links.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('source_repo', models.CharField(blank=True, default=None, help_text='GitHub repo this instructor was synced from (NULL for backfill).', max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order; 0 is the primary instructor.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.instructor')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('course', 'instructor')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors teaching this course. Order is controlled via the CourseInstructor.position field. The first instructor is mirrored into the legacy instructor_name/instructor_bio fields by the sync pipeline.', related_name='courses', through='content.CourseInstructor', to='content.instructor'),
        ),
        migrations.CreateModel(
            name='WorkshopInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order; 0 is the primary instructor.')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.instructor')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.workshop')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('workshop', 'instructor')},
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors teaching this workshop. Order is controlled via the WorkshopInstructor.position field. The first instructor is mirrored into the legacy instructor_name field by the sync pipeline.', related_name='workshops', through='content.WorkshopInstructor', to='content.instructor'),
        ),
    ]
