# Generated by Django 6.0.2 on 2026-04-28 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_reattach_orphan_course_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('workshop_page', 'Workshop page')], help_text='Discriminator for the kind of content the row points at. Restricted to the values handled by content.services.completion.', max_length=32)),
                ('object_id', models.PositiveIntegerField(help_text='Integer PK of the underlying row (e.g. WorkshopPage.id). Stored as a plain integer rather than via GenericForeignKey so queries remain simple and indexable.')),
                ('completed_at', models.DateTimeField(help_text='When the row was inserted. Always set — presence of the row is the completion signal.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='content_completion_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uniq_user_content_completion')],
            },
        ),
    ]
