# Generated by Django 6.0.2 on 2026-04-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_usercontentcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='interviewcategory',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='interviewcategory',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interviewcategory',
            name='source_repo',
            field=models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='Stable UUID from frontmatter for linking user-generated data.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='source_commit',
            field=models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='source_path',
            field=models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True),
        ),
    ]
