# Generated by Django 6.0.2 on 2026-05-06 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_workshoppage_source_repo_alter_article_source_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='pdf_url',
            field=models.URLField(blank=True, default='', help_text='Optional external URL to a PDF version of the certificate. Surfaced as a Download PDF button on the public cert page.', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
