# Generated by Django 6.0.2 on 2026-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_coursecertificate_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_unit_required_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], help_text="Default access level applied to every unit in this course unless the unit's frontmatter overrides it. When null, units inherit Course.required_level (legacy behaviour). Issue #465.", null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='required_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], help_text='Per-unit override of the course default. When null, the unit inherits Course.default_unit_required_level (or, when that is also null, Course.required_level). Issue #465.', null=True),
        ),
    ]
