# Generated by Django 6.0.2 on 2026-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_backfill_legacy_only_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_bio',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='instructor_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors teaching this course. Order is controlled via the CourseInstructor.position field; the first instructor is the primary instructor shown on listings and cards.', related_name='courses', through='content.CourseInstructor', to='content.instructor'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors teaching this workshop. Order is controlled via the WorkshopInstructor.position field; the first instructor is the primary instructor shown on listings and cards.', related_name='workshops', through='content.WorkshopInstructor', to='content.instructor'),
        ),
    ]
