# Generated by Django 6.0.2 on 2026-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_remove_course_instructor_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='pages_required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=10, help_text='Minimum tier level required to view workshop pages. Accepts LEVEL_REGISTERED (5) so authors can require a free account without requiring payment.'),
        ),
    ]
