# Generated by Django 6.0.2 on 2026-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_alter_workshop_pages_required_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedlink',
            name='category',
            field=models.CharField(choices=[('workshops', 'Workshops'), ('courses', 'Courses'), ('articles', 'Articles'), ('tools', 'Tools'), ('models', 'Models'), ('other', 'Other')], max_length=20),
        ),
    ]
