# Generated by Django 6.0.2 on 2026-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_alter_curatedlink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='required_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], help_text='Per-page override of the workshop default. When null the page inherits Workshop.pages_required_level. Must be >= Workshop.landing_required_level so a page is never more accessible than the workshop landing it lives under. Issue #571.', null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='pages_required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=5, help_text='Minimum tier level required to view workshop pages. Accepts LEVEL_REGISTERED (5) so authors can require a free account without requiring payment. Issue #571 changed the default from LEVEL_BASIC (10) to LEVEL_REGISTERED (5); existing rows keep their stored value.'),
        ),
    ]
