# Generated by Django 6.0.2 on 2026-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_workshoppage_required_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, url, type} dicts. Falls back to linked Event.materials when empty. Authored in workshop.yaml under a top-level `materials:` key. Issue #646: this is the workshop-scoped source of truth, gated against pages_required_level (not recording_required_level).'),
        ),
    ]
