# Generated by Django 6.0.2 on 2026-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_workshop_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the title used to render the current ``auto_banner_url``. Detects title drift between syncs so the banner is regenerated only when the title actually changed.', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #788). Overwritten by the auto-banner pipeline; templates should prefer ``cover_image_url`` and fall back to this.', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the title used to render the current ``auto_banner_url``. Used to detect title drift between syncs.', max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #788). Overwritten by the auto-banner pipeline; templates should prefer ``cover_image_url`` and fall back to this.', max_length=500),
        ),
        migrations.AddField(
            model_name='download',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the title used to render the current ``auto_banner_url``. Used to detect title drift between syncs.', max_length=64),
        ),
        migrations.AddField(
            model_name='download',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #788). Overwritten by the auto-banner pipeline; templates should prefer ``cover_image_url`` and fall back to this.', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the title used to render the current ``auto_banner_url``. Used to detect title drift between syncs.', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #788). Overwritten by the auto-banner pipeline; templates should prefer ``cover_image_url`` and fall back to this.', max_length=500),
        ),
        migrations.AddField(
            model_name='workshop',
            name='auto_banner_title_hash',
            field=models.CharField(blank=True, default='', help_text='sha256 hex digest of the title used to render the current ``auto_banner_url``. Used to detect title drift between syncs.', max_length=64),
        ),
        migrations.AddField(
            model_name='workshop',
            name='auto_banner_url',
            field=models.URLField(blank=True, default='', help_text='Platform-generated OG banner URL (banner-generator Lambda, issue #788). Overwritten by the auto-banner pipeline; templates should prefer ``cover_image_url`` and fall back to this.', max_length=500),
        ),
    ]
