# Generated by Django 6.0.2 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_backfill_workshop_rendered_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
        migrations.AddField(
            model_name='download',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
        migrations.AddField(
            model_name='workshop',
            name='custom_banner_url',
            field=models.URLField(blank=True, default='', help_text='Operator-uploaded custom banner/social image. Survives content re-sync. Wins over the generated banner; loses to a frontmatter cover_image_url.', max_length=500),
        ),
    ]
