# Generated by Django 6.0.2 on 2026-06-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_article_custom_banner_url_course_custom_banner_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who revoked this certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
