# Generated by Django 6.0.2 on 2026-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_backfill_linkified_markdown_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='landing_required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0, help_text='Minimum tier level required to view the workshop landing page. Must be <= pages_required_level.'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='recording_required_level',
            field=models.IntegerField(choices=[(0, 'Open (everyone)'), (5, 'Registered users (any tier)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=20, help_text='Minimum tier level required to watch the recording. Accepts LEVEL_REGISTERED (5) so a free-with-sign-in workshop can gate its recording at the same level as its pages. Must be >= pages_required_level.'),
        ),
    ]
