# Generated by Codex on 2026-07-01

import uuid

from django.db import migrations, models


def backfill_preview_tokens(apps, schema_editor):
    Article = apps.get_model('content', 'Article')
    for article in Article.objects.filter(preview_token__isnull=True):
        article.preview_token = uuid.uuid4()
        article.save(update_fields=['preview_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_alter_workshop_landing_required_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_token',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),
        migrations.RunPython(backfill_preview_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='preview_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
