# Generated by Django 6.0.2 on 2026-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_article_preview_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner-friendly'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', help_text='Visitor-facing prerequisite level from workshop.yaml. Blank means no skill badge/filter match; this is separate from membership access gates.', max_length=20),
        ),
    ]
