# Generated by Django 6.0.2 on 2026-07-10 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_workshop_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_repo', models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable UUID for sync/API identity.', unique=True)),
                ('title', models.CharField(max_length=300)),
                ('public_path', models.CharField(help_text='Canonical public URL path, e.g. /community-story.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('meta_description', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('nav_section', models.CharField(choices=[('none', 'None'), ('about', 'About'), ('community', 'Community'), ('resources', 'Resources')], default='none', max_length=20)),
                ('nav_label', models.CharField(blank=True, default='', max_length=120)),
                ('nav_order', models.IntegerField(default=0)),
                ('preview_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['nav_order', 'title'],
            },
        ),
    ]
