# Generated by Django 6.0.2 on 2026-07-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_reconcile_workshop_preview_tokens'),
        ('events', '0042_event_host_access_version_hostinvitedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_event',
            field=models.ForeignKey(blank=True, help_text='Event that produced this article. Managed by article frontmatter during content sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_articles', to='events.event'),
        ),
    ]
