# Generated by Django 6.0.2 on 2026-07-24 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_article_source_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Platform account that receives in-app notifications for comments on this instructor's content. Operator-set; survives content re-sync.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
