# Generated by Django 6.0.2 on 2026-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, db_default='', default='', help_text='Optional instructor email synced from YAML. Used only as the auto-match key to fill a NULL user link with the verified platform account of the same email; never the notification target itself (that is the user FK).', max_length=254),
        ),
    ]
