# Generated by Django 6.0.2 on 2026-09-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_article_image_manifest'),
        ('events', '0052_eventseries_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='event_series',
            field=models.ForeignKey(blank=True, help_text='Optional recurring meeting series (e.g. office hours) whose occurrences are surfaced to enrolled cohort members on the course page. Deleting the series unlinks the cohort; the cohort itself is preserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='events.eventseries'),
        ),
    ]
