# Generated by Django 6.0.2 on 2026-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_cohort_event_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='external_key',
            field=models.CharField(blank=True, default='', help_text="Maven's cohort identifier string, matched case-insensitively against the Maven webhook's cohort_key at enrollment time (issue #1659). Source-owned from course.yaml's cohorts: list; blank means no external mapping. Unique per course when set.", max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='maven_course_key',
            field=models.CharField(blank=True, default='', help_text="Maven's course identifier string, matched case-insensitively against the Maven webhook's course_key at enrollment time (issue #1659). Source-owned from course.yaml; blank means no Maven course is linked.", max_length=255),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key', ''), _negated=True), fields=('course', 'external_key'), name='unique_cohort_course_external_key'),
        ),
    ]
