# Generated by Django 6.0.2 on 2026-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_cohort_external_key_course_maven_course_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_mode',
            field=models.CharField(choices=[('tier', 'Tier-gated'), ('entitlement', 'Entitlement-only')], db_default='tier', default='tier', help_text="'tier' (default): access follows subscription tier level. 'entitlement': tier comparison is skipped — only a CourseAccess row or staff/superuser opens the course. For programs sold outside the membership plans (issue #1658).", max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='enroll_url',
            field=models.URLField(blank=True, db_default='', default='', help_text="External signup page (e.g. the Maven course page). Only meaningful when access_mode='entitlement'.", max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='program_label',
            field=models.CharField(blank=True, db_default='', default='', help_text="Short external-program name shown on the 'Sold separately' badge and enroll CTA, e.g. 'Maven'. Blank falls back to generic copy.", max_length=100),
        ),
    ]
