# Generated by Django 6.0.2 on 2026-09-16 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_module_slug_unique_per_sibling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_repo', models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True)),
                ('content_id', models.UUIDField(blank=True, help_text="Stable UUID from the owning Unit's frontmatter. NOT globally unique -- see the module docstring: scoped to (cohort, content_id) so multiple cohorts can each carry homework for the same curriculum unit.", null=True)),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('due_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('CL', 'Closed'), ('OP', 'Open'), ('SC', 'Scored')], db_default='OP', default='OP', max_length=2)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='content.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_repo', models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True)),
                ('source_question_id', models.SlugField(blank=True, db_default='', default='', max_length=128)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('MC', 'Multiple choice'), ('FF', 'Free form'), ('FL', 'Free form long'), ('CB', 'Checkboxes')], max_length=2)),
                ('answer_type', models.CharField(blank=True, choices=[('ANY', 'Any'), ('FLT', 'Float'), ('INT', 'Integer'), ('EXS', 'Exact string'), ('CTS', 'Contains string')], db_default='', default='', max_length=3)),
                ('possible_answers', models.TextField(blank=True, db_default='', default='')),
                ('correct_answer', models.TextField(blank=True, db_default='', default='')),
                ('scores_for_correct_answer', models.IntegerField(db_default=1, default=1)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.homework')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_link', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions_score', models.IntegerField(db_default=0, default=0)),
                ('total_score', models.IntegerField(db_default=0, default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='content.cohortenrollment')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(db_default=False, default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('cohort', 'slug'), name='content_homework_cohort_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('cohort', 'content_id'), name='content_homework_cohort_content_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('homework', 'student'), name='content_submission_homework_student_uq'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='content_answer_submission_question_uq'),
        ),
    ]
