# Generated by Django 6.0.2 on 2026-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_homework_question_submission_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_label',
            field=models.CharField(blank=True, db_default='', default='', help_text="Short external-program name shown on the 'External course' badge and enroll CTA, e.g. 'Maven'. Blank falls back to generic copy.", max_length=100),
        ),
    ]
