# Generated by Django 6.0.2 on 2026-09-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_alter_course_program_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_repo', models.CharField(blank=True, default=None, help_text='GitHub repo this content was synced from.', max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, help_text='File path within the source repo.', max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, help_text='Git commit SHA of the last sync.', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('company', models.CharField(max_length=300)),
                ('roles_json', models.JSONField(blank=True, default=list, help_text='Role titles merged from the source job descriptions.')),
                ('process_summary', models.TextField(blank=True, default='')),
                ('steps_json', models.JSONField(blank=True, default=list, help_text='List of step objects with name and optional duration/details.')),
                ('notable', models.TextField(blank=True, default='')),
                ('source_files_json', models.JSONField(blank=True, default=list, help_text='Field-guide job-description filenames this row was merged from.')),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=10, help_text='Minimum tier level required to view the full process detail.')),
            ],
            options={
                'verbose_name_plural': 'interview companies',
                'ordering': ['company'],
            },
        ),
    ]
