# Generated by Django 6.0.2 on 2026-09-20 18:16

import hashlib

import django.db.models.deletion
from django.core.management.color import no_style
from django.db import connection, migrations, models


def _sha1(seed: str) -> str:
    return hashlib.sha1(seed.encode('utf-8')).hexdigest()


def _sha256(seed: str) -> str:
    return hashlib.sha256(seed.encode('utf-8')).hexdigest()


def _provenance(content_id, source_path, source_commit):
    if not content_id and not source_path and not source_commit:
        return {
            'source_content_id': None,
            'source_path': None,
            'source_commit_sha': None,
            'source_checksum': None,
        }
    seed = str(content_id or source_path or source_commit or '')
    commit = source_commit if source_commit and len(str(source_commit)) == 40 else _sha1(seed)
    path = source_path or f'migrated/{seed}'
    return {
        'source_content_id': content_id,
        'source_path': path,
        'source_commit_sha': commit,
        'source_checksum': _sha256(f'{path}:{commit}'),
    }


def copy_curriculum(apps, schema_editor):
    OldCourse = apps.get_model('content', 'Course')
    OldModule = apps.get_model('content', 'Module')
    OldUnit = apps.get_model('content', 'Unit')
    NewCourse = apps.get_model('cb_curriculum', 'Course')
    NewModule = apps.get_model('cb_curriculum', 'Module')
    NewUnit = apps.get_model('cb_curriculum', 'Unit')
    CourseExtension = apps.get_model('content', 'CourseExtension')

    for old in OldCourse.objects.all().iterator():
        prov = _provenance(
            getattr(old, 'content_id', None),
            getattr(old, 'source_path', None),
            getattr(old, 'source_commit', None),
        )
        NewCourse.objects.create(
            id=old.id,
            slug=old.slug,
            title=old.title,
            description=old.description or '',
            description_html=old.description_html or '',
            cover_image_url=old.cover_image_url or '',
            auto_banner_url=old.auto_banner_url or '',
            custom_banner_url=old.custom_banner_url or '',
            required_level=old.required_level,
            default_unit_required_level=old.default_unit_required_level,
            status=old.status,
            discussion_url=old.discussion_url or '',
            tags=old.tags or [],
            testimonials=old.testimonials or [],
            visible=True,
            created_at=old.created_at,
            updated_at=old.updated_at,
            **prov,
        )
        CourseExtension.objects.create(
            course_id=old.id,
            maven_course_key=getattr(old, 'maven_course_key', '') or '',
            source_repo=getattr(old, 'source_repo', '') or '',
            access_mode=getattr(old, 'access_mode', 'tier') or 'tier',
            enroll_url=getattr(old, 'enroll_url', '') or '',
            program_label=getattr(old, 'program_label', '') or '',
            individual_price_eur=old.individual_price_eur,
            stripe_product_id=old.stripe_product_id or '',
            stripe_price_id=old.stripe_price_id or '',
            auto_banner_title_hash=getattr(old, 'auto_banner_title_hash', '') or '',
            peer_review_enabled=old.peer_review_enabled,
            peer_review_count=old.peer_review_count,
            peer_review_deadline_days=old.peer_review_deadline_days,
            peer_review_criteria=old.peer_review_criteria or '',
            peer_review_criteria_html=old.peer_review_criteria_html or '',
        )

    for old in OldModule.objects.order_by('parent_id', 'id').iterator():
        prov = _provenance(
            None,
            getattr(old, 'source_path', None),
            getattr(old, 'source_commit', None),
        )
        NewModule.objects.create(
            id=old.id,
            course_id=old.course_id,
            parent_id=old.parent_id,
            slug=old.slug or '',
            title=old.title,
            sort_order=old.sort_order,
            overview=old.overview or '',
            overview_html=old.overview_html or '',
            is_bonus=getattr(old, 'is_bonus', False),
            available_after_days=getattr(old, 'available_after_days', None),
            **prov,
        )

    for old in OldUnit.objects.order_by('id').iterator():
        prov = _provenance(
            getattr(old, 'content_id', None),
            getattr(old, 'source_path', None),
            getattr(old, 'source_commit', None),
        )
        NewUnit.objects.create(
            id=old.id,
            module_id=old.module_id,
            slug=old.slug or '',
            title=old.title,
            sort_order=old.sort_order,
            kind=getattr(old, 'kind', 'lesson') or 'lesson',
            session_position=getattr(old, 'session_position', None),
            is_bonus=getattr(old, 'is_bonus', False),
            video_url=old.video_url or '',
            body=old.body or '',
            body_html=old.body_html or '',
            homework=old.homework or '',
            homework_html=old.homework_html or '',
            timestamps=old.timestamps or [],
            is_preview=old.is_preview,
            required_level=old.required_level,
            available_after_days=old.available_after_days,
            content_hash=old.content_hash or '',
            **prov,
        )

    sequence_sql = connection.ops.sequence_reset_sql(
        no_style(), [NewCourse, NewModule, NewUnit],
    )
    with connection.cursor() as cursor:
        for sql in sequence_sql:
            cursor.execute(sql)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0003_unit_body_html_source'),
        ('content', '0069_interviewcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maven_course_key', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('source_repo', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('access_mode', models.CharField(choices=[('tier', 'Tier-gated'), ('entitlement', 'Entitlement-only')], db_default='tier', default='tier', max_length=20)),
                ('enroll_url', models.URLField(blank=True, db_default='', default='', max_length=500)),
                ('program_label', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('individual_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('auto_banner_title_hash', models.CharField(blank=True, default='', max_length=64)),
                ('peer_review_enabled', models.BooleanField(default=False)),
                ('peer_review_count', models.IntegerField(default=3)),
                ('peer_review_deadline_days', models.IntegerField(default=7)),
                ('peer_review_criteria', models.TextField(blank=True, default='')),
                ('peer_review_criteria_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='courseextension',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aisl_extension', to='cb_curriculum.course'),
        ),
        migrations.RunPython(copy_curriculum, noop),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisl_cohorts', to='cb_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='coursecertificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cb_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cb_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_access', to='cb_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='cb_curriculum.course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisl_instructor_links', to='cb_curriculum.course'),
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='module_top_level_slug_unique_per_course',
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='module_submodule_slug_unique_per_parent',
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisl_progress', to='cb_curriculum.unit'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
