# Generated by Django 6.0.2 on 2026-09-21 11:17

import django.db.models.deletion
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0003_unit_body_html_source'),
        ('content', '0070_curriculum_package_cutover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsubmission',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('submission_due_at', models.DateTimeField()),
                ('review_due_at', models.DateTimeField()),
                ('peer_review_count', models.PositiveSmallIntegerField(blank=True, help_text='Reviews per learner; blank uses the course setting.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_projects', to='content.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_projects', to='cb_curriculum.course')),
            ],
            options={
                'ordering': ['submission_due_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='course_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.courseproject'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('course_project__isnull', True)), fields=('user', 'course'), name='legacy_submission_user_course_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'course_project'), name='submission_user_course_project_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseproject',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='course_project_course_slug_unique'),
        ),
    ]
