# Generated by Django 6.0.2 on 2026-09-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0003_unit_body_html_source'),
        ('content', '0071_alter_projectsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproject',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_projects', to='cb_curriculum.module'),
        ),
    ]
