# Generated by Django 6.0.2 on 2026-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_courseextension_reader_navigation_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseextension',
            name='reader_navigation_scope',
            field=models.CharField(choices=[('course', 'Entire course'), ('module', 'Current module'), ('submodule', 'Current module (legacy)')], db_default='course', default='course', max_length=20),
        ),
    ]
