# Generated by Django 6.0.2 on 2026-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_homework_stepper_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
