# Generated by Django 6.0.2 on 2026-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_alter_homework_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_url_field',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='learning_in_public_cap',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='homework',
            name='time_spent_homework_field',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='time_spent_lectures_field',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='learning_in_public_links',
            field=models.JSONField(blank=True, default=list, null=True, help_text='Optional public links submitted with this homework.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent_homework',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent_lectures',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
