# Generated by Django 6.0.2 on 2026-09-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0005_module_unit_source_sibling_position'),
        ('content', '0080_rename_user_submission_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='curriculum_cohort',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aisl_cohort', to='cb_curriculum.cohort'),
        ),
    ]
