# Generated by Django 6.0.2 on 2026-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_backfill_cohort_curriculum_mirrors'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkStepThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_content_id', models.UUIDField(db_index=True, help_text='Stable content UUID of the curriculum unit that owns the homework.')),
                ('step_slug', models.CharField(help_text="Public step slug in the canonical step URL: an authored question source_question_id, 'learning-in-public', or 'review'.", max_length=128)),
                ('content_id', models.UUIDField(help_text='Deterministic thread UUID for the (unit identity, step slug) pair; the value the browser comments API mounts for this step page.', unique=True)),
            ],
            options={
                'ordering': ['unit_content_id', 'step_slug'],
                'constraints': [models.UniqueConstraint(fields=('unit_content_id', 'step_slug'), name='content_homework_step_thread_unit_slug_uq')],
            },
        ),
    ]
