# Generated by Django 6.0.2 on 2026-10-08 23:02

from django.db import migrations, models

# Steps that lost their live Q&A thread in issue #1925.
RETIRED_THREAD_STEPS = ('review', 'learning-in-public')


def move_retired_step_comments_to_unit_thread(apps, schema_editor):
    """Move ``review`` / ``learning-in-public`` step comments to the unit.

    Issue #1925: those two stepper pages no longer mount a live Q&A thread.
    Their comments are re-pointed at the owning unit's own ``content_id``,
    which Review & submit shows read-only as ``Earlier homework discussion``.

    - Only ``Comment.content_id`` changes. Replies share their parent's
      ``content_id`` so they move with it; votes are FK-linked to the
      comment and need nothing. No row is deleted, and queryset ``update``
      leaves ``created_at`` / ``updated_at`` / ``edited_at`` / ``hidden_at``
      untouched.
    - Idempotent: once moved, no comment carries a retired step thread UUID,
      so a second run updates zero rows.
    - Defensive: a row with a missing ``unit_content_id``, or one whose
      thread UUID equals its unit UUID, is skipped instead of raising, so
      unexpected production data can never fail ``migrate``. Comments on a
      skipped row stay where they are (still listed by the operator API).
    - The ``HomeworkStepThread`` rows themselves are kept so the old UUIDs
      remain registered owners.
    """
    Comment = apps.get_model('comments', 'Comment')
    HomeworkStepThread = apps.get_model('content', 'HomeworkStepThread')
    threads = (
        HomeworkStepThread.objects
        .filter(step_slug__in=RETIRED_THREAD_STEPS)
        .values_list('content_id', 'unit_content_id')
    )
    for thread_content_id, unit_content_id in threads.iterator():
        if not thread_content_id or not unit_content_id:
            continue
        if thread_content_id == unit_content_id:
            continue
        Comment.objects.filter(content_id=thread_content_id).update(
            content_id=unit_content_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0085_normalize_homework_draft_hours'),
        ('comments', '0003_comment_edited_at_comment_hidden_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstepthread',
            name='step_slug',
            field=models.CharField(help_text="Public step slug in the canonical step URL: 'intro' or an authored question source_question_id ('learning-in-public' and 'review' rows predate issue #1925 and are kept).", max_length=128),
        ),
        # Reverse is a no-op: the original step a moved comment came from is
        # not recorded, and leaving comments on the unit thread loses nothing.
        migrations.RunPython(
            move_retired_step_comments_to_unit_thread,
            migrations.RunPython.noop,
        ),
    ]
