"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
import warnings
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _csv_env(name, default='', *, env=None, allow_empty=False):
    env = os.environ if env is None else env
    values = [
        value.strip()
        for value in env.get(name, default).split(',')
        if value.strip()
    ]
    if values or allow_empty:
        return values
    return [value.strip() for value in default.split(',') if value.strip()]


_TRUTHY_BOOL_VALUES = frozenset({'1', 'true', 'yes'})


def _bool_env(name, *, default, env=None):
    """Parse a boolean env var.

    Truthy values (case-insensitive): ``1``, ``true``, ``yes``.
    Anything else (including ``0``, ``false``, ``no``, empty string) is
    falsy. Missing / unset uses ``default``.
    """
    env = os.environ if env is None else env
    if name not in env:
        return default
    return env[name].strip().lower() in _TRUTHY_BOOL_VALUES


# Insecure dev-only fallback used when DEBUG=True and SECRET_KEY is unset.
# Must NEVER be accepted in production: _resolve_secret_key rejects it
# explicitly if DEBUG=False, even if it sneaks in via the environment
# (e.g. someone copy-pasted from local).
DEV_FALLBACK_SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'


def _resolve_secret_key(*, debug, env=None):
    """Resolve Django's ``SECRET_KEY`` from the environment.

    Production (``debug=False``): the env var ``SECRET_KEY`` MUST be set
    to a non-empty value that is not the dev fallback. Otherwise we raise
    ``ImproperlyConfigured`` at import time so the deploy fails fast
    rather than silently signing cookies / JWTs with a known key.

    Development (``debug=True``): if ``SECRET_KEY`` is unset or empty,
    fall back to ``DEV_FALLBACK_SECRET_KEY`` and emit a
    ``RuntimeWarning`` so the developer notices. If the env var is set,
    use it (no warning).
    """
    env = os.environ if env is None else env
    value = env.get('SECRET_KEY', '').strip()
    if not value or value == DEV_FALLBACK_SECRET_KEY:
        if debug:
            warnings.warn(
                'SECRET_KEY is not set; using insecure dev-only default. '
                'Set SECRET_KEY in your .env file for any non-trivial '
                'work. Generate one with: python -c "from '
                'django.core.management.utils import '
                'get_random_secret_key; print(get_random_secret_key())"',
                RuntimeWarning,
                stacklevel=2,
            )
            return DEV_FALLBACK_SECRET_KEY
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable must be set when DEBUG=False. '
            'In production this is injected from AWS Secrets Manager '
            '(ai-shipping-labs/django-secret-key). The in-tree dev '
            'fallback is rejected on purpose and must not be used in '
            'production.'
        )
    return value


DEBUG = _bool_env('DEBUG', default=True)

SECRET_KEY = _resolve_secret_key(debug=DEBUG)


def _security_setting_values(*, debug):
    return {
        'SESSION_COOKIE_SECURE': not debug,
        'CSRF_COOKIE_SECURE': not debug,
        'SECURE_HSTS_SECONDS': 3600 if not debug else 0,
    }

# AWS ALB terminates TLS and forwards X-Forwarded-Proto. Trust it
# unconditionally: local dev never receives this header from an external
# attacker (it's localhost) so the gate isn't worth losing dev DEBUG=True
# coverage. Without this, the host-mismatch banner false-fires on dev.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

globals().update(_security_setting_values(debug=DEBUG))

ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')

CSRF_TRUSTED_ORIGINS = _csv_env('CSRF_TRUSTED_ORIGINS', '', allow_empty=True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.forms',
    # Third-party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.slack',
    'django_q',
    # Project apps
    'accounts',
    'payments',
    'content',
    'events',
    'integrations',
    'email_app',
    'voting',
    'jobs',
    'community',
    'notifications',
    'studio',
    'comments',
    'analytics',
]

MIDDLEWARE = [
    # Must run before SecurityMiddleware/CommonMiddleware so that ALB
    # health checks (which use the container's VPC IP as Host) don't trip
    # ALLOWED_HOSTS validation. See website/middleware.py.
    'website.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves /static/* from STATIC_ROOT in production (DEBUG=False).
    # Must come right after SecurityMiddleware so static responses still
    # get security headers but skip session / auth / CSRF processing.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'integrations.middleware.RemoveTrailingSlashMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'analytics.middleware.CampaignTrackingMiddleware',
    'integrations.middleware.RedirectMiddleware',
    # Mark /studio/* and /accounts/* responses uncacheable. Defensive
    # protection so authenticated HTML (which can carry per-user flash
    # messages and CSRF tokens) never sits in a browser back-forward
    # cache, service worker, or future CDN. See issue #347.
    'studio.middleware.StudioNoStoreMiddleware',
]

APPEND_SLASH = True

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.site_context',
                'website.context_processors.impersonation_context',
                'website.context_processors.announcement_banner_context',
                'website.context_processors.studio_env_mismatch_context',
            ],
        },
    },
]

# Use the project's TEMPLATES setting for form widget rendering so that
# custom widget templates in templates/ are found by the form renderer.
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'website.wsgi.application'


# Database
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    ),
}
# SQLite concurrency tuning. Without these PRAGMAs, two writers racing the
# same db.sqlite3 file (e.g. Q_WORKERS>1 syncing 6 sources in parallel)
# surface as "database is locked". The Postgres branch is left untouched.
#
# - journal_mode=WAL: writers don't block readers, and one writer can run
#   while others queue on the busy_timeout instead of failing immediately.
# - busy_timeout=30000: when a writer hits the lock, wait up to 30 s for
#   it to clear instead of raising OperationalError.
# - synchronous=NORMAL: WAL's recommended fsync level. FULL is overkill
#   for a dev database and noticeably slower.
# - transaction_mode=IMMEDIATE (Django 5.1+): start write transactions in
#   IMMEDIATE mode so we acquire the write lock up front. Without this,
#   two transactions that both START as readers (DEFERRED, the default)
#   and later try to UPGRADE to writers deadlock — SQLite resolves this
#   by killing one with SQLITE_BUSY, which busy_timeout cannot retry.
# - timeout=30: connect-level fallback for the same lock acquisition;
#   retained for callers that bypass the busy_timeout PRAGMA.
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {}).update({
        'timeout': 30,
        'init_command': (
            'PRAGMA journal_mode=WAL;'
            'PRAGMA busy_timeout=30000;'
            'PRAGMA synchronous=NORMAL;'
        ),
        'transaction_mode': 'IMMEDIATE',
    })


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


def _staticfiles_storage_backend(*, debug):
    if debug:
        return 'django.contrib.staticfiles.storage.StaticFilesStorage'
    return 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# WhiteNoise: serve hashed, compressed static files in production. The
# Dockerfile runs `collectstatic --noinput` so STATIC_ROOT is populated
# at build time. Manifest storage adds content-hash suffixes so static
# URLs can be cached far-future without staleness. In DEBUG/test runs,
# keep static URLs unhashed so Django's staticfiles finders can serve
# both project-level assets and app-provided assets such as Django admin
# without requiring a prior collectstatic.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': _staticfiles_storage_backend(debug=DEBUG),
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Analytics / UTM tracking
# Salt for SHA-256-hashing client IPs in CampaignVisit.ip_hash. If unset
# (empty string), `ip_hash` is left blank — we never store raw IPs.
IP_HASH_SALT = os.environ.get('IP_HASH_SALT', '')
# Optional: scope analytics cookies (aslab_aid, aslab_ft) to a specific
# domain. Defaults to SESSION_COOKIE_DOMAIN (Django's session cookie scope).
ANALYTICS_COOKIE_DOMAIN = os.environ.get('ANALYTICS_COOKIE_DOMAIN', '') or None

# Site configuration
VERSION = os.getenv("VERSION", "N/A")
SITE_NAME = 'AI Shipping Labs'
# Canonical base URL used by every URL-generating call site
# (unsubscribe links, calendar invites, password resets, OAuth redirect
# URIs, share URLs, OG / canonical meta tags, Slack announcement links,
# UTM campaign destinations). Resolution order: IntegrationSetting row
# in the DB (Studio > Settings > Site) > SITE_BASE_URL env var > literal
# default. The literal default is a safety net so settings always
# exposes the attribute; production deploys MUST override it. The
# Studio host-mismatch banner (see
# website.context_processors.studio_env_mismatch_context) warns when
# the configured value disagrees with the request host.
#
# get_config() guards against the chicken-and-egg of being called while
# settings.py is still loading (settings.configured == False at this
# point, so the django-conf branch is skipped and we fall through to
# env / default — DB rows are picked up on the next access after Django
# finishes booting).
from integrations.config import get_config  # noqa: E402

SITE_BASE_URL = get_config(
    'SITE_BASE_URL',
    os.environ.get('SITE_BASE_URL', 'https://aishippinglabs.com'),
)
SITE_DESCRIPTION = 'An invite-only community for action-oriented builders who want to turn AI ideas into real projects.'

# Stripe payment links
STRIPE_PAYMENT_LINKS = {
    'basic': {
        'monthly': 'https://buy.stripe.com/aFa6oGdrN8XT8oFcoJgbm0c',
        'annual': 'https://buy.stripe.com/eVq7sK5Zl2zveN388tgbm0b',
    },
    'main': {
        'monthly': 'https://buy.stripe.com/7sYbJ0afBb61gVbfAVgbm0a',
        'annual': 'https://buy.stripe.com/3cI00ifzV6PL7kB0G1gbm07',
    },
    'premium': {
        'monthly': 'https://buy.stripe.com/7sY3cudrNeid6gx9cxgbm09',
        'annual': 'https://buy.stripe.com/cNi9AS2N96PLbARagBgbm08',
    },
}
STRIPE_CUSTOMER_PORTAL_URL = 'https://billing.stripe.com/p/login/14A4gy0F1b610WdewRgbm00'

# Stripe API keys (set via environment variables in production)
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_CHECKOUT_ENABLED = os.getenv('STRIPE_CHECKOUT_ENABLED', 'false').lower() == 'true'

# Zoom API credentials (set via environment variables in production)
ZOOM_CLIENT_ID = os.environ.get('ZOOM_CLIENT_ID', '')
ZOOM_CLIENT_SECRET = os.environ.get('ZOOM_CLIENT_SECRET', '')
ZOOM_ACCOUNT_ID = os.environ.get('ZOOM_ACCOUNT_ID', '')
ZOOM_WEBHOOK_SECRET_TOKEN = os.environ.get('ZOOM_WEBHOOK_SECRET_TOKEN', '')

# Amazon SES configuration (set via environment variables in production)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_SES_REGION = os.environ.get('AWS_SES_REGION', 'us-east-1')

# S3 configuration for recording uploads
AWS_S3_RECORDINGS_BUCKET = os.environ.get('AWS_S3_RECORDINGS_BUCKET', '')
AWS_S3_RECORDINGS_REGION = os.environ.get('AWS_S3_RECORDINGS_REGION', 'eu-central-1')

# S3 configuration for content images (synced from GitHub repos)
AWS_S3_CONTENT_BUCKET = os.environ.get('AWS_S3_CONTENT_BUCKET', '')
AWS_S3_CONTENT_REGION = os.environ.get('AWS_S3_CONTENT_REGION', 'eu-west-1')

# YouTube Data API v3 credentials (OAuth2 with refresh token)
YOUTUBE_CLIENT_ID = os.environ.get('YOUTUBE_CLIENT_ID', '')
YOUTUBE_CLIENT_SECRET = os.environ.get('YOUTUBE_CLIENT_SECRET', '')
YOUTUBE_REFRESH_TOKEN = os.environ.get('YOUTUBE_REFRESH_TOKEN', '')

SES_FROM_EMAIL = os.environ.get('SES_FROM_EMAIL', 'community@aishippinglabs.com')
SES_WEBHOOK_VALIDATION_ENABLED = os.environ.get('SES_WEBHOOK_VALIDATION_ENABLED', '') == 'true'

# Email campaign chunking: number of recipients per chunked send_campaign_batch task.
# At ~0.05s/email + SES network latency, a 200-recipient batch finishes in roughly
# 10-30s, well under the 300s Q_CLUSTER worker timeout, while keeping the queue
# row count manageable (5000 recipients => 25 chunks).
EMAIL_BATCH_SIZE = int(os.environ.get('EMAIL_BATCH_SIZE', 200))

# Content directory (markdown files from reference)
CONTENT_DIR = BASE_DIR / 'reference' / 'content'

# GitHub App authentication for private repo access
GITHUB_APP_ID = os.environ.get('GITHUB_APP_ID', '')
GITHUB_APP_INSTALLATION_ID = os.environ.get('GITHUB_APP_INSTALLATION_ID', '')

# Private key: local file → env var → Secrets Manager
_github_key_path = os.environ.get('GITHUB_APP_PRIVATE_KEY_FILE', '')
if _github_key_path and os.path.isfile(_github_key_path):
    with open(_github_key_path) as f:
        GITHUB_APP_PRIVATE_KEY = f.read()
else:
    GITHUB_APP_PRIVATE_KEY = os.environ.get('GITHUB_APP_PRIVATE_KEY', '')


def _fetch_secret(secret_id, region='eu-west-1'):
    """Fetch a secret from AWS Secrets Manager."""
    import logging
    logger = logging.getLogger(__name__)
    try:
        import boto3
        client = boto3.client('secretsmanager', region_name=region)
        return client.get_secret_value(SecretId=secret_id)['SecretString']
    except Exception as e:
        logger.warning('Failed to fetch secret %s: %s', secret_id, e)
        return ''


if not GITHUB_APP_PRIVATE_KEY:
    GITHUB_APP_PRIVATE_KEY = _fetch_secret('ai-shipping-labs/github-app-private-key')

# CDN base URL for content images uploaded during sync
CONTENT_CDN_BASE = os.environ.get('CONTENT_CDN_BASE', '/static/content-images')

# Sync watchdog thresholds (issue #274). The dashboard runs an inline
# watchdog query at the top of every render to flip stuck rows to ``failed``:
#  - SYNC_QUEUED_THRESHOLD_MINUTES: a SyncLog stuck in ``queued`` longer than
#    this means the worker never picked it up. Should normally be seconds.
#  - SYNC_RUNNING_THRESHOLD_MINUTES: a SyncLog stuck in ``running`` longer
#    than this means the worker died mid-sync. Real syncs can take a few
#    minutes, so the default is generous.
SYNC_QUEUED_THRESHOLD_MINUTES = int(
    os.environ.get('SYNC_QUEUED_THRESHOLD_MINUTES', 10),
)
SYNC_RUNNING_THRESHOLD_MINUTES = int(
    os.environ.get('SYNC_RUNNING_THRESHOLD_MINUTES', 30),
)

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Django sites framework (required by allauth)
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none'  # OAuth providers already verify email
ACCOUNT_SIGNUP_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGIN_API_SLOW_MS = float(os.environ.get('LOGIN_API_SLOW_MS', 750))

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# OAuth provider configuration (credentials managed via Django admin > Social applications)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'SCOPE': ['user:email'],
    },
    'slack': {
        'SCOPE': ['openid', 'profile', 'email'],
    },
}

# Slack community integration (set via environment variables in production)
# SLACK_ENABLED must be explicitly set to 'true' — off by default to prevent
# dev/test environments from posting to real Slack channels.
import sys

TESTING = 'test' in sys.argv
SLACK_ENABLED = (
    not TESTING
    and os.environ.get('SLACK_ENABLED', 'false').lower() == 'true'
)
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN', '') if SLACK_ENABLED else ''
SLACK_ENVIRONMENT = os.environ.get('SLACK_ENVIRONMENT', 'development').lower()
SLACK_COMMUNITY_CHANNEL_IDS = [
    cid.strip()
    for cid in os.environ.get('SLACK_COMMUNITY_CHANNEL_IDS', '').split(',')
    if cid.strip()
] if SLACK_ENABLED else []
SLACK_DEV_COMMUNITY_CHANNEL_IDS = [
    cid.strip()
    for cid in os.environ.get('SLACK_DEV_COMMUNITY_CHANNEL_IDS', '').split(',')
    if cid.strip()
] if SLACK_ENABLED else []
SLACK_TEST_COMMUNITY_CHANNEL_IDS = [
    cid.strip()
    for cid in os.environ.get('SLACK_TEST_COMMUNITY_CHANNEL_IDS', '').split(',')
    if cid.strip()
] if SLACK_ENABLED else []
SLACK_INVITE_URL = os.environ.get('SLACK_INVITE_URL', '')
SLACK_ANNOUNCEMENTS_CHANNEL_ID = os.environ.get('SLACK_ANNOUNCEMENTS_CHANNEL_ID', '') if SLACK_ENABLED else ''
SLACK_DEV_ANNOUNCEMENTS_CHANNEL_ID = os.environ.get('SLACK_DEV_ANNOUNCEMENTS_CHANNEL_ID', '') if SLACK_ENABLED else ''
SLACK_TEST_ANNOUNCEMENTS_CHANNEL_ID = os.environ.get('SLACK_TEST_ANNOUNCEMENTS_CHANNEL_ID', '') if SLACK_ENABLED else ''

# Cache configuration
# django-q writes cluster heartbeats (used by the /studio/worker/ dashboard)
# to Django's cache backend. The default LocMemCache is per-process, so the
# qcluster's heartbeats are invisible to the gunicorn / runserver process —
# the dashboard always reports "Worker NOT running" even when the cluster is
# healthy. We use a dedicated `django_q` cache that is shared across every
# process that can reach the application database:
#
# - Tests: LocMemCache. Single-process, fast, isolated per run. The
#   cross-process behaviour is exercised explicitly in
#   `studio/tests/test_worker_health_cache.py`.
# - Local dev / production: DatabaseCache. Heartbeats live in a single
#   `django_q_cache` table in the application DB, so they are visible to
#   every process / container that talks to the same DB — works on a
#   single host (SQLite, `make dev`) and across containers in ECS where
#   web and worker are separate tasks sharing only the database. No
#   shared filesystem required, no extra infra (Redis, EFS) needed.
#
# The cache table must exist before django-q can write to it — run
# `python manage.py createcachetable django_q_cache` after `migrate`.
# It is idempotent and wired into both `scripts/setup.sh` (local) and
# `entrypoint.sh` (every container start in deploy).
#
# `Q_CLUSTER['cache'] = 'django_q'` (below) tells django-q to use this
# named cache rather than `default`, so the application's own cache usage
# (if any) doesn't share a namespace with cluster heartbeats.
if TESTING:
    _django_q_cache = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'django-q-test',
    }
else:
    _django_q_cache = {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_q_cache',
    }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'django_q': _django_q_cache,
}

# Django-Q2 task queue configuration
# Default workers=1 on SQLite — concurrent writers serialise on the file lock
# and surface as "database is locked" during bulk syncs. Override with
# Q_WORKERS=N on Postgres deployments.
if 'sqlite' in DATABASES['default']['ENGINE']:
    _default_q_workers = 1
else:
    _default_q_workers = 2
Q_CLUSTER = {
    'name': 'ai-shipping-labs',
    'workers': int(os.environ.get('Q_WORKERS', _default_q_workers)),
    'timeout': 300,           # Task timeout in seconds (5 min)
    'retry': 360,             # Retry timeout in seconds (6 min, must be > timeout)
    'max_attempts': 3,        # Default max attempts (1 initial + 2 retries)
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',         # Use the default database as broker
    'cache': 'django_q',      # Named cache for cluster heartbeats (cross-process)
    'save_limit': 250,        # Keep last 250 task results
    # Heartbeats are written by the guard loop and stored in the cache
    # with a hardcoded 3 s TTL (see django_q.status.Stat.save). Keep
    # guard_cycle <= 2 s so writes always overlap the TTL — otherwise
    # the worker dashboard flickers between alive and dead between
    # cycles.
    'guard_cycle': 2,
    'poll': 5,                # Worker polls every 5 seconds
    'catch_up': False,        # Don't catch up on missed schedules
    'sync': os.environ.get('Q_SYNC', '') == 'true',  # Sync mode for testing
}

IMPORT_WELCOME_EMAILS_PER_HOUR = int(os.environ.get('IMPORT_WELCOME_EMAILS_PER_HOUR', '50'))
