"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-hlmbk@+b=_0t_+&z8rrhf%+3f&_zldtutm8(n3hlk6f+=oi##4'

DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.forms',
    # Third-party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.slack',
    'django_q',
    # Project apps
    'accounts',
    'payments',
    'content',
    'events',
    'integrations',
    'email_app',
    'voting',
    'jobs',
    'community',
    'notifications',
    'studio',
    'comments',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'integrations.middleware.RemoveTrailingSlashMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'analytics.middleware.CampaignTrackingMiddleware',
    'integrations.middleware.RedirectMiddleware',
]

APPEND_SLASH = True

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.site_context',
                'website.context_processors.impersonation_context',
                'website.context_processors.announcement_banner_context',
            ],
        },
    },
]

# Use the project's TEMPLATES setting for form widget rendering so that
# custom widget templates in templates/ are found by the form renderer.
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'website.wsgi.application'


# Database
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    ),
}
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {})['timeout'] = 30


# Enable WAL mode for SQLite to improve concurrency (needed for Playwright E2E
# tests where the dev server and test process access the same database).
def _enable_wal_mode(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA busy_timeout=30000;')


from django.db.backends.signals import connection_created  # noqa: E402

connection_created.connect(_enable_wal_mode)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Analytics / UTM tracking
# Salt for SHA-256-hashing client IPs in CampaignVisit.ip_hash. If unset
# (empty string), `ip_hash` is left blank — we never store raw IPs.
IP_HASH_SALT = os.environ.get('IP_HASH_SALT', '')
# Optional: scope analytics cookies (aslab_aid, aslab_ft) to a specific
# domain. Defaults to SESSION_COOKIE_DOMAIN (Django's session cookie scope).
ANALYTICS_COOKIE_DOMAIN = os.environ.get('ANALYTICS_COOKIE_DOMAIN', '') or None

# Site configuration
VERSION = os.getenv("VERSION", "N/A")
SITE_NAME = 'AI Shipping Labs'
SITE_URL = 'https://aishippinglabs.com'
# Base URL used by UTM link generation when destinations are paths
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'https://aishippinglabs.com')
SITE_DESCRIPTION = 'An invite-only community for action-oriented builders who want to turn AI ideas into real projects.'

# Stripe payment links
STRIPE_PAYMENT_LINKS = {
    'basic': {
        'monthly': 'https://buy.stripe.com/14A4gy0F1b610WdewRgbm00',
        'annual': 'https://buy.stripe.com/3cIcN44VhfmhbARagBgbm01',
    },
    'main': {
        'monthly': 'https://buy.stripe.com/dRm8wOgDZca5bARbkFgbm02',
        'annual': 'https://buy.stripe.com/3cI3cu0F12zvcEV4Whgbm06',
    },
    'premium': {
        'monthly': 'https://buy.stripe.com/dRm3cu4Vh7TPawN3Sdgbm04',
        'annual': 'https://buy.stripe.com/4gM9AS1J50rneN360lgbm05',
    },
}
STRIPE_CUSTOMER_PORTAL_URL = 'https://billing.stripe.com/p/login/14A4gy0F1b610WdewRgbm00'

# Stripe API keys (set via environment variables in production)
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_CHECKOUT_ENABLED = os.getenv('STRIPE_CHECKOUT_ENABLED', 'false').lower() == 'true'

# Zoom API credentials (set via environment variables in production)
ZOOM_CLIENT_ID = os.environ.get('ZOOM_CLIENT_ID', '')
ZOOM_CLIENT_SECRET = os.environ.get('ZOOM_CLIENT_SECRET', '')
ZOOM_ACCOUNT_ID = os.environ.get('ZOOM_ACCOUNT_ID', '')
ZOOM_WEBHOOK_SECRET_TOKEN = os.environ.get('ZOOM_WEBHOOK_SECRET_TOKEN', '')

# Amazon SES configuration (set via environment variables in production)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_SES_REGION = os.environ.get('AWS_SES_REGION', 'us-east-1')

# S3 configuration for recording uploads
AWS_S3_RECORDINGS_BUCKET = os.environ.get('AWS_S3_RECORDINGS_BUCKET', '')
AWS_S3_RECORDINGS_REGION = os.environ.get('AWS_S3_RECORDINGS_REGION', 'eu-central-1')

# S3 configuration for content images (synced from GitHub repos)
AWS_S3_CONTENT_BUCKET = os.environ.get('AWS_S3_CONTENT_BUCKET', '')
AWS_S3_CONTENT_REGION = os.environ.get('AWS_S3_CONTENT_REGION', 'eu-west-1')

# YouTube Data API v3 credentials (OAuth2 with refresh token)
YOUTUBE_CLIENT_ID = os.environ.get('YOUTUBE_CLIENT_ID', '')
YOUTUBE_CLIENT_SECRET = os.environ.get('YOUTUBE_CLIENT_SECRET', '')
YOUTUBE_REFRESH_TOKEN = os.environ.get('YOUTUBE_REFRESH_TOKEN', '')

SES_FROM_EMAIL = os.environ.get('SES_FROM_EMAIL', 'community@aishippinglabs.com')
SES_WEBHOOK_VALIDATION_ENABLED = os.environ.get('SES_WEBHOOK_VALIDATION_ENABLED', '') == 'true'

# Email campaign chunking: number of recipients per chunked send_campaign_batch task.
# At ~0.05s/email + SES network latency, a 200-recipient batch finishes in roughly
# 10-30s, well under the 300s Q_CLUSTER worker timeout, while keeping the queue
# row count manageable (5000 recipients => 25 chunks).
EMAIL_BATCH_SIZE = int(os.environ.get('EMAIL_BATCH_SIZE', 200))

# Content directory (markdown files from reference)
CONTENT_DIR = BASE_DIR / 'reference' / 'content'

# GitHub App authentication for private repo access
GITHUB_APP_ID = os.environ.get('GITHUB_APP_ID', '')
GITHUB_APP_INSTALLATION_ID = os.environ.get('GITHUB_APP_INSTALLATION_ID', '')

# Private key: local file → env var → Secrets Manager
_github_key_path = os.environ.get('GITHUB_APP_PRIVATE_KEY_FILE', '')
if _github_key_path and os.path.isfile(_github_key_path):
    with open(_github_key_path) as f:
        GITHUB_APP_PRIVATE_KEY = f.read()
else:
    GITHUB_APP_PRIVATE_KEY = os.environ.get('GITHUB_APP_PRIVATE_KEY', '')


def _fetch_secret(secret_id, region='eu-west-1'):
    """Fetch a secret from AWS Secrets Manager."""
    import logging
    logger = logging.getLogger(__name__)
    try:
        import boto3
        client = boto3.client('secretsmanager', region_name=region)
        return client.get_secret_value(SecretId=secret_id)['SecretString']
    except Exception as e:
        logger.warning('Failed to fetch secret %s: %s', secret_id, e)
        return ''


if not GITHUB_APP_PRIVATE_KEY:
    GITHUB_APP_PRIVATE_KEY = _fetch_secret('ai-shipping-labs/github-app-private-key')

# CDN base URL for content images uploaded during sync
CONTENT_CDN_BASE = os.environ.get('CONTENT_CDN_BASE', '/static/content-images')

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Django sites framework (required by allauth)
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none'  # OAuth providers already verify email
ACCOUNT_SIGNUP_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# OAuth provider configuration (credentials managed via Django admin > Social applications)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'SCOPE': ['user:email'],
    },
    'slack': {
        'SCOPE': ['openid', 'profile', 'email'],
    },
}

# Slack community integration (set via environment variables in production)
# SLACK_ENABLED must be explicitly set to 'true' — off by default to prevent
# dev/test environments from posting to real Slack channels.
import sys

TESTING = 'test' in sys.argv
SLACK_ENABLED = (
    not TESTING
    and os.environ.get('SLACK_ENABLED', 'false').lower() == 'true'
)
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN', '') if SLACK_ENABLED else ''
SLACK_COMMUNITY_CHANNEL_IDS = [
    cid.strip()
    for cid in os.environ.get('SLACK_COMMUNITY_CHANNEL_IDS', '').split(',')
    if cid.strip()
] if SLACK_ENABLED else []
SLACK_INVITE_URL = os.environ.get('SLACK_INVITE_URL', '')
SLACK_ANNOUNCEMENTS_CHANNEL_ID = os.environ.get('SLACK_ANNOUNCEMENTS_CHANNEL_ID', '') if SLACK_ENABLED else ''

# Cache configuration
# django-q writes cluster heartbeats (used by the /studio/worker/ dashboard)
# to Django's cache backend. The default LocMemCache is per-process, so the
# qcluster's heartbeats are invisible to the gunicorn / runserver process —
# the dashboard always reports "Worker NOT running" even when the cluster is
# healthy. We use a dedicated `django_q` cache that is shared across
# processes:
#
# - Tests: LocMemCache. Single-process, fast, isolated per run. The
#   cross-process behaviour is exercised explicitly in
#   `studio/tests/test_worker_health_cache.py` via a real subprocess + a
#   tmpdir FileBasedCache.
# - Local dev / production: FileBasedCache by default (zero-deps,
#   cross-process). Override the directory with `CACHE_DIR` env var.
#
# `Q_CLUSTER['cache'] = 'django_q'` (below) tells django-q to use this
# named cache rather than `default`, so the application's own cache usage
# (if any) doesn't share a namespace with cluster heartbeats.
if TESTING:
    _django_q_cache = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'django-q-test',
    }
else:
    # FileBasedCache creates LOCATION lazily on first write — no makedirs here.
    _cache_dir = os.environ.get('CACHE_DIR') or str(BASE_DIR / '.django_cache')
    _django_q_cache = {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': _cache_dir,
    }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'django_q': _django_q_cache,
}

# Django-Q2 task queue configuration
# Default workers=1 on SQLite — concurrent writers serialise on the file lock
# and surface as "database is locked" during bulk syncs. Override with
# Q_WORKERS=N on Postgres deployments.
if 'sqlite' in DATABASES['default']['ENGINE']:
    _default_q_workers = 1
else:
    _default_q_workers = 2
Q_CLUSTER = {
    'name': 'ai-shipping-labs',
    'workers': int(os.environ.get('Q_WORKERS', _default_q_workers)),
    'timeout': 300,           # Task timeout in seconds (5 min)
    'retry': 360,             # Retry timeout in seconds (6 min, must be > timeout)
    'max_attempts': 3,        # Default max attempts (1 initial + 2 retries)
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',         # Use the default database as broker
    'cache': 'django_q',      # Named cache for cluster heartbeats (cross-process)
    'save_limit': 250,        # Keep last 250 task results
    # Heartbeats are written by the guard loop and stored in the cache
    # with a hardcoded 3 s TTL (see django_q.status.Stat.save). Keep
    # guard_cycle <= 2 s so writes always overlap the TTL — otherwise
    # the worker dashboard flickers between alive and dead between
    # cycles.
    'guard_cycle': 2,
    'poll': 5,                # Worker polls every 5 seconds
    'catch_up': False,        # Don't catch up on missed schedules
    'sync': os.environ.get('Q_SYNC', '') == 'true',  # Sync mode for testing
}
