# Generated by Django 6.0.2 on 2026-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreminderlog',
            name='interval',
            field=models.CharField(help_text='Reminder interval: "24h" or "20m".', max_length=10),
        ),
    ]
