# Generated by Django 6.0.2 on 2026-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_eventreminderlog_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreminderlog',
            name='interval',
            field=models.CharField(help_text='Reminder interval: "24h" or "20m" for pre-event reminders, "followup" for the post-event recap email (issue #680).', max_length=10),
        ),
    ]
