# Generated by Django 6.0.2 on 2026-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_eventreminderlog_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_content', 'New Content'), ('event_reminder', 'Event Reminder'), ('announcement', 'Announcement'), ('plan_request', 'Plan Request'), ('plan_shared', 'Plan Shared')], default='new_content', max_length=20),
        ),
    ]
