# Generated by Django 6.0.2 on 2026-06-08 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreminderlog',
            name='interval',
            field=models.CharField(help_text='Reminder interval: "24h" or "20m" for pre-event reminders, "followup" for the post-event recap email (issue #680), "24h_slack" for the per-event channel announcement guard (issue #887).', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventreminderlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='NULL for per-event guard rows (e.g. the "24h_slack" channel announcement marker, issue #887). Set for per-user reminders.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reminder_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
