# Generated by Django 6.0.2 on 2026-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_eventreminderlog_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_content', 'New Content'), ('event_reminder', 'Event Reminder'), ('announcement', 'Announcement'), ('plan_request', 'Plan Request'), ('plan_shared', 'Plan Shared'), ('onboarding_submitted', 'Onboarding Submitted')], default='new_content', max_length=20),
        ),
    ]
