# Generated by Django 6.0.2 on 2026-08-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread_content_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Exact comment-thread UUID for content-comment notifications.', null=True),
        ),
    ]
