# Generated by Django 6.0.2 on 2026-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_notification_thread_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_content', 'New Content'), ('event_reminder', 'Event Reminder'), ('announcement', 'Announcement'), ('plan_request', 'Plan Request'), ('plan_shared', 'Plan Shared'), ('sprint_recap', 'Sprint Recap'), ('onboarding_submitted', 'Onboarding Submitted'), ('sprint_week_start', 'Sprint Week Start'), ('week_note_prompt', 'Week Note Prompt'), ('slack_progress', 'Slack Progress'), ('content_comment', 'Content Comment'), ('bookclub_summary', 'Book Club Summary'), ('event_recap', 'Event Recap')], default='new_content', max_length=20),
        ),
    ]
